// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.orderslineitems

import app.sell.sellapp.SellApp
import app.sell.sellapp.common.http.Page
import app.sell.sellapp.common.http.RawResponse
import app.sell.sellapp.common.http.RequestConfig
import app.sell.sellapp.common.http.RequestOptions
import app.sell.sellapp.common.http.encodePathSegment
import app.sell.sellapp.common.json.runtimeSchema
import app.sell.sellapp.models.ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItem
import app.sell.sellapp.models.SdkGetOrderSLineItemResponseValue200ApplicationJson
import app.sell.sellapp.models.SearchOrderSLineItemsRequestApplicationJsonPropertyFiltersItem
import app.sell.sellapp.models.SearchOrderSLineItemsRequestApplicationJsonPropertyPagination
import app.sell.sellapp.models.SearchOrderSLineItemsRequestApplicationJsonPropertySortItem
import app.sell.sellapp.models.SearchOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItem
import com.fasterxml.jackson.core.type.TypeReference

/**
 * API accessor for OrdersLineItems.
 *
 * Every operation on this class is available in two flavors: a blocking variant (`<methodName>`)
 * and a coroutine-aware variant (`<methodName>Suspend`). The `Suspend` variants delegate to the
 * blocking ones under `withContext(Dispatchers.IO)`, so they are safe to call from any coroutine
 * dispatcher (including `Dispatchers.Main`).
 */
class OrdersLineItems(internal val sellapp: SellApp) {
    /**
     * List an order's line items
     *
     * List purchase line items for the selected store. Requires the `invoice` API-key ability or
     * the corresponding OAuth scope and current store permission. The order path parameter scopes
     * the result and must match the line item's parent order. OAuth callers use the admin grant and
     * select a store with X-STORE. Current membership and role permissions apply to every request.
     *
     * @param order The parent order ID.
     * @param limit Maximum number of line items per page.
     * @param page One-based result page.
     * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
     * @return a [app.sell.sellapp.common.http.Page] of results
     */
    @JvmOverloads
    fun list(
        order: String,
        limit: Int? = null,
        page: Long? = null,
        requestOptions: RequestOptions? = null,
    ): Page<ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItem> {
        val itemType =
            object :
                TypeReference<
                    ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItem
                >() {}
        return sellapp.baseClient.requestPage(
            method = "GET",
            path = "/v2/orders/${encodePathSegment(order)}/line-items",
            itemType = itemType,
            requestOptions = requestOptions,
            operationId = "listOrderSLineItems",
            supportsIdempotency = false,
            itemSchema =
                app.sell.sellapp.models
                    .ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItem
                    .runtimeSchema,
            before = null,
            after = null,
        ) {
            limit?.let { add("limit" to it.toString()) }
            page?.let { add("page" to it.toString()) }
        }
    }

    @Suppress("UNCHECKED_CAST")
    fun listWithResponse(
        order: String,
        limit: Int? = null,
        page: Long? = null,
        requestOptions: RequestOptions? = null,
    ): RawResponse<Page<ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItem>> {
        var captured: RawResponse<Any?>? = null
        val capturingOptions =
            (requestOptions?.copy() ?: RequestOptions()).also { options ->
                options.responseCapture = { response -> captured = response }
            }
        list(order, limit, page, capturingOptions)
        return captured
            as?
            RawResponse<Page<ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItem>>
            ?: error("Response metadata was not captured")
    }

    /**
     * Coroutine-aware variant of [list]. Use this from a `suspend` function or coroutine scope.
     *
     * Delegates to the blocking [list] under `withContext(Dispatchers.IO)`, so this is safe to call
     * from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("listSuspend")
    suspend fun listSuspend(
        order: String,
        limit: Int? = null,
        page: Long? = null,
        requestOptions: RequestOptions? = null,
    ): Page<ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItem> =
        sellapp.baseClient.runCancellable {
            list(order, limit, page, requestOptions)
        }

    /**
     * Coroutine-aware variant of [listWithResponse]. Use this from a `suspend` function or
     * coroutine scope.
     *
     * Delegates to the blocking [listWithResponse] under `withContext(Dispatchers.IO)`, so this is
     * safe to call from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("listWithResponseSuspend")
    suspend fun listWithResponseSuspend(
        order: String,
        limit: Int? = null,
        page: Long? = null,
        requestOptions: RequestOptions? = null,
    ): RawResponse<Page<ListOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItem>> =
        sellapp.baseClient.runCancellable {
            listWithResponse(order, limit, page, requestOptions)
        }

    /**
     * Search an order's line items
     *
     * Search product-level sale records with filters and sorting. Requires the `invoice` token
     * ability. The order path parameter scopes the result and must match the line item's parent
     * order. OAuth callers use the admin grant and select a store with X-STORE. Current membership
     * and role permissions apply to every request.
     *
     * @param order The parent order ID.
     * @param filters the filters of the request.
     * @param sort the sort of the request.
     * @param pagination the pagination of the request.
     * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
     * @return a [app.sell.sellapp.common.http.Page] of results
     */
    @JvmOverloads
    fun search(
        order: String,
        filters: List<SearchOrderSLineItemsRequestApplicationJsonPropertyFiltersItem>? = null,
        sort: List<SearchOrderSLineItemsRequestApplicationJsonPropertySortItem>? = null,
        pagination: SearchOrderSLineItemsRequestApplicationJsonPropertyPagination? = null,
        requestOptions: RequestOptions? = null,
    ): Page<SearchOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItem> {
        val itemType =
            object :
                TypeReference<
                    SearchOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItem
                >() {}
        return sellapp.baseClient.requestPage(
            method = "POST",
            path = "/v2/orders/${encodePathSegment(order)}/line-items/search",
            itemType = itemType,
            requestOptions = requestOptions,
            operationId = "searchOrderSLineItems",
            supportsIdempotency = false,
            itemSchema =
                app.sell.sellapp.models
                    .SearchOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItem
                    .runtimeSchema,
            before = null,
            after = null,
        ) {}
    }

    @Suppress("UNCHECKED_CAST")
    fun searchWithResponse(
        order: String,
        filters: List<SearchOrderSLineItemsRequestApplicationJsonPropertyFiltersItem>? = null,
        sort: List<SearchOrderSLineItemsRequestApplicationJsonPropertySortItem>? = null,
        pagination: SearchOrderSLineItemsRequestApplicationJsonPropertyPagination? = null,
        requestOptions: RequestOptions? = null,
    ): RawResponse<Page<SearchOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItem>> {
        var captured: RawResponse<Any?>? = null
        val capturingOptions =
            (requestOptions?.copy() ?: RequestOptions()).also { options ->
                options.responseCapture = { response -> captured = response }
            }
        search(order, filters, sort, pagination, capturingOptions)
        return captured
            as?
            RawResponse<Page<SearchOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItem>>
            ?: error("Response metadata was not captured")
    }

    /**
     * Coroutine-aware variant of [search]. Use this from a `suspend` function or coroutine scope.
     *
     * Delegates to the blocking [search] under `withContext(Dispatchers.IO)`, so this is safe to
     * call from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("searchSuspend")
    suspend fun searchSuspend(
        order: String,
        filters: List<SearchOrderSLineItemsRequestApplicationJsonPropertyFiltersItem>? = null,
        sort: List<SearchOrderSLineItemsRequestApplicationJsonPropertySortItem>? = null,
        pagination: SearchOrderSLineItemsRequestApplicationJsonPropertyPagination? = null,
        requestOptions: RequestOptions? = null,
    ): Page<SearchOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItem> =
        sellapp.baseClient.runCancellable {
            search(order, filters, sort, pagination, requestOptions)
        }

    /**
     * Coroutine-aware variant of [searchWithResponse]. Use this from a `suspend` function or
     * coroutine scope.
     *
     * Delegates to the blocking [searchWithResponse] under `withContext(Dispatchers.IO)`, so this
     * is safe to call from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("searchWithResponseSuspend")
    suspend fun searchWithResponseSuspend(
        order: String,
        filters: List<SearchOrderSLineItemsRequestApplicationJsonPropertyFiltersItem>? = null,
        sort: List<SearchOrderSLineItemsRequestApplicationJsonPropertySortItem>? = null,
        pagination: SearchOrderSLineItemsRequestApplicationJsonPropertyPagination? = null,
        requestOptions: RequestOptions? = null,
    ): RawResponse<Page<SearchOrderSLineItemsResponseValue200ApplicationJsonPropertyDataItem>> =
        sellapp.baseClient.runCancellable {
            searchWithResponse(order, filters, sort, pagination, requestOptions)
        }

    /**
     * Retrieve an order's line item
     *
     * Retrieve one product-level sale record for the selected store. Requires the `invoice` token
     * ability. Records from another store or whose order does not match the store return `404`. The
     * order path parameter scopes the result and must match the line item's parent order. OAuth
     * callers use the admin grant and select a store with X-STORE. Current membership and role
     * permissions apply to every request.
     *
     * @param order The parent order ID.
     * @param lineItem The purchase line-item ID.
     * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
     * @return the SdkGetOrderSLineItemResponseValue200ApplicationJson
     */
    @JvmOverloads
    fun get(
        order: String,
        lineItem: String,
        requestOptions: RequestOptions? = null,
    ): SdkGetOrderSLineItemResponseValue200ApplicationJson {
        val config =
            RequestConfig(
                method = "GET",
                path =
                    "/v2/orders/${encodePathSegment(order)}/line-items/${encodePathSegment(lineItem)}",
                requestOptions = requestOptions,
                responseSchema =
                    app.sell.sellapp.models.SdkGetOrderSLineItemResponseValue200ApplicationJson
                        .runtimeSchema,
                operationId = "getOrderSLineItem",
                supportsIdempotency = false,
            )
        return sellapp.baseClient.request(
            config,
            SdkGetOrderSLineItemResponseValue200ApplicationJson::class.java,
        )
    }

    @Suppress("UNCHECKED_CAST")
    fun getWithResponse(
        order: String,
        lineItem: String,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkGetOrderSLineItemResponseValue200ApplicationJson> {
        var captured: RawResponse<Any?>? = null
        val capturingOptions =
            (requestOptions?.copy() ?: RequestOptions()).also { options ->
                options.responseCapture = { response -> captured = response }
            }
        get(order, lineItem, capturingOptions)
        return captured as? RawResponse<SdkGetOrderSLineItemResponseValue200ApplicationJson>
            ?: error("Response metadata was not captured")
    }

    /**
     * Coroutine-aware variant of [get]. Use this from a `suspend` function or coroutine scope.
     *
     * Delegates to the blocking [get] under `withContext(Dispatchers.IO)`, so this is safe to call
     * from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("getSuspend")
    suspend fun getSuspend(
        order: String,
        lineItem: String,
        requestOptions: RequestOptions? = null,
    ): SdkGetOrderSLineItemResponseValue200ApplicationJson =
        sellapp.baseClient.runCancellable {
            get(order, lineItem, requestOptions)
        }

    /**
     * Coroutine-aware variant of [getWithResponse]. Use this from a `suspend` function or coroutine
     * scope.
     *
     * Delegates to the blocking [getWithResponse] under `withContext(Dispatchers.IO)`, so this is
     * safe to call from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("getWithResponseSuspend")
    suspend fun getWithResponseSuspend(
        order: String,
        lineItem: String,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkGetOrderSLineItemResponseValue200ApplicationJson> =
        sellapp.baseClient.runCancellable {
            getWithResponse(order, lineItem, requestOptions)
        }
}
