// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.exports

import app.sell.sellapp.common.exceptions.GenericServerException
import app.sell.sellapp.common.exceptions.NotFoundException
import app.sell.sellapp.common.exceptions.RateLimitException
import app.sell.sellapp.common.exceptions.UnauthorizedException
import app.sell.sellapp.test.TestBase
import app.sell.sellapp.types.SdkCreateExportRequestApplicationJsonFormat
import app.sell.sellapp.types.SdkCreateExportRequestApplicationJsonType
import com.github.tomakehurst.wiremock.client.WireMock.getRequestedFor
import com.github.tomakehurst.wiremock.client.WireMock.matching
import com.github.tomakehurst.wiremock.client.WireMock.matchingJsonPath
import com.github.tomakehurst.wiremock.client.WireMock.postRequestedFor
import com.github.tomakehurst.wiremock.client.WireMock.urlPathMatching
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.Test

class ExportsTest : TestBase() {
    private fun api() = Exports(createSellAppClient())

    @Test
    fun `list returns a typed response`() {
        stubResponse(
            "GET",
            "/v2/exports",
            200,
            "{\"data\": [], \"list_metadata\": {\"before\": null, \"after\": null}}",
        )
        val result = api().list()
        assertNotNull(result)
    }

    @Test
    fun `create returns a typed response`() {
        stubResponse(
            "POST",
            "/v2/exports",
            200,
            "{\"data\": {\"id\": \"sample\", \"type\": \"sales\", \"format\": \"csv\", \"status\": \"pending\", \"parameters\": {}, " +
                "\"filename\": null, \"content_type\": null, \"size\": null, \"failure_message\": null, \"started_at\": null, \"completed_at\": " +
                "null, \"failed_at\": null, \"expires_at\": null, \"created_at\": \"2024-01-01T00:00:00Z\", \"updated_at\": null}, \"meta\": " +
                "{\"poll_after_seconds\": 1}}",
        )
        val result =
            api()
                .create(
                    type =
                        SdkCreateExportRequestApplicationJsonType.values().first {
                            it != SdkCreateExportRequestApplicationJsonType.Unknown
                        },
                    format =
                        SdkCreateExportRequestApplicationJsonFormat.values().first {
                            it != SdkCreateExportRequestApplicationJsonFormat.Unknown
                        },
                )
        assertNotNull(result)
        wireMockRule.verify(
            postRequestedFor(urlPathMatching("/v2/exports"))
                .withRequestBody(matchingJsonPath("\$.type"))
                .withRequestBody(matchingJsonPath("\$.format"))
        )
    }

    @Test
    fun `get returns a typed response`() {
        stubResponse(
            "GET",
            "/v2/exports/sample-arg",
            200,
            "{\"data\": {\"id\": \"sample\", \"type\": \"sales\", \"format\": \"csv\", \"status\": \"pending\", \"parameters\": {}, " +
                "\"filename\": null, \"content_type\": null, \"size\": null, \"failure_message\": null, \"started_at\": null, \"completed_at\": " +
                "null, \"failed_at\": null, \"expires_at\": null, \"created_at\": \"2024-01-01T00:00:00Z\", \"updated_at\": null}}",
        )
        val result = api().get("sample-arg")
        assertNotNull(result)
    }

    @Test
    fun `download completes without throwing`() {
        stubResponse("GET", "/v2/exports/sample-arg/download", 200)
        api().download("sample-arg", 0, "sample-arg")
        wireMockRule.verify(
            getRequestedFor(urlPathMatching("/v2/exports/sample-arg/download"))
                .withQueryParam("expires", matching("0"))
                .withQueryParam("signature", matching("sample-arg"))
        )
    }

    @Test
    fun `list translates 401 to UnauthorizedException`() {
        stubResponse("GET", "/v2/exports", 401)
        assertThrows(UnauthorizedException::class.java) {
            api().list()
        }
    }

    @Test
    fun `list translates 404 to NotFoundException`() {
        stubResponse("GET", "/v2/exports", 404)
        assertThrows(NotFoundException::class.java) {
            api().list()
        }
    }

    @Test
    fun `list translates 429 to RateLimitException`() {
        stubResponse("GET", "/v2/exports", 429)
        assertThrows(RateLimitException::class.java) {
            api().list()
        }
    }

    @Test
    fun `list translates 500 to GenericServerException`() {
        stubResponse("GET", "/v2/exports", 500)
        assertThrows(GenericServerException::class.java) {
            api().list()
        }
    }
}
