// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode
import java.time.OffsetDateTime

/** ActivateLicenseKeyResponseValue200ApplicationJsonPropertyData model. */
data class ActivateLicenseKeyResponseValue200ApplicationJsonPropertyData(
    /** The id. */
    @JsonProperty("id") val id: String,

    /** The license key id. */
    @JsonProperty("license_key_id") val licenseKeyId: Long,

    /** The name. */
    @JsonProperty("name") val name: String,

    /** The store id. */
    @JsonProperty("store_id") val storeId: Long,

    /** The created at. */
    @JsonProperty("created_at") val createdAt: OffsetDateTime,

    /** The updated at. */
    @JsonProperty("updated_at") val updatedAt: OffsetDateTime,
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"ActivateLicenseKeyResponseValue200ApplicationJsonPropertyData\",\"properties\":{\"id\":{\"kind\":\"primitive\",\"type\":\"string\"},\"license_key_id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"name\":{\"kind\":\"primitive\",\"type\":\"string\"},\"store_id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"created_at\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"},\"updated_at\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"}},\"required\":[\"id\",\"license_key_id\",\"name\",\"store_id\",\"created_at\",\"updated_at\"],\"additionalProperties\":true}"
            )
    }
}
