// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode

/** AppendVariantSerialInventoryResponseValue201ApplicationJsonPropertyData model. */
data class AppendVariantSerialInventoryResponseValue201ApplicationJsonPropertyData(
    /** The previous count. */
    @JsonProperty("previous_count") val previousCount: Long,

    /** The current count. */
    @JsonProperty("current_count") val currentCount: Long,

    /** The submitted count. */
    @JsonProperty("submitted_count") val submittedCount: Long,
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"AppendVariantSerialInventoryResponseValue201ApplicationJsonPropertyData\",\"properties\":{\"previous_count\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":0}},\"current_count\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":0}},\"submitted_count\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":0}}},\"required\":[\"previous_count\",\"current_count\",\"submitted_count\"],\"additionalProperties\":true}"
            )
    }
}
