// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/** Alias for [GetProductVariantResponseValue200ApplicationJsonPropertyDataPropertyDeliverable]. */
typealias BatchUpdateProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverable =
    GetProductVariantResponseValue200ApplicationJsonPropertyDataPropertyDeliverable
