// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/**
 * Alias for
 * [GetProductVariantResponseValue200ApplicationJsonPropertyDataPropertyDeliverablePropertyData].
 */
typealias BatchDeleteProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverablePropertyData =
    GetProductVariantResponseValue200ApplicationJsonPropertyDataPropertyDeliverablePropertyData
