// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/**
 * Alias for
 * [GetBundleItemResponseValue200ApplicationJsonPropertyDataPropertyPricingPropertyFrequency].
 */
typealias BatchCreateProductVariantsResponseValue201ApplicationJsonPropertyDataItemPropertyPricingPropertyFrequency =
    GetBundleItemResponseValue200ApplicationJsonPropertyDataPropertyPricingPropertyFrequency
