// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/** Alias for [GetGroupResponseValue200ApplicationJsonPropertyDataPropertyProductsItem]. */
typealias BatchUpdateSectionsResponseValue200ApplicationJsonPropertyDataItemPropertyProductsItem =
    GetGroupResponseValue200ApplicationJsonPropertyDataPropertyProductsItem
