// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/** Alias for [GetBundleItemResponseValue200ApplicationJsonPropertyDataPropertyProduct]. */
typealias CreateProductVariantResponseValue201ApplicationJsonPropertyDataPropertyProduct =
    GetBundleItemResponseValue200ApplicationJsonPropertyDataPropertyProduct
