// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/** Alias for [GetCouponResponseValue200ApplicationJsonPropertyData]. */
typealias CreateCouponResponseValue201ApplicationJsonPropertyData =
    GetCouponResponseValue200ApplicationJsonPropertyData
