// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode
import java.time.OffsetDateTime

/** CreateBookingHoldResponseValue201ApplicationJsonPropertyData model. */
data class CreateBookingHoldResponseValue201ApplicationJsonPropertyData(
    /** The id. */
    @JsonProperty("id") val id: String,

    /** The slot start at. */
    @JsonProperty("slot_start_at") val slotStartAt: OffsetDateTime,

    /** The slot end at. */
    @JsonProperty("slot_end_at") val slotEndAt: OffsetDateTime,

    /** The quantity. */
    @JsonProperty("quantity") val quantity: Long,

    /** The expires at. */
    @JsonProperty("expires_at") val expiresAt: OffsetDateTime,
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"CreateBookingHoldResponseValue201ApplicationJsonPropertyData\",\"properties\":{\"id\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"uuid\"},\"slot_start_at\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"},\"slot_end_at\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"},\"quantity\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"expires_at\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"}},\"required\":[\"id\",\"slot_start_at\",\"slot_end_at\",\"quantity\",\"expires_at\"],\"additionalProperties\":true}"
            )
    }
}
