// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/** Alias for [GetOrderResponseValue200ApplicationJsonPropertyDataPropertyCustomer]. */
typealias CreateOrderResponseValue201ApplicationJsonPropertyDataPropertyCustomer =
    GetOrderResponseValue200ApplicationJsonPropertyDataPropertyCustomer
