// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/** Alias for [GetCustomPaymentMethodResponseValue200ApplicationJsonPropertyData]. */
typealias CreateCustomPaymentMethodResponseValue201ApplicationJsonPropertyData =
    GetCustomPaymentMethodResponseValue200ApplicationJsonPropertyData
