// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/**
 * Alias for
 * [UpdateInvoiceStatusResponseValue200ApplicationJsonPropertyPaymentPropertyFeePropertyTotal].
 */
typealias CreateCheckoutSessionResponseValue201ApplicationJsonPropertyInvoicePropertyPaymentPropertyFeePropertyTotal =
    UpdateInvoiceStatusResponseValue200ApplicationJsonPropertyPaymentPropertyFeePropertyTotal
