// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import app.sell.sellapp.types.CreateCourseLessonRequestApplicationJsonPropertyQuestionsItemQuestionType
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode
import java.time.OffsetDateTime

/** CreateCourseLessonResponseValue201ApplicationJsonPropertyDataPropertyQuestionsItem model. */
data class CreateCourseLessonResponseValue201ApplicationJsonPropertyDataPropertyQuestionsItem(
    /** The id. */
    @JsonProperty("id") val id: Long,

    /** The prompt. */
    @JsonProperty("prompt") val prompt: String,

    /** The question type. */
    @JsonProperty("question_type")
    val questionType: CreateCourseLessonRequestApplicationJsonPropertyQuestionsItemQuestionType,

    /** The solution. */
    @JsonProperty("solution") val solution: String?,

    /** The sort order. */
    @JsonProperty("sort_order") val sortOrder: Long,

    /** The answers. */
    @JsonProperty("answers")
    val answers:
        List<
            CreateCourseLessonResponseValue201ApplicationJsonPropertyDataPropertyQuestionsItemPropertyAnswersItem
        >,

    /** The created at. */
    @JsonProperty("created_at") val createdAt: OffsetDateTime,

    /** The updated at. */
    @JsonProperty("updated_at") val updatedAt: OffsetDateTime,
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"CreateCourseLessonResponseValue201ApplicationJsonPropertyDataPropertyQuestionsItem\",\"properties\":{\"id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"prompt\":{\"kind\":\"primitive\",\"type\":\"string\"},\"question_type\":{\"kind\":\"enum\",\"values\":[\"text\",\"single_choice\",\"multiple_choice\"]},\"solution\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"sort_order\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":1}},\"answers\":{\"kind\":\"array\",\"items\":{\"kind\":\"object\",\"modelName\":\"CreateCourseLessonResponseValue201ApplicationJsonPropertyDataPropertyQuestionsItemPropertyAnswersItem\",\"properties\":{\"id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"answer\":{\"kind\":\"primitive\",\"type\":\"string\"},\"is_correct\":{\"kind\":\"primitive\",\"type\":\"boolean\"},\"sort_order\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":1}}},\"required\":[\"id\",\"answer\",\"is_correct\",\"sort_order\"],\"additionalProperties\":true}},\"created_at\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"},\"updated_at\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"}},\"required\":[\"id\",\"prompt\",\"question_type\",\"solution\",\"sort_order\",\"answers\",\"created_at\",\"updated_at\"],\"additionalProperties\":true}"
            )
    }
}
