// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/** Alias for [GetOrderResponseValue200ApplicationJsonPropertyDataPropertyTimelineItem]. */
typealias CreateOrderRefundResponseValue200ApplicationJsonPropertyDataPropertyOrderPropertyTimelineItem =
    GetOrderResponseValue200ApplicationJsonPropertyDataPropertyTimelineItem
