// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode

/** CreateCustomerSessionRequestApplicationJsonOneOfValue1 model. */
data class CreateCustomerSessionRequestApplicationJsonOneOfValue1(
    /** The customer id. */
    @JsonProperty("customer_id") val customerId: Long
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"CreateCustomerSessionRequestApplicationJsonOneOfValue1\",\"properties\":{\"customer_id\":{\"kind\":\"primitive\",\"type\":\"integer\"}},\"required\":[\"customer_id\"],\"additionalProperties\":false}"
            )
    }
}
