// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode

/** CursorExpiredErrorFallback model. */
data class CursorExpiredErrorFallback(
    /** The url. */
    @JsonProperty("url") val url: String,

    /** Always `"cursor_polling"`. */
    @JsonProperty("transport") val transport: String = "cursor_polling",
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"CursorExpiredErrorFallback\",\"properties\":{\"transport\":{\"kind\":\"literal\",\"value\":\"cursor_polling\"},\"url\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"uri\"}},\"required\":[\"transport\",\"url\"],\"additionalProperties\":true}"
            )
    }
}
