// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/**
 * Alias for
 * [GetGroupResponseValue200ApplicationJsonPropertyDataPropertyImageValuePropertyMetadata].
 */
typealias DeleteGroupResponseValue200ApplicationJsonPropertyDataPropertyImageValuePropertyMetadata =
    GetGroupResponseValue200ApplicationJsonPropertyDataPropertyImageValuePropertyMetadata
