// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonInclude
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode
import java.time.OffsetDateTime

/** GetAffiliateReferralSessionResponseValue200ApplicationJsonPropertyData model. */
data class GetAffiliateReferralSessionResponseValue200ApplicationJsonPropertyData(
    /** The id. */
    @JsonProperty("id") val id: Long,

    /** The tracked referral session identifier. Treat this value as sensitive. */
    @JsonProperty("session_id") val sessionId: String,

    /** The affiliate id. */
    @JsonProperty("affiliate_id") val affiliateId: Long,

    /** The affiliate email. */
    @JsonProperty("affiliate_email")
    @get:JsonInclude(JsonInclude.Include.NON_NULL)
    val affiliateEmail: String? = null,

    /** The expires at. */
    @JsonProperty("expires_at") val expiresAt: OffsetDateTime? = null,

    /** The created at. */
    @JsonProperty("created_at")
    @get:JsonInclude(JsonInclude.Include.NON_NULL)
    val createdAt: OffsetDateTime? = null,

    /** The updated at. */
    @JsonProperty("updated_at")
    @get:JsonInclude(JsonInclude.Include.NON_NULL)
    val updatedAt: OffsetDateTime? = null,
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"GetAffiliateReferralSessionResponseValue200ApplicationJsonPropertyData\",\"properties\":{\"id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"session_id\":{\"kind\":\"primitive\",\"type\":\"string\"},\"affiliate_id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"affiliate_email\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"email\"},\"expires_at\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"}},\"created_at\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"},\"updated_at\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"}},\"required\":[\"id\",\"session_id\",\"affiliate_id\"],\"additionalProperties\":true}"
            )
    }
}
