// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import app.sell.sellapp.types.GetAffiliatePayoutResponseValue200ApplicationJsonPropertyDataStatus
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonInclude
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode
import java.time.OffsetDateTime

/** GetAffiliatePayoutResponseValue200ApplicationJsonPropertyData model. */
data class GetAffiliatePayoutResponseValue200ApplicationJsonPropertyData(
    /** The id. */
    @JsonProperty("id") val id: Long,

    /** The affiliate id. */
    @JsonProperty("affiliate_id") val affiliateId: Long,

    /** The amount usd cents. */
    @JsonProperty("amount_usd_cents") val amountUsdCents: Long,

    /** The status. */
    @JsonProperty("status")
    val status: GetAffiliatePayoutResponseValue200ApplicationJsonPropertyDataStatus,

    /** A masked payout destination. Full payout credentials are never returned. */
    @JsonProperty("payout_account") val payoutAccount: String,

    /** The referrals count. */
    @JsonProperty("referrals_count") val referralsCount: Long,

    /** The affiliate email. */
    @JsonProperty("affiliate_email")
    @get:JsonInclude(JsonInclude.Include.NON_NULL)
    val affiliateEmail: String? = null,

    /** The payout method. */
    @JsonProperty("payout_method") val payoutMethod: String? = null,

    /** The created at. */
    @JsonProperty("created_at")
    @get:JsonInclude(JsonInclude.Include.NON_NULL)
    val createdAt: OffsetDateTime? = null,

    /** The updated at. */
    @JsonProperty("updated_at")
    @get:JsonInclude(JsonInclude.Include.NON_NULL)
    val updatedAt: OffsetDateTime? = null,
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"GetAffiliatePayoutResponseValue200ApplicationJsonPropertyData\",\"properties\":{\"id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"affiliate_id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"affiliate_email\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"email\"},\"amount_usd_cents\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":0}},\"status\":{\"kind\":\"enum\",\"values\":[\"due\",\"paid\",\"cancelled\"]},\"payout_method\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"payout_account\":{\"kind\":\"primitive\",\"type\":\"string\"},\"referrals_count\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":0}},\"created_at\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"},\"updated_at\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"}},\"required\":[\"id\",\"affiliate_id\",\"amount_usd_cents\",\"status\",\"payout_account\",\"referrals_count\"],\"additionalProperties\":true}"
            )
    }
}
