// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode

/**
 * GetAffiliateProgramConfigurationResponseValue200ApplicationJsonPropertyDataPropertyProductsItem
 * model.
 */
data class GetAffiliateProgramConfigurationResponseValue200ApplicationJsonPropertyDataPropertyProductsItem(
    /** The id. */
    @JsonProperty("id") val id: Long,

    /** The product id. */
    @JsonProperty("product_id") val productId: Long,

    /** The product title. */
    @JsonProperty("product_title") val productTitle: String,

    /** The variant title. */
    @JsonProperty("variant_title") val variantTitle: String,

    /** The commission. */
    @JsonProperty("commission")
    val commission:
        GetAffiliateProgramConfigurationResponseValue200ApplicationJsonPropertyDataPropertyProductsItemPropertyCommission,

    /** Always `true`. */
    @JsonProperty("enabled") val enabled: Boolean = true,
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"GetAffiliateProgramConfigurationResponseValue200ApplicationJsonPropertyDataPropertyProductsItem\",\"properties\":{\"id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"product_id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"product_title\":{\"kind\":\"primitive\",\"type\":\"string\"},\"variant_title\":{\"kind\":\"primitive\",\"type\":\"string\"},\"enabled\":{\"kind\":\"literal\",\"value\":true},\"commission\":{\"kind\":\"object\",\"modelName\":\"GetAffiliateProgramConfigurationResponseValue200ApplicationJsonPropertyDataPropertyProductsItemPropertyCommission\",\"properties\":{\"type\":{\"kind\":\"enum\",\"values\":[\"percentage\",\"fixed\"]},\"percentage\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"amount_usd_cents\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":1}}}},\"required\":[\"type\",\"percentage\",\"amount_usd_cents\"],\"additionalProperties\":true}},\"required\":[\"id\",\"product_id\",\"product_title\",\"variant_title\",\"enabled\",\"commission\"],\"additionalProperties\":true}"
            )
    }
}
