// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/** Alias for [CreateCustomPaymentMethodRequestApplicationJsonPropertyModifier]. */
typealias GetCustomPaymentMethodResponseValue200ApplicationJsonPropertyDataPropertyModifier =
    CreateCustomPaymentMethodRequestApplicationJsonPropertyModifier
