// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode

/** GetChargeResponseValue200ApplicationJsonPropertyData model. */
data class GetChargeResponseValue200ApplicationJsonPropertyData(
    /** The id. */
    @JsonProperty("id") val id: Long,

    /** The url. */
    @JsonProperty("url") val url: String,

    /** The status. */
    @JsonProperty("status") val status: String,

    /**
     * Selected custom payment method ULID, or null when no custom method was selected. The saved
     * checkout configuration remains available after the method is edited or deleted.
     */
    @JsonProperty("custom_payment_method_id") val customPaymentMethodId: String?,
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"GetChargeResponseValue200ApplicationJsonPropertyData\",\"properties\":{\"id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"url\":{\"kind\":\"primitive\",\"type\":\"string\"},\"status\":{\"kind\":\"primitive\",\"type\":\"string\"},\"custom_payment_method_id\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\"}}},\"required\":[\"id\",\"url\",\"status\",\"custom_payment_method_id\"],\"additionalProperties\":true}"
            )
    }
}
