// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonInclude
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode

/** GetGroupResponseValue200ApplicationJsonPropertyDataPropertyImageValuePropertyMetadata model. */
data class GetGroupResponseValue200ApplicationJsonPropertyDataPropertyImageValuePropertyMetadata(
    /** The size. */
    @JsonProperty("size") @get:JsonInclude(JsonInclude.Include.NON_NULL) val size: Long? = null,

    /** The filename. */
    @JsonProperty("filename")
    @get:JsonInclude(JsonInclude.Include.NON_NULL)
    val filename: String? = null,

    /** The extension. */
    @JsonProperty("extension")
    @get:JsonInclude(JsonInclude.Include.NON_NULL)
    val extension: String? = null,

    /** The mime type. */
    @JsonProperty("mime_type")
    @get:JsonInclude(JsonInclude.Include.NON_NULL)
    val mimeType: String? = null,
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"GetGroupResponseValue200ApplicationJsonPropertyDataPropertyImageValuePropertyMetadata\",\"properties\":{\"size\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"filename\":{\"kind\":\"primitive\",\"type\":\"string\"},\"extension\":{\"kind\":\"primitive\",\"type\":\"string\"},\"mime_type\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"required\":[],\"additionalProperties\":true}"
            )
    }
}
