// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode
import java.time.OffsetDateTime

/** GetHighlightResponseValue200ApplicationJsonPropertyData model. */
data class GetHighlightResponseValue200ApplicationJsonPropertyData(
    /** The id. */
    @JsonProperty("id") val id: Long,

    /** The title. */
    @JsonProperty("title") val title: String,

    /** The hidden. */
    @JsonProperty("hidden") val hidden: Boolean,

    /** The sort order. */
    @JsonProperty("sort_order") val sortOrder: Long?,

    /** The published at. */
    @JsonProperty("published_at") val publishedAt: OffsetDateTime?,

    /** The media. */
    @JsonProperty("media")
    val media: List<GetHighlightResponseValue200ApplicationJsonPropertyDataPropertyMediaItem>,

    /** The created at. */
    @JsonProperty("created_at") val createdAt: OffsetDateTime,

    /** The updated at. */
    @JsonProperty("updated_at") val updatedAt: OffsetDateTime,
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"GetHighlightResponseValue200ApplicationJsonPropertyData\",\"properties\":{\"id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"title\":{\"kind\":\"primitive\",\"type\":\"string\"},\"hidden\":{\"kind\":\"primitive\",\"type\":\"boolean\"},\"sort_order\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"integer\"}},\"published_at\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"}},\"media\":{\"kind\":\"array\",\"items\":{\"kind\":\"object\",\"modelName\":\"GetHighlightResponseValue200ApplicationJsonPropertyDataPropertyMediaItem\",\"properties\":{\"id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"sort_order\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"type\":{\"kind\":\"enum\",\"values\":[\"image\",\"video\"]},\"url\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"uri\"},\"filename\":{\"kind\":\"primitive\",\"type\":\"string\"},\"size\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"mime_type\":{\"kind\":\"primitive\",\"type\":\"string\"},\"cta_title\":{\"kind\":\"primitive\",\"type\":\"string\"},\"product_id\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"integer\"}},\"created_at\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"},\"updated_at\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"}},\"required\":[\"id\",\"sort_order\",\"type\",\"url\",\"filename\",\"size\",\"mime_type\",\"cta_title\",\"product_id\",\"created_at\",\"updated_at\"],\"additionalProperties\":true}},\"created_at\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"},\"updated_at\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"}},\"required\":[\"id\",\"title\",\"hidden\",\"sort_order\",\"published_at\",\"media\",\"created_at\",\"updated_at\"],\"additionalProperties\":true}"
            )
    }
}
