// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import app.sell.sellapp.types.CreateProductVariantRequestApplicationJsonPropertyDeliverableTypes
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode

/**
 * GetInvoiceDeliverablesResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverable model.
 */
data class GetInvoiceDeliverablesResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverable(
    /** The types. */
    @JsonProperty("types")
    val types: List<CreateProductVariantRequestApplicationJsonPropertyDeliverableTypes>,

    /** The data. */
    @JsonProperty("data")
    val data:
        GetInvoiceDeliverablesResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverablePropertyData,
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"GetInvoiceDeliverablesResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverable\",\"properties\":{\"types\":{\"kind\":\"array\",\"items\":{\"kind\":\"enum\",\"values\":[\"DOWNLOADABLE\",\"TEXT\",\"DYNAMIC\",\"MANUAL\",\"LICENSE_KEY\",\"BUNDLE\",\"BOOKING\",\"CREDITS\"]}},\"data\":{\"kind\":\"object\",\"modelName\":\"GetInvoiceDeliverablesResponseValue200ApplicationJsonPropertyDataItemPropertyDeliverablePropertyData\",\"properties\":{\"serials\":{\"kind\":\"array\",\"items\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"delivered_files\":{\"kind\":\"array\",\"items\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"uri\"}},\"dynamic\":{\"kind\":\"primitive\",\"type\":\"string\"},\"manual\":{\"kind\":\"primitive\",\"type\":\"string\"},\"license_keys\":{\"kind\":\"array\",\"items\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"credits_granted\":{\"kind\":\"primitive\",\"type\":\"integer\"}},\"required\":[],\"additionalProperties\":true}},\"required\":[\"types\",\"data\"],\"additionalProperties\":true}"
            )
    }
}
