// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode
import java.time.OffsetDateTime

/** GetLicenseKeyResponseValue200ApplicationJsonPropertyData model. */
data class GetLicenseKeyResponseValue200ApplicationJsonPropertyData(
    /** The id. */
    @JsonProperty("id") val id: Long,

    /** The key. */
    @JsonProperty("key") val key: String,

    /** The limit. */
    @JsonProperty("limit") val limit: Long,

    /** The active. */
    @JsonProperty("active") val active: Long,

    /** The status. */
    @JsonProperty("status") val status: String,

    /** The expires at. */
    @JsonProperty("expires_at") val expiresAt: OffsetDateTime?,

    /** The is expired. */
    @JsonProperty("is_expired") val isExpired: Boolean,

    /** The store id. */
    @JsonProperty("store_id") val storeId: Long,

    /** The order id. */
    @JsonProperty("order_id") val orderId: Long?,

    /** The invoice id. */
    @JsonProperty("invoice_id") val invoiceId: Long?,

    /** The product id. */
    @JsonProperty("product_id") val productId: Long,

    /** The variant id. */
    @JsonProperty("variant_id") val variantId: Long,

    /** The customer id. */
    @JsonProperty("customer_id") val customerId: Long,

    /** The subscription id. */
    @JsonProperty("subscription_id") val subscriptionId: Long?,

    /** The created at. */
    @JsonProperty("created_at") val createdAt: OffsetDateTime,

    /** The updated at. */
    @JsonProperty("updated_at") val updatedAt: OffsetDateTime,
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"GetLicenseKeyResponseValue200ApplicationJsonPropertyData\",\"properties\":{\"id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"key\":{\"kind\":\"primitive\",\"type\":\"string\"},\"limit\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"active\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"status\":{\"kind\":\"primitive\",\"type\":\"string\"},\"expires_at\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"}},\"is_expired\":{\"kind\":\"primitive\",\"type\":\"boolean\"},\"store_id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"order_id\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"integer\"}},\"invoice_id\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"integer\"}},\"product_id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"variant_id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"customer_id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"subscription_id\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"integer\"}},\"created_at\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"},\"updated_at\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"}},\"required\":[\"id\",\"key\",\"limit\",\"active\",\"status\",\"expires_at\",\"is_expired\",\"store_id\",\"order_id\",\"invoice_id\",\"product_id\",\"variant_id\",\"customer_id\",\"subscription_id\",\"created_at\",\"updated_at\"],\"additionalProperties\":true}"
            )
    }
}
