// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode

/** GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataPropertyDiscounts model. */
data class GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataPropertyDiscounts(
    /** The coupon. */
    @JsonProperty("coupon")
    val coupon:
        GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataPropertyDiscountsPropertyCoupon?,

    /**
     * Safe historical summaries of discount, fee, and pricing modifiers. Only the documented fields
     * are returned. Coupon codes are included only when the coupon is verified as belonging to the
     * authenticated store.
     */
    @JsonProperty("modifiers")
    val modifiers:
        List<
            GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataPropertyDiscountsPropertyModifiersItem
        >,
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataPropertyDiscounts\",\"properties\":{\"coupon\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"object\",\"modelName\":\"GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataPropertyDiscountsPropertyCoupon\",\"properties\":{\"id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"code\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\"}}},\"required\":[\"id\",\"code\"],\"additionalProperties\":true}},\"modifiers\":{\"kind\":\"array\",\"items\":{\"kind\":\"object\",\"modelName\":\"GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataPropertyDiscountsPropertyModifiersItem\",\"properties\":{\"type\":{\"kind\":\"primitive\",\"type\":\"string\"},\"key\":{\"kind\":\"primitive\",\"type\":\"string\"},\"amount_cents\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"attributes\":{\"kind\":\"object\",\"modelName\":\"GetOrderSLineItemResponseValue200ApplicationJsonPropertyDataPropertyDiscountsPropertyModifiersItemPropertyAttributes\",\"properties\":{\"label\":{\"kind\":\"primitive\",\"type\":\"string\"},\"code\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"required\":[],\"additionalProperties\":false}},\"required\":[\"type\"],\"additionalProperties\":false}}},\"required\":[\"coupon\",\"modifiers\"],\"additionalProperties\":true}"
            )
    }
}
