// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode
import java.time.OffsetDateTime

/** GetOrderLineItemResponseValue200ApplicationJsonPropertyDataPropertySubscription model. */
data class GetOrderLineItemResponseValue200ApplicationJsonPropertyDataPropertySubscription(
    /** The id. */
    @JsonProperty("id") val id: Long,

    /** The provider. */
    @JsonProperty("provider") val provider: String?,

    /** The status. */
    @JsonProperty("status") val status: String?,

    /** The cancel at period end. */
    @JsonProperty("cancel_at_period_end") val cancelAtPeriodEnd: Boolean,

    /** The current period start. */
    @JsonProperty("current_period_start") val currentPeriodStart: OffsetDateTime? = null,

    /** The current period end. */
    @JsonProperty("current_period_end") val currentPeriodEnd: OffsetDateTime? = null,
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"GetOrderLineItemResponseValue200ApplicationJsonPropertyDataPropertySubscription\",\"properties\":{\"id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"provider\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"status\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"current_period_start\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"}},\"current_period_end\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"}},\"cancel_at_period_end\":{\"kind\":\"primitive\",\"type\":\"boolean\"}},\"required\":[\"id\",\"provider\",\"status\",\"cancel_at_period_end\"],\"additionalProperties\":true}"
            )
    }
}
