// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode

/** GetProductResponseValue200ApplicationJsonPropertyDataPropertyVariantsItem model. */
data class GetProductResponseValue200ApplicationJsonPropertyDataPropertyVariantsItem(
    /** The id. */
    @JsonProperty("id") val id: Long,

    /** The title. */
    @JsonProperty("title") val title: String,
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"GetProductResponseValue200ApplicationJsonPropertyDataPropertyVariantsItem\",\"properties\":{\"id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"title\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"required\":[\"id\",\"title\"],\"additionalProperties\":true}"
            )
    }
}
