// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode

/** GetRefundResponseValue200ApplicationJsonPropertyData model. */
data class GetRefundResponseValue200ApplicationJsonPropertyData(
    /** The id. */
    @JsonProperty("id") val id: Long,

    /** The source. */
    @JsonProperty("source") val source: String,

    /** The refundable. */
    @JsonProperty("refundable")
    val refundable: GetRefundResponseValue200ApplicationJsonPropertyDataPropertyRefundable,

    /** The provider. */
    @JsonProperty("provider") val provider: String,

    /** The amount cents. */
    @JsonProperty("amount_cents") val amountCents: Long,

    /** The currency. */
    @JsonProperty("currency") val currency: String,

    /** The status. */
    @JsonProperty("status") val status: String,

    /** The provider payment id. */
    @JsonProperty("provider_payment_id") val providerPaymentId: String? = null,

    /** The provider refund id. */
    @JsonProperty("provider_refund_id") val providerRefundId: String? = null,

    /** The reason. */
    @JsonProperty("reason") val reason: String? = null,
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"GetRefundResponseValue200ApplicationJsonPropertyData\",\"properties\":{\"id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"source\":{\"kind\":\"primitive\",\"type\":\"string\"},\"refundable\":{\"kind\":\"object\",\"modelName\":\"GetRefundResponseValue200ApplicationJsonPropertyDataPropertyRefundable\",\"properties\":{\"type\":{\"kind\":\"enum\",\"values\":[\"order\",\"charge\"]},\"id\":{\"kind\":\"primitive\",\"type\":\"integer\"}},\"required\":[\"type\",\"id\"],\"additionalProperties\":true},\"provider\":{\"kind\":\"primitive\",\"type\":\"string\"},\"provider_payment_id\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"provider_refund_id\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"amount_cents\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"currency\":{\"kind\":\"primitive\",\"type\":\"string\"},\"status\":{\"kind\":\"primitive\",\"type\":\"string\"},\"reason\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\"}}},\"required\":[\"id\",\"source\",\"refundable\",\"provider\",\"amount_cents\",\"currency\",\"status\"],\"additionalProperties\":true}"
            )
    }
}
