// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode

/** GetStoreSettingsResponseValue200ApplicationJsonPropertyDataPropertyStatus model. */
data class GetStoreSettingsResponseValue200ApplicationJsonPropertyDataPropertyStatus(
    /** The accessible. */
    @JsonProperty("accessible") val accessible: Boolean,

    /** The verified. */
    @JsonProperty("verified") val verified: Boolean,

    /** The locked. */
    @JsonProperty("locked") val locked: Boolean,
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"GetStoreSettingsResponseValue200ApplicationJsonPropertyDataPropertyStatus\",\"properties\":{\"accessible\":{\"kind\":\"primitive\",\"type\":\"boolean\"},\"verified\":{\"kind\":\"primitive\",\"type\":\"boolean\"},\"locked\":{\"kind\":\"primitive\",\"type\":\"boolean\"}},\"required\":[\"accessible\",\"verified\",\"locked\"],\"additionalProperties\":true}"
            )
    }
}
