// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode
import java.time.OffsetDateTime

/** GetSectionResponseValue200ApplicationJsonPropertyData model. */
data class GetSectionResponseValue200ApplicationJsonPropertyData(
    /** The id. */
    @JsonProperty("id") val id: Long,

    /** The title. */
    @JsonProperty("title") val title: String,

    /** The slug. */
    @JsonProperty("slug") val slug: String?,

    /** The hidden. */
    @JsonProperty("hidden") val hidden: Boolean,

    /** The order. */
    @JsonProperty("order") val order: Long,

    /** The created at. */
    @JsonProperty("created_at") val createdAt: OffsetDateTime,

    /** The updated at. */
    @JsonProperty("updated_at") val updatedAt: OffsetDateTime,

    /** The store id. */
    @JsonProperty("store_id") val storeId: Long,

    /** The groups linked. */
    @JsonProperty("groups_linked") val groupsLinked: Long,

    /** The products linked. */
    @JsonProperty("products_linked") val productsLinked: Long,

    /** The groups. */
    @JsonProperty("groups")
    val groups: List<GetSectionResponseValue200ApplicationJsonPropertyDataPropertyGroupsItem>,

    /** The products. */
    @JsonProperty("products")
    val products: List<GetSectionResponseValue200ApplicationJsonPropertyDataPropertyProductsItem>,
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"GetSectionResponseValue200ApplicationJsonPropertyData\",\"properties\":{\"id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"title\":{\"kind\":\"primitive\",\"type\":\"string\"},\"slug\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"hidden\":{\"kind\":\"primitive\",\"type\":\"boolean\"},\"order\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"created_at\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"},\"updated_at\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"},\"store_id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"groups_linked\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"products_linked\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"groups\":{\"kind\":\"array\",\"items\":{\"kind\":\"object\",\"modelName\":\"GetSectionResponseValue200ApplicationJsonPropertyDataPropertyGroupsItem\",\"properties\":{\"id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"title\":{\"kind\":\"primitive\",\"type\":\"string\"},\"group_products\":{\"kind\":\"primitive\",\"type\":\"integer\"}},\"required\":[\"id\",\"title\",\"group_products\"],\"additionalProperties\":true}},\"products\":{\"kind\":\"array\",\"items\":{\"kind\":\"object\",\"modelName\":\"GetSectionResponseValue200ApplicationJsonPropertyDataPropertyProductsItem\",\"properties\":{\"id\":{\"kind\":\"primitive\",\"type\":\"string\"},\"title\":{\"kind\":\"primitive\",\"type\":\"string\"},\"description\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"required\":[\"id\",\"title\",\"description\"],\"additionalProperties\":true}}},\"required\":[\"id\",\"title\",\"slug\",\"hidden\",\"order\",\"created_at\",\"updated_at\",\"store_id\",\"groups_linked\",\"products_linked\",\"groups\",\"products\"],\"additionalProperties\":true}"
            )
    }
}
