// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/** Alias for [UpdateInvoiceStatusResponseValue200ApplicationJsonPropertyStatus]. */
typealias IssueReplacementForCompletedInvoiceResponseValue200ApplicationJsonPropertyStatus =
    UpdateInvoiceStatusResponseValue200ApplicationJsonPropertyStatus
