// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import app.sell.sellapp.types.CreatePromotionRequestApplicationJsonPropertyPhasesItemDiscountType
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode
import java.time.OffsetDateTime

/** ListPromotionPhasesResponseValue200ApplicationJsonPropertyDataItem model. */
data class ListPromotionPhasesResponseValue200ApplicationJsonPropertyDataItem(
    /** The id. */
    @JsonProperty("id") val id: Long,

    /** The promotion id. */
    @JsonProperty("promotion_id") val promotionId: Long,

    /** The sort order. */
    @JsonProperty("sort_order") val sortOrder: Long,

    /** The discount type. */
    @JsonProperty("discount_type")
    val discountType: CreatePromotionRequestApplicationJsonPropertyPhasesItemDiscountType,

    /** The discount value. */
    @JsonProperty("discount_value") val discountValue: String,

    /** The ends at. */
    @JsonProperty("ends_at") val endsAt: OffsetDateTime? = null,

    /** The max redemptions. */
    @JsonProperty("max_redemptions") val maxRedemptions: Long? = null,

    /** The minimum amount. */
    @JsonProperty("minimum_amount") val minimumAmount: String? = null,

    /** The created at. */
    @JsonProperty("created_at") val createdAt: OffsetDateTime? = null,

    /** The updated at. */
    @JsonProperty("updated_at") val updatedAt: OffsetDateTime? = null,

    /** The deleted at. */
    @JsonProperty("deleted_at") val deletedAt: OffsetDateTime? = null,
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"ListPromotionPhasesResponseValue200ApplicationJsonPropertyDataItem\",\"properties\":{\"id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"promotion_id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"sort_order\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":1}},\"discount_type\":{\"kind\":\"enum\",\"values\":[\"percentage\",\"fixed\"]},\"discount_value\":{\"kind\":\"primitive\",\"type\":\"string\"},\"ends_at\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"}},\"max_redemptions\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":1}}},\"minimum_amount\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"created_at\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"}},\"updated_at\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"}},\"deleted_at\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"}}},\"required\":[\"id\",\"promotion_id\",\"sort_order\",\"discount_type\",\"discount_value\"],\"additionalProperties\":true}"
            )
    }
}
