// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/**
 * Alias for
 * [UpdateInvoiceStatusResponseValue200ApplicationJsonPropertyCustomerInformationPropertyVat].
 */
typealias ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyCustomerInformationPropertyVat =
    UpdateInvoiceStatusResponseValue200ApplicationJsonPropertyCustomerInformationPropertyVat
