// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/**
 * Alias for [GetCreditsProductResponseValue200ApplicationJsonPropertyDataPropertyVariantInvariant].
 */
typealias ListCreditsProductsResponseValue200ApplicationJsonAnyOfValue1PropertyDataItemPropertyVariantInvariant =
    GetCreditsProductResponseValue200ApplicationJsonPropertyDataPropertyVariantInvariant
