// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/** Alias for [ListCustomerEntitlementsResponseValue200ApplicationJsonPropertyDataItem]. */
typealias ListCustomerPortalEntitlementsResponseValue200ApplicationJsonPropertyDataItem =
    ListCustomerEntitlementsResponseValue200ApplicationJsonPropertyDataItem
