// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/** Alias for [GetAddOnResponseValue200ApplicationJsonPropertyData]. */
typealias ListProductSAddOnsResponseValue200ApplicationJsonAnyOfValue2PropertyDataItem =
    GetAddOnResponseValue200ApplicationJsonPropertyData
