// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/** Alias for [GetProductResponseValue200ApplicationJsonPropertyDataPropertyImagesItem]. */
typealias ListProductsResponseValue200ApplicationJsonPropertyDataItemPropertyImagesItem =
    GetProductResponseValue200ApplicationJsonPropertyDataPropertyImagesItem
