// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import app.sell.sellapp.types.SdkRecordCreditTransactionRequestApplicationJsonKind
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonInclude
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode
import java.time.OffsetDateTime

/** ListCreditBalanceTransactionsResponseValue200ApplicationJsonPropertyDataItem model. */
data class ListCreditBalanceTransactionsResponseValue200ApplicationJsonPropertyDataItem(
    /** The id. */
    @JsonProperty("id") val id: Long,

    /** The store id. */
    @JsonProperty("store_id") val storeId: Long,

    /** The customer id. */
    @JsonProperty("customer_id") val customerId: Long,

    /** The product id. */
    @JsonProperty("product_id") val productId: Long,

    /** The kind. */
    @JsonProperty("kind") val kind: SdkRecordCreditTransactionRequestApplicationJsonKind,

    /** The amount units. */
    @JsonProperty("amount_units") val amountUnits: Long,

    /** The balance after units. */
    @JsonProperty("balance_after_units") val balanceAfterUnits: Long,

    /** The idempotency key. */
    @JsonProperty("idempotency_key") val idempotencyKey: String,

    /** The source type. */
    @JsonProperty("source_type") val sourceType: String? = null,

    /** The source id. */
    @JsonProperty("source_id") val sourceId: String? = null,

    /** The reason. */
    @JsonProperty("reason") val reason: String? = null,

    /** The metadata. */
    @JsonProperty("metadata")
    @get:JsonInclude(JsonInclude.Include.NON_NULL)
    val metadata:
        ListCreditBalanceTransactionsResponseValue200ApplicationJsonPropertyDataItemPropertyMetadata? =
        null,

    /** The actor user id. */
    @JsonProperty("actor_user_id") val actorUserId: Long? = null,

    /** The created at. */
    @JsonProperty("created_at")
    @get:JsonInclude(JsonInclude.Include.NON_NULL)
    val createdAt: OffsetDateTime? = null,
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"ListCreditBalanceTransactionsResponseValue200ApplicationJsonPropertyDataItem\",\"properties\":{\"id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"store_id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"customer_id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"product_id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"kind\":{\"kind\":\"enum\",\"values\":[\"grant\",\"consumption\",\"adjustment\"]},\"amount_units\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"balance_after_units\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":0}},\"idempotency_key\":{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"maxLength\":128}},\"source_type\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"source_id\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"reason\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"metadata\":{\"kind\":\"object\",\"modelName\":\"ListCreditBalanceTransactionsResponseValue200ApplicationJsonPropertyDataItemPropertyMetadata\",\"properties\":{},\"required\":[],\"additionalProperties\":true},\"actor_user_id\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"integer\"}},\"created_at\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"}},\"required\":[\"id\",\"store_id\",\"customer_id\",\"product_id\",\"kind\",\"amount_units\",\"balance_after_units\",\"idempotency_key\"],\"additionalProperties\":true}"
            )
    }
}
