// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode

/** ListWebhookEventTypesResponseValue200ApplicationJsonPropertyDataItem model. */
data class ListWebhookEventTypesResponseValue200ApplicationJsonPropertyDataItem(
    /** The type. */
    @JsonProperty("type") val type: String,

    /** The version. */
    @JsonProperty("version") val version: Long,

    /** The description. */
    @JsonProperty("description") val description: String,
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"ListWebhookEventTypesResponseValue200ApplicationJsonPropertyDataItem\",\"properties\":{\"type\":{\"kind\":\"primitive\",\"type\":\"string\"},\"version\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"description\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"required\":[\"type\",\"version\",\"description\"],\"additionalProperties\":true}"
            )
    }
}
