// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/** Alias for [AddHighlightMediaResponseValue201ApplicationJsonPropertyData]. */
typealias ListHighlightMediaResponseValue200ApplicationJsonPropertyDataItem =
    AddHighlightMediaResponseValue201ApplicationJsonPropertyData
