// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/** Alias for [GetBundleItemResponseValue200ApplicationJsonPropertyDataPropertyOtherSettings]. */
typealias ListProductVariantsResponseValue200ApplicationJsonPropertyDataItemPropertyOtherSettings =
    GetBundleItemResponseValue200ApplicationJsonPropertyDataPropertyOtherSettings
