// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.databind.JsonNode

/**
 * ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyCustomerInformationPropertyDiscordData
 * model.
 */
class ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyCustomerInformationPropertyDiscordData {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyCustomerInformationPropertyDiscordData\",\"properties\":{},\"required\":[],\"additionalProperties\":true}"
            )
    }
}
