// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/** Alias for [GetRefundResponseValue200ApplicationJsonPropertyDataPropertyRefundable]. */
typealias ListRefundsResponseValue200ApplicationJsonPropertyDataItemPropertyRefundable =
    GetRefundResponseValue200ApplicationJsonPropertyDataPropertyRefundable
