// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode

/** ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyCustomerInformation model. */
data class ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyCustomerInformation(
    /** The id. */
    @JsonProperty("id") val id: Long,

    /** The email. */
    @JsonProperty("email") val email: String,

    /** The country. */
    @JsonProperty("country") val country: String?,

    /** The location. */
    @JsonProperty("location") val location: String,

    /** The ip. */
    @JsonProperty("ip") val ip: String,

    /** The proxied. */
    @JsonProperty("proxied") val proxied: Boolean,

    /** The browser agent. */
    @JsonProperty("browser_agent") val browserAgent: String,

    /** The vat. */
    @JsonProperty("vat")
    val vat:
        ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyCustomerInformationPropertyVat?,

    /** The discord data. */
    @JsonProperty("discord_data")
    val discordData:
        ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyCustomerInformationPropertyDiscordData,

    /** The billing details. */
    @JsonProperty("billing_details")
    val billingDetails:
        ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyCustomerInformationPropertyBillingDetails,
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyCustomerInformation\",\"properties\":{\"id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"email\":{\"kind\":\"primitive\",\"type\":\"string\"},\"country\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"location\":{\"kind\":\"primitive\",\"type\":\"string\"},\"ip\":{\"kind\":\"primitive\",\"type\":\"string\"},\"proxied\":{\"kind\":\"primitive\",\"type\":\"boolean\"},\"browser_agent\":{\"kind\":\"primitive\",\"type\":\"string\"},\"vat\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"object\",\"modelName\":\"ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyCustomerInformationPropertyVat\",\"properties\":{\"amount\":{\"kind\":\"primitive\",\"type\":\"string\"},\"country\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\"}}},\"required\":[\"amount\",\"country\"],\"additionalProperties\":true}},\"discord_data\":{\"kind\":\"object\",\"modelName\":\"ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyCustomerInformationPropertyDiscordData\",\"properties\":{},\"required\":[],\"additionalProperties\":true},\"billing_details\":{\"kind\":\"object\",\"modelName\":\"ListInvoicesResponseValue200ApplicationJsonPropertyDataItemPropertyCustomerInformationPropertyBillingDetails\",\"properties\":{},\"required\":[],\"additionalProperties\":true}},\"required\":[\"id\",\"email\",\"country\",\"location\",\"ip\",\"proxied\",\"browser_agent\",\"vat\",\"discord_data\",\"billing_details\"],\"additionalProperties\":true}"
            )
    }
}
