// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode

/** PaginationMeta model. */
data class PaginationMeta(
    /** The current page. */
    @JsonProperty("current_page") val currentPage: Long,

    /** The from. */
    @JsonProperty("from") val from: Long?,

    /** The last page. */
    @JsonProperty("last_page") val lastPage: Long,

    /** The links. */
    @JsonProperty("links") val links: List<PaginationMetaLink>,

    /** The path. */
    @JsonProperty("path") val path: String,

    /** The per page. */
    @JsonProperty("per_page") val perPage: Long,

    /** The to. */
    @JsonProperty("to") val to: Long?,

    /** The total. */
    @JsonProperty("total") val total: Long,
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"PaginationMeta\",\"properties\":{\"current_page\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"from\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"integer\"}},\"last_page\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"links\":{\"kind\":\"array\",\"items\":{\"kind\":\"object\",\"modelName\":\"PaginationMetaLink\",\"properties\":{\"url\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"label\":{\"kind\":\"primitive\",\"type\":\"string\"},\"active\":{\"kind\":\"primitive\",\"type\":\"boolean\"}},\"required\":[\"url\",\"label\",\"active\"],\"additionalProperties\":true}},\"path\":{\"kind\":\"primitive\",\"type\":\"string\"},\"per_page\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"to\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"integer\"}},\"total\":{\"kind\":\"primitive\",\"type\":\"integer\"}},\"required\":[\"current_page\",\"from\",\"last_page\",\"links\",\"path\",\"per_page\",\"to\",\"total\"],\"additionalProperties\":true}"
            )
    }
}
