// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode

/**
 * PollCommunityConnectionResponseValue200ApplicationJsonPropertyDataPropertyAvailableServersItem
 * model.
 */
data class PollCommunityConnectionResponseValue200ApplicationJsonPropertyDataPropertyAvailableServersItem(
    /** The id. */
    @JsonProperty("id") val id: String,

    /** The name. */
    @JsonProperty("name") val name: String,

    /** Always `"group"`. */
    @JsonProperty("type") val type: String = "group",
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"PollCommunityConnectionResponseValue200ApplicationJsonPropertyDataPropertyAvailableServersItem\",\"properties\":{\"id\":{\"kind\":\"primitive\",\"type\":\"string\"},\"name\":{\"kind\":\"primitive\",\"type\":\"string\"},\"type\":{\"kind\":\"literal\",\"value\":\"group\"}},\"required\":[\"id\",\"name\",\"type\"],\"additionalProperties\":true}"
            )
    }
}
