// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/**
 * Alias for
 * [CreateCourseLessonResponseValue201ApplicationJsonPropertyDataPropertyQuestionsItemPropertyAnswersItem].
 */
typealias ReorderCourseSectionsResponseValue200ApplicationJsonPropertyDataPropertySectionsItemPropertyLessonsItemPropertyAssignmentValuePropertyQuestionsItemPropertyAnswersItem =
    CreateCourseLessonResponseValue201ApplicationJsonPropertyDataPropertyQuestionsItemPropertyAnswersItem
