// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/** Alias for [GetCourseResponseValue200ApplicationJsonPropertyDataPropertyPromoVideo]. */
typealias ReorderCourseLessonsResponseValue200ApplicationJsonPropertyDataPropertyPromoVideo =
    GetCourseResponseValue200ApplicationJsonPropertyDataPropertyPromoVideo
