// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/** Alias for [GetVariantDeliverableFileResponseValue200ApplicationJsonPropertyData]. */
typealias ReplaceVariantDeliverableFileSettingsResponseValue200ApplicationJsonPropertyData =
    GetVariantDeliverableFileResponseValue200ApplicationJsonPropertyData
