// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/**
 * Alias for
 * [GetAffiliateProgramConfigurationResponseValue200ApplicationJsonPropertyDataPropertySettings].
 */
typealias ReplaceAffiliateProgramConfigurationResponseValue200ApplicationJsonPropertyDataPropertySettings =
    GetAffiliateProgramConfigurationResponseValue200ApplicationJsonPropertyDataPropertySettings
