// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/** Alias for [GetUpsellOfferResponseValue200ApplicationJsonPropertyDataPropertyItemsItem]. */
typealias ReplaceUpsellOfferResponseValue200ApplicationJsonPropertyDataPropertyItemsItem =
    GetUpsellOfferResponseValue200ApplicationJsonPropertyDataPropertyItemsItem
