// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import app.sell.sellapp.types.CreatePromotionRequestApplicationJsonPropertyPhasesItemDiscountType
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode

/**
 * ReplaceAffiliateProgramConfigurationRequestApplicationJsonPropertySettingsPropertyCommission
 * model.
 */
data class ReplaceAffiliateProgramConfigurationRequestApplicationJsonPropertySettingsPropertyCommission(
    /** The type. */
    @JsonProperty("type")
    val type: CreatePromotionRequestApplicationJsonPropertyPhasesItemDiscountType,

    /**
     * Decimal commission value. Percentage commissions must be from 0.01 through 100; fixed
     * commissions are USD major units.
     */
    @JsonProperty("amount") val amount: String,
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"ReplaceAffiliateProgramConfigurationRequestApplicationJsonPropertySettingsPropertyCommission\",\"properties\":{\"type\":{\"kind\":\"enum\",\"values\":[\"percentage\",\"fixed\"]},\"amount\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"required\":[\"type\",\"amount\"],\"additionalProperties\":true}"
            )
    }
}
