// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/** Alias for [CreateCashbackRuleResponseValue201ApplicationJsonPropertyData]. */
typealias RestoreCashbackRuleResponseValue200ApplicationJsonPropertyData =
    CreateCashbackRuleResponseValue201ApplicationJsonPropertyData
