// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/** Alias for [GetPromotionResponseValue200ApplicationJsonPropertyData]. */
typealias RestorePromotionResponseValue200ApplicationJsonPropertyData =
    GetPromotionResponseValue200ApplicationJsonPropertyData
