// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode

/** RetryOrderFulfillmentResponseValue200ApplicationJsonPropertyMeta model. */
data class RetryOrderFulfillmentResponseValue200ApplicationJsonPropertyMeta(
    /** The effects reset. */
    @JsonProperty("effects_reset") val effectsReset: Long
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"RetryOrderFulfillmentResponseValue200ApplicationJsonPropertyMeta\",\"properties\":{\"effects_reset\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":0}}},\"required\":[\"effects_reset\"],\"additionalProperties\":true}"
            )
    }
}
