// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/** Alias for [SdkAttachBundleItemsResponseValue200ApplicationJson]. */
typealias SdkAddProductsToGroupResponseValue200ApplicationJson =
    SdkAttachBundleItemsResponseValue200ApplicationJson
