// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonInclude
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode

/** SdkAddHighlightMediaRequestMultipartFormData model. */
data class SdkAddHighlightMediaRequestMultipartFormData(
    /** The file. */
    @JsonProperty("file") val file: ByteArray,

    /** The cta title. */
    @JsonProperty("cta_title")
    @get:JsonInclude(JsonInclude.Include.NON_NULL)
    val ctaTitle: String? = null,

    /** The product id. */
    @JsonProperty("product_id") val productId: Long? = null,
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"SdkAddHighlightMediaRequestMultipartFormData\",\"properties\":{\"file\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"binary\"},\"cta_title\":{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"maxLength\":510}},\"product_id\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":1}}}},\"required\":[\"file\"],\"additionalProperties\":true}"
            )
    }
}
