// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode

/** SdkDeactivateLicenseRequestApplicationJson model. */
data class SdkDeactivateLicenseRequestApplicationJson(
    /** The license key. */
    @JsonProperty("license_key") val licenseKey: String,

    /** The instance id. */
    @JsonProperty("instance_id") val instanceId: String,
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"SdkDeactivateLicenseRequestApplicationJson\",\"properties\":{\"license_key\":{\"kind\":\"primitive\",\"type\":\"string\"},\"instance_id\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"required\":[\"license_key\",\"instance_id\"],\"additionalProperties\":true}"
            )
    }
}
