// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode

/** SdkDenyOAuthAuthorizationRequestApplicationXWwwFormUrlencoded model. */
data class SdkDenyOAuthAuthorizationRequestApplicationXWwwFormUrlencoded(
    /** The auth token. */
    @JsonProperty("auth_token") val authToken: String,

    /** The token. */
    @JsonProperty("_token") val token: String,
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"SdkDenyOAuthAuthorizationRequestApplicationXWwwFormUrlencoded\",\"properties\":{\"auth_token\":{\"kind\":\"primitive\",\"type\":\"string\"},\"_token\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"required\":[\"auth_token\",\"_token\"],\"additionalProperties\":true}"
            )
    }
}
