// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode

/** SdkEnableOrDisablePaymentMethodRequestApplicationJson model. */
data class SdkEnableOrDisablePaymentMethodRequestApplicationJson(
    /** The enabled. */
    @JsonProperty("enabled") val enabled: Boolean
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"SdkEnableOrDisablePaymentMethodRequestApplicationJson\",\"properties\":{\"enabled\":{\"kind\":\"primitive\",\"type\":\"boolean\"}},\"required\":[\"enabled\"],\"additionalProperties\":true}"
            )
    }
}
