// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode

/** SdkGetNotificationChannelResponseValue200ApplicationJson model. */
data class SdkGetNotificationChannelResponseValue200ApplicationJson(
    /** The data. */
    @JsonProperty("data")
    val data: GetNotificationChannelResponseValue200ApplicationJsonPropertyData
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"SdkGetNotificationChannelResponseValue200ApplicationJson\",\"properties\":{\"data\":{\"kind\":\"object\",\"modelName\":\"GetNotificationChannelResponseValue200ApplicationJsonPropertyData\",\"properties\":{\"id\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"uuid\"},\"type\":{\"kind\":\"enum\",\"values\":[\"email\",\"discord\"]},\"email\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"email\"}},\"channel\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"webhook_configured\":{\"kind\":\"primitive\",\"type\":\"boolean\"},\"allowed_notifications\":{\"kind\":\"array\",\"items\":{\"kind\":\"primitive\",\"type\":\"string\"}}},\"required\":[\"id\",\"type\",\"webhook_configured\",\"allowed_notifications\"],\"additionalProperties\":true}},\"required\":[\"data\"],\"additionalProperties\":true}"
            )
    }
}
