// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/** Alias for [SdkReplyToTicketResponseValue201ApplicationJson]. */
typealias SdkGetTicketMessageResponseValue200ApplicationJson =
    SdkReplyToTicketResponseValue201ApplicationJson
