// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode

/** SdkGetRefundResponseValue200ApplicationJson model. */
data class SdkGetRefundResponseValue200ApplicationJson(
    /** The data. */
    @JsonProperty("data") val data: GetRefundResponseValue200ApplicationJsonPropertyData
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"SdkGetRefundResponseValue200ApplicationJson\",\"properties\":{\"data\":{\"kind\":\"object\",\"modelName\":\"GetRefundResponseValue200ApplicationJsonPropertyData\",\"properties\":{\"id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"source\":{\"kind\":\"primitive\",\"type\":\"string\"},\"refundable\":{\"kind\":\"object\",\"modelName\":\"GetRefundResponseValue200ApplicationJsonPropertyDataPropertyRefundable\",\"properties\":{\"type\":{\"kind\":\"enum\",\"values\":[\"order\",\"charge\"]},\"id\":{\"kind\":\"primitive\",\"type\":\"integer\"}},\"required\":[\"type\",\"id\"],\"additionalProperties\":true},\"provider\":{\"kind\":\"primitive\",\"type\":\"string\"},\"provider_payment_id\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"provider_refund_id\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"amount_cents\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"currency\":{\"kind\":\"primitive\",\"type\":\"string\"},\"status\":{\"kind\":\"primitive\",\"type\":\"string\"},\"reason\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\"}}},\"required\":[\"id\",\"source\",\"refundable\",\"provider\",\"amount_cents\",\"currency\",\"status\"],\"additionalProperties\":true}},\"required\":[\"data\"],\"additionalProperties\":true}"
            )
    }
}
