// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode

/** SdkGetOAuthAuthorizationServerMetadataResponseValue200ApplicationJson model. */
data class SdkGetOAuthAuthorizationServerMetadataResponseValue200ApplicationJson(
    /** The issuer. */
    @JsonProperty("issuer") val issuer: String,

    /** The authorization endpoint. */
    @JsonProperty("authorization_endpoint") val authorizationEndpoint: String,

    /** The token endpoint. */
    @JsonProperty("token_endpoint") val tokenEndpoint: String,

    /** The revocation endpoint. */
    @JsonProperty("revocation_endpoint") val revocationEndpoint: String,

    /** The response types supported. */
    @JsonProperty("response_types_supported") val responseTypesSupported: List<String>,

    /** The grant types supported. */
    @JsonProperty("grant_types_supported") val grantTypesSupported: List<String>,

    /** The code challenge methods supported. */
    @JsonProperty("code_challenge_methods_supported")
    val codeChallengeMethodsSupported: List<String>,

    /** The token endpoint auth methods supported. */
    @JsonProperty("token_endpoint_auth_methods_supported")
    val tokenEndpointAuthMethodsSupported: List<String>,

    /** The revocation endpoint auth methods supported. */
    @JsonProperty("revocation_endpoint_auth_methods_supported")
    val revocationEndpointAuthMethodsSupported: List<String>,

    /** The scopes supported. */
    @JsonProperty("scopes_supported") val scopesSupported: List<String>,
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"SdkGetOAuthAuthorizationServerMetadataResponseValue200ApplicationJson\",\"properties\":{\"issuer\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"uri\"},\"authorization_endpoint\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"uri\"},\"token_endpoint\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"uri\"},\"revocation_endpoint\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"uri\"},\"response_types_supported\":{\"kind\":\"array\",\"items\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"grant_types_supported\":{\"kind\":\"array\",\"items\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"code_challenge_methods_supported\":{\"kind\":\"array\",\"items\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"token_endpoint_auth_methods_supported\":{\"kind\":\"array\",\"items\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"revocation_endpoint_auth_methods_supported\":{\"kind\":\"array\",\"items\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"scopes_supported\":{\"kind\":\"array\",\"items\":{\"kind\":\"primitive\",\"type\":\"string\"}}},\"required\":[\"issuer\",\"authorization_endpoint\",\"token_endpoint\",\"revocation_endpoint\",\"response_types_supported\",\"grant_types_supported\",\"code_challenge_methods_supported\",\"token_endpoint_auth_methods_supported\",\"revocation_endpoint_auth_methods_supported\",\"scopes_supported\"],\"additionalProperties\":true}"
            )
    }
}
