// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode

/** SdkGetAffiliatePayoutResponseValue200ApplicationJson model. */
data class SdkGetAffiliatePayoutResponseValue200ApplicationJson(
    /** The data. */
    @JsonProperty("data") val data: GetAffiliatePayoutResponseValue200ApplicationJsonPropertyData
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"SdkGetAffiliatePayoutResponseValue200ApplicationJson\",\"properties\":{\"data\":{\"kind\":\"object\",\"modelName\":\"GetAffiliatePayoutResponseValue200ApplicationJsonPropertyData\",\"properties\":{\"id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"affiliate_id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"affiliate_email\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"email\"},\"amount_usd_cents\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":0}},\"status\":{\"kind\":\"enum\",\"values\":[\"due\",\"paid\",\"cancelled\"]},\"payout_method\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"payout_account\":{\"kind\":\"primitive\",\"type\":\"string\"},\"referrals_count\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":0}},\"created_at\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"},\"updated_at\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"}},\"required\":[\"id\",\"affiliate_id\",\"amount_usd_cents\",\"status\",\"payout_account\",\"referrals_count\"],\"additionalProperties\":true}},\"required\":[\"data\"],\"additionalProperties\":true}"
            )
    }
}
