// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode

/** SdkListWalletBonusTiersResponseValue200ApplicationJson model. */
data class SdkListWalletBonusTiersResponseValue200ApplicationJson(
    /** The data. */
    @JsonProperty("data")
    val data: List<ListWalletBonusTiersResponseValue200ApplicationJsonPropertyDataItem>
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"SdkListWalletBonusTiersResponseValue200ApplicationJson\",\"properties\":{\"data\":{\"kind\":\"array\",\"items\":{\"kind\":\"object\",\"modelName\":\"ListWalletBonusTiersResponseValue200ApplicationJsonPropertyDataItem\",\"properties\":{\"id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"minimum_top_up_cents\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":1,\"maximum\":999999999999}},\"bonus_kind\":{\"kind\":\"enum\",\"values\":[\"fixed\",\"percent\"]},\"fixed_bonus_cents\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":1,\"maximum\":999999999999}}},\"percent_basis\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":1,\"maximum\":10000}}},\"maximum_bonus_cents\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":1,\"maximum\":999999999999}}},\"priority\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":0,\"maximum\":65535}},\"is_active\":{\"kind\":\"primitive\",\"type\":\"boolean\"},\"superseded_by_id\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"integer\"}},\"restorable\":{\"kind\":\"primitive\",\"type\":\"boolean\"},\"created_at\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"}},\"updated_at\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"}},\"deleted_at\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"}}},\"required\":[\"id\",\"minimum_top_up_cents\",\"bonus_kind\",\"fixed_bonus_cents\",\"percent_basis\",\"maximum_bonus_cents\",\"priority\",\"is_active\",\"superseded_by_id\",\"restorable\"],\"additionalProperties\":true}}},\"required\":[\"data\"],\"additionalProperties\":true}"
            )
    }
}
