// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode

/** SdkPauseSubscriptionResponseValue200ApplicationJson model. */
data class SdkPauseSubscriptionResponseValue200ApplicationJson(
    /** The data. */
    @JsonProperty("data") val data: PauseSubscriptionResponseValue200ApplicationJsonPropertyData,

    /** The message. */
    @JsonProperty("message") val message: String,
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"SdkPauseSubscriptionResponseValue200ApplicationJson\",\"properties\":{\"data\":{\"kind\":\"object\",\"modelName\":\"PauseSubscriptionResponseValue200ApplicationJsonPropertyData\",\"properties\":{\"id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"product_subscription_id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"subscription_id\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"action\":{\"kind\":\"enum\",\"values\":[\"pause\",\"resume\",\"cancel_at_period_end\",\"cancel_immediately\",\"update_payment_method\",\"change_plan\",\"shift_billing_date\"]},\"status\":{\"kind\":\"enum\",\"values\":[\"pending\",\"confirmed\",\"failed\",\"expired\",\"dismissed\",\"force_resolved\"]},\"provider\":{\"kind\":\"primitive\",\"type\":\"string\"},\"customer_message\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"confirmed_at\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"}},\"failed_at\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"}},\"created_at\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"},\"updated_at\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"}},\"required\":[],\"additionalProperties\":true},\"message\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"required\":[\"data\",\"message\"],\"additionalProperties\":true}"
            )
    }
}
