// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonInclude
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode

/** SdkPauseCustomerSubscriptionRequestApplicationJson model. */
data class SdkPauseCustomerSubscriptionRequestApplicationJson(
    /** The preview id. */
    @JsonProperty("preview_id")
    @get:JsonInclude(JsonInclude.Include.NON_NULL)
    val previewId: String? = null,

    /** The product variant id. */
    @JsonProperty("product_variant_id")
    @get:JsonInclude(JsonInclude.Include.NON_NULL)
    val productVariantId: Long? = null,

    /** The renewal date. */
    @JsonProperty("renewal_date")
    @get:JsonInclude(JsonInclude.Include.NON_NULL)
    val renewalDate: String? = null,

    /** The return url. */
    @JsonProperty("return_url")
    @get:JsonInclude(JsonInclude.Include.NON_NULL)
    val returnUrl: String? = null,

    /** The reason. */
    @JsonProperty("reason")
    @get:JsonInclude(JsonInclude.Include.NON_NULL)
    val reason: String? = null,
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"SdkPauseCustomerSubscriptionRequestApplicationJson\",\"properties\":{\"preview_id\":{\"kind\":\"primitive\",\"type\":\"string\"},\"product_variant_id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"renewal_date\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date\"},\"return_url\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"uri\"},\"reason\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"required\":[],\"additionalProperties\":true}"
            )
    }
}
