// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode

/** SdkQueueVariantSerialImportResponseValue202ApplicationJson model. */
data class SdkQueueVariantSerialImportResponseValue202ApplicationJson(
    /** The data. */
    @JsonProperty("data")
    val data: QueueVariantSerialImportResponseValue202ApplicationJsonPropertyData
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"SdkQueueVariantSerialImportResponseValue202ApplicationJson\",\"properties\":{\"data\":{\"kind\":\"object\",\"modelName\":\"QueueVariantSerialImportResponseValue202ApplicationJsonPropertyData\",\"properties\":{\"status\":{\"kind\":\"literal\",\"value\":\"queued\"},\"tracker_id\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"required\":[\"status\",\"tracker_id\"],\"additionalProperties\":true}},\"required\":[\"data\"],\"additionalProperties\":true}"
            )
    }
}
