// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode

/** SdkReplaceWalletSettingsRequestApplicationJson model. */
data class SdkReplaceWalletSettingsRequestApplicationJson(
    /** The enabled. */
    @JsonProperty("enabled") val enabled: Boolean,

    /** The minimum top up cents. */
    @JsonProperty("minimum_top_up_cents") val minimumTopUpCents: Long?,

    /** The maximum top up cents. */
    @JsonProperty("maximum_top_up_cents") val maximumTopUpCents: Long?,

    /** The expiration days. */
    @JsonProperty("expiration_days") val expirationDays: Long?,

    /**
     * Effective top-up gateway groups. CUSTOM_PAYMENT_METHOD enables all usable custom methods;
     * customers choose an individual method in the portal. With no saved restriction, every
     * currently configurable group is returned, including custom methods. An empty array disables
     * all methods. Custom top-ups charge and credit the exact USD deposit amount, plus any wallet
     * bonus, without custom-method discounts or fees.
     */
    @JsonProperty("payment_methods") val paymentMethods: List<String>,
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"SdkReplaceWalletSettingsRequestApplicationJson\",\"properties\":{\"enabled\":{\"kind\":\"primitive\",\"type\":\"boolean\"},\"minimum_top_up_cents\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":1,\"maximum\":999999999999}}},\"maximum_top_up_cents\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":1,\"maximum\":999999999999}}},\"expiration_days\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":1,\"maximum\":3650}}},\"payment_methods\":{\"kind\":\"array\",\"items\":{\"kind\":\"primitive\",\"type\":\"string\"}}},\"required\":[\"enabled\",\"minimum_top_up_cents\",\"maximum_top_up_cents\",\"expiration_days\",\"payment_methods\"],\"additionalProperties\":true}"
            )
    }
}
