// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode

/** SdkReplyToTicketRequestApplicationJson model. */
data class SdkReplyToTicketRequestApplicationJson(
    /** The content. */
    @JsonProperty("content") val content: String
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"SdkReplyToTicketRequestApplicationJson\",\"properties\":{\"content\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"required\":[\"content\"],\"additionalProperties\":true}"
            )
    }
}
