// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import app.sell.sellapp.types.CreateProductVariantRequestApplicationJsonPropertyDeliverableTypes
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonInclude
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode
import java.time.OffsetDateTime

/** SdkReplaceVariantDeliverableConfigurationRequestApplicationJson model. */
data class SdkReplaceVariantDeliverableConfigurationRequestApplicationJson(
    /**
     * The complete type list. TEXT, BOOKING, CREDITS, and BUNDLE are owned by their dedicated
     * resources and must remain unchanged here.
     */
    @JsonProperty("types")
    val types: List<CreateProductVariantRequestApplicationJsonPropertyDeliverableTypes>,

    /** The data. */
    @JsonProperty("data")
    val data: ReplaceVariantDeliverableConfigurationRequestApplicationJsonPropertyData,

    /**
     * Optional optimistic-concurrency snapshot from the deliverable resource's updated_at field.
     * The request returns 422 if the variant changed after this timestamp was loaded.
     */
    @JsonProperty("expected_updated_at")
    @get:JsonInclude(JsonInclude.Include.NON_NULL)
    val expectedUpdatedAt: OffsetDateTime? = null,
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"SdkReplaceVariantDeliverableConfigurationRequestApplicationJson\",\"properties\":{\"types\":{\"kind\":\"array\",\"items\":{\"kind\":\"enum\",\"values\":[\"DOWNLOADABLE\",\"TEXT\",\"DYNAMIC\",\"MANUAL\",\"LICENSE_KEY\",\"BUNDLE\",\"BOOKING\",\"CREDITS\"]},\"constraints\":{\"minItems\":1,\"uniqueItems\":true}},\"expected_updated_at\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"},\"data\":{\"kind\":\"object\",\"modelName\":\"ReplaceVariantDeliverableConfigurationRequestApplicationJsonPropertyData\",\"properties\":{\"comment\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"maxLength\":10000}}},\"webhook\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"uri\",\"constraints\":{\"pattern\":\"^https://\"}}},\"licenseLength\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":1}}},\"licenseLengthUnit\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"enum\",\"values\":[\"day\",\"month\",\"year\",\"DAY\",\"MONTH\",\"YEAR\",\"null\"]}},\"isLicenseLengthUnlimited\":{\"kind\":\"primitive\",\"type\":\"boolean\"},\"licenseLimit\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":1}}},\"isLicenseLimitUnlimited\":{\"kind\":\"primitive\",\"type\":\"boolean\"},\"licensePrefix\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"maxLength\":50,\"pattern\":\"^[A-Za-z0-9_-]+\$\"}}}},\"required\":[],\"additionalProperties\":false}},\"required\":[\"types\",\"data\"],\"additionalProperties\":false}"
            )
    }
}
