// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import app.sell.sellapp.types.DarkMode
import app.sell.sellapp.types.StoreVisibility
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode

/** SdkReplaceGeneralStoreSettingsRequestApplicationJson model. */
data class SdkReplaceGeneralStoreSettingsRequestApplicationJson(
    /** The name. */
    @JsonProperty("name") val name: String,

    /** The visibility. */
    @JsonProperty("visibility") val visibility: StoreVisibility,

    /** The timezone. */
    @JsonProperty("timezone") val timezone: String,

    /** The currency. */
    @JsonProperty("currency") val currency: String,

    /** The dark mode. */
    @JsonProperty("dark_mode") val darkMode: DarkMode? = null,
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"SdkReplaceGeneralStoreSettingsRequestApplicationJson\",\"properties\":{\"name\":{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"maxLength\":48}},\"visibility\":{\"kind\":\"enum\",\"values\":[\"PUBLIC\",\"HIDDEN\",\"PRIVATE\"]},\"timezone\":{\"kind\":\"primitive\",\"type\":\"string\"},\"currency\":{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"minLength\":3,\"maxLength\":3}},\"dark_mode\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"enum\",\"values\":[\"light\",\"dark\",\"system\",\"null\"]}}},\"required\":[\"name\",\"visibility\",\"timezone\",\"currency\"],\"additionalProperties\":true}"
            )
    }
}
