// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/** Alias for [SdkUpdateUpsellOfferRequestApplicationJson]. */
typealias SdkReplaceUpsellOfferRequestApplicationJson = SdkUpdateUpsellOfferRequestApplicationJson
