// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode

/** SdkSetBookingDateAvailabilityRequestApplicationJson model. */
data class SdkSetBookingDateAvailabilityRequestApplicationJson(
    /** The dates. */
    @JsonProperty("dates") val dates: List<String>,

    /**
     * Set false to block the dates and true to clear the exact block or open an inherited block for
     * the variant.
     */
    @JsonProperty("available") val available: Boolean,

    /** The product variant id. */
    @JsonProperty("product_variant_id") val productVariantId: Long? = null,
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"SdkSetBookingDateAvailabilityRequestApplicationJson\",\"properties\":{\"product_variant_id\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"integer\",\"constraints\":{\"minimum\":1}}},\"dates\":{\"kind\":\"array\",\"items\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date\"},\"constraints\":{\"minItems\":1,\"maxItems\":366,\"uniqueItems\":true}},\"available\":{\"kind\":\"primitive\",\"type\":\"boolean\"}},\"required\":[\"dates\",\"available\"],\"additionalProperties\":true}"
            )
    }
}
