// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/** Alias for [SdkCreateWalletBonusTierResponseValue201ApplicationJson]. */
typealias SdkUpdateWalletBonusTierResponseValue200ApplicationJson =
    SdkCreateWalletBonusTierResponseValue201ApplicationJson
