// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonInclude
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode
import java.time.OffsetDateTime

/** SdkUpdateCourseSectionRequestApplicationJson model. */
data class SdkUpdateCourseSectionRequestApplicationJson(
    /** The title. */
    @JsonProperty("title") @get:JsonInclude(JsonInclude.Include.NON_NULL) val title: String? = null,

    /** The description. */
    @JsonProperty("description") val description: String? = null,

    /** The expected updated at. */
    @JsonProperty("expected_updated_at")
    @get:JsonInclude(JsonInclude.Include.NON_NULL)
    val expectedUpdatedAt: OffsetDateTime? = null,
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"SdkUpdateCourseSectionRequestApplicationJson\",\"properties\":{\"title\":{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"maxLength\":255}},\"description\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\",\"constraints\":{\"maxLength\":65535}}},\"expected_updated_at\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"}},\"required\":[],\"additionalProperties\":true}"
            )
    }
}
