// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode

/** SdkV2SearchTicketMessagesResponseValue200ApplicationJson model. */
data class SdkV2SearchTicketMessagesResponseValue200ApplicationJson(
    /** The data. */
    @JsonProperty("data")
    val data: List<V2SearchTicketMessagesResponseValue200ApplicationJsonPropertyDataItem>,

    /** The links. */
    @JsonProperty("links")
    val links: V2SearchTicketMessagesResponseValue200ApplicationJsonPropertyLinks,

    /** The meta. */
    @JsonProperty("meta")
    val meta: V2SearchTicketMessagesResponseValue200ApplicationJsonPropertyMeta,
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"SdkV2SearchTicketMessagesResponseValue200ApplicationJson\",\"properties\":{\"data\":{\"kind\":\"array\",\"items\":{\"kind\":\"object\",\"modelName\":\"V2SearchTicketMessagesResponseValue200ApplicationJsonPropertyDataItem\",\"properties\":{\"id\":{\"kind\":\"primitive\",\"type\":\"integer\"},\"author\":{\"kind\":\"primitive\",\"type\":\"string\"},\"sender\":{\"kind\":\"nullable\",\"inner\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"content\":{\"kind\":\"primitive\",\"type\":\"string\"},\"created_at\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"},\"updated_at\":{\"kind\":\"primitive\",\"type\":\"string\",\"format\":\"date-time\"},\"ticket_id\":{\"kind\":\"primitive\",\"type\":\"integer\"}},\"required\":[\"id\",\"author\",\"sender\",\"content\",\"created_at\",\"updated_at\",\"ticket_id\"],\"additionalProperties\":true}},\"links\":{\"kind\":\"object\",\"modelName\":\"V2SearchTicketMessagesResponseValue200ApplicationJsonPropertyLinks\",\"properties\":{},\"required\":[],\"additionalProperties\":true},\"meta\":{\"kind\":\"object\",\"modelName\":\"V2SearchTicketMessagesResponseValue200ApplicationJsonPropertyMeta\",\"properties\":{},\"required\":[],\"additionalProperties\":true}},\"required\":[\"data\",\"links\",\"meta\"],\"additionalProperties\":true}"
            )
    }
}
