// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/** Alias for [SdkGetCouponResponseValue200ApplicationJson]. */
typealias SdkV2DeleteCouponResponseValue200ApplicationJson =
    SdkGetCouponResponseValue200ApplicationJson
