// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/** Alias for [SearchAddOnsRequestApplicationJsonPropertyIncludesItem]. */
typealias SearchTicketsRequestApplicationJsonPropertyIncludesItem =
    SearchAddOnsRequestApplicationJsonPropertyIncludesItem
