// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/** Alias for [GetOrderResponseValue200ApplicationJsonPropertyDataPropertyLineItemsItem]. */
typealias SendOrderFulfillmentNotificationsResponseValue200ApplicationJsonPropertyDataPropertyLineItemsItem =
    GetOrderResponseValue200ApplicationJsonPropertyDataPropertyLineItemsItem
