// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/** Alias for [GetGroupResponseValue200ApplicationJsonPropertyDataPropertyImage]. */
typealias UpdateGroupResponseValue200ApplicationJsonPropertyDataPropertyImage =
    GetGroupResponseValue200ApplicationJsonPropertyDataPropertyImage
