// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/** Alias for [GetAffiliateResponseValue200ApplicationJsonPropertyDataPropertyBalances]. */
typealias UpdateAffiliateStatusResponseValue200ApplicationJsonPropertyDataPropertyBalances =
    GetAffiliateResponseValue200ApplicationJsonPropertyDataPropertyBalances
