// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/** Alias for [GetAffiliateResponseValue200ApplicationJsonPropertyData]. */
typealias UpdateAffiliateStatusResponseValue200ApplicationJsonPropertyData =
    GetAffiliateResponseValue200ApplicationJsonPropertyData
