// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/** Alias for [GetCustomerResponseValue200ApplicationJsonPropertyDataPropertyWallet]. */
typealias UpdateCustomerResponseValue200ApplicationJsonPropertyDataPropertyWallet =
    GetCustomerResponseValue200ApplicationJsonPropertyDataPropertyWallet
