// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/**
 * Alias for [CreateCourseLessonResponseValue201ApplicationJsonPropertyDataPropertyQuestionsItem].
 */
typealias UpdateCourseLessonResponseValue200ApplicationJsonPropertyDataPropertyQuestionsItem =
    CreateCourseLessonResponseValue201ApplicationJsonPropertyDataPropertyQuestionsItem
