// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/**
 * Alias for
 * [GetProductResponseValue200ApplicationJsonPropertyDataPropertyAdditionalInformationItem].
 */
typealias UpdateProductResponseValue200ApplicationJsonPropertyDataPropertyAdditionalInformationItem =
    GetProductResponseValue200ApplicationJsonPropertyDataPropertyAdditionalInformationItem
