// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/** Alias for [GetProductResponseValue200ApplicationJsonPropertyDataPropertyVariantsItem]. */
typealias UpdateProductResponseValue200ApplicationJsonPropertyDataPropertyVariantsItem =
    GetProductResponseValue200ApplicationJsonPropertyDataPropertyVariantsItem
