// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/** Alias for [ReplyToTicketResponseValue201ApplicationJsonPropertyData]. */
typealias V2ListTicketMessagesResponseValue200ApplicationJsonPropertyDataItem =
    ReplyToTicketResponseValue201ApplicationJsonPropertyData
