// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/** Alias for [GetSectionResponseValue200ApplicationJsonPropertyData]. */
typealias V2ReplaceSectionGroupsResponseValue200ApplicationJsonPropertyData =
    GetSectionResponseValue200ApplicationJsonPropertyData
