// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

/** Alias for [V2GetTicketResponseValue200ApplicationJsonPropertyDataPropertyReadStatus]. */
typealias V2SearchTicketsResponseValue200ApplicationJsonPropertyDataItemPropertyReadStatus =
    V2GetTicketResponseValue200ApplicationJsonPropertyDataPropertyReadStatus
