// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.runtimeSchema
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.JsonNode

/** ValidateAndSavePaymentMethodConfigurationRequestApplicationJsonOneOfValue2 model. */
data class ValidateAndSavePaymentMethodConfigurationRequestApplicationJsonOneOfValue2(
    /** Write-only secret. SellApp never returns the stored value. */
    @JsonProperty("public_key") val publicKey: String,

    /** Write-only secret. SellApp never returns the stored value. */
    @JsonProperty("access_token") val accessToken: String,

    /** Write-only secret. SellApp never returns the stored value. */
    @JsonProperty("webhook_secret") val webhookSecret: String,
) {
    /** Additive response fields retained verbatim for forward compatibility. */
    @get:JsonAnyGetter val additionalProperties: MutableMap<String, JsonNode> = linkedMapOf()

    @JsonAnySetter
    fun setAdditionalProperty(name: String, value: JsonNode) {
        additionalProperties[name] = value
    }

    companion object {
        internal val runtimeSchema =
            runtimeSchema(
                "{\"kind\":\"object\",\"modelName\":\"ValidateAndSavePaymentMethodConfigurationRequestApplicationJsonOneOfValue2\",\"properties\":{\"public_key\":{\"kind\":\"primitive\",\"type\":\"string\"},\"access_token\":{\"kind\":\"primitive\",\"type\":\"string\"},\"webhook_secret\":{\"kind\":\"primitive\",\"type\":\"string\"}},\"required\":[\"public_key\",\"access_token\",\"webhook_secret\"],\"additionalProperties\":true}"
            )
    }
}
