// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.wallettopups

import app.sell.sellapp.SellApp
import app.sell.sellapp.common.http.RawResponse
import app.sell.sellapp.common.http.RequestConfig
import app.sell.sellapp.common.http.RequestOptions
import app.sell.sellapp.common.http.bodyOf
import app.sell.sellapp.common.http.encodePathSegment
import app.sell.sellapp.common.json.runtimeSchema
import app.sell.sellapp.models.SdkCreateWalletTopUpResponseValue201ApplicationJson
import app.sell.sellapp.types.PaymentMethod

/**
 * API accessor for WalletTopups.
 *
 * Every operation on this class is available in two flavors: a blocking variant (`<methodName>`)
 * and a coroutine-aware variant (`<methodName>Suspend`). The `Suspend` variants delegate to the
 * blocking ones under `withContext(Dispatchers.IO)`, so they are safe to call from any coroutine
 * dispatcher (including `Dispatchers.Main`).
 */
class WalletTopups(internal val sellapp: SellApp) {
    /**
     * Create a wallet top-up payment link
     *
     * Create a paid USD top-up for an existing customer and return data.checkout_url for the
     * customer to pay. Creating a link leaves the wallet balance unchanged. Requires both
     * wallet:write and charge API-key abilities and both store wallet and charge permissions. The
     * wallet must be enabled and unfrozen, and the amount and selected method must satisfy the
     * store's wallet settings. Payment completion credits the deposit and any bonus saved at
     * creation exactly once; custom-method modifiers do not change the deposit. Browser returns and
     * submitted payment proof do not prove payment. The return and cancel destination is the
     * store's customer portal wallet. Currency, metadata, and redirect overrides are unsupported.
     * Send an Idempotency-Key and reuse the same key and request for response replay within 24
     * hours. Changed input returns 409. For an uncertain provider outcome, inspect the charge
     * before starting another top-up. OAuth callers use the admin grant and select a store with
     * X-STORE. Current membership and role permissions apply to every request.
     *
     * @param customer the customer of the request.
     * @param amountCents Deposit in integer USD cents: 2500 means $25.00. The store's minimum and
     *   maximum top-up amounts also apply.
     * @param paymentMethod One enabled payment gateway allowed by the store's wallet settings for
     *   USD. CUSTOM_PAYMENT_METHOD also requires custom_payment_method_id.
     * @param customPaymentMethodId Enabled custom method in this store. Required for
     *   CUSTOM_PAYMENT_METHOD; omit or use null for other gateways.
     * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
     * @return the SdkCreateWalletTopUpResponseValue201ApplicationJson
     */
    @JvmOverloads
    fun create(
        customer: String,
        amountCents: Long,
        paymentMethod: PaymentMethod,
        customPaymentMethodId: String? = null,
        requestOptions: RequestOptions? = null,
    ): SdkCreateWalletTopUpResponseValue201ApplicationJson {
        val body =
            bodyOf(
                "amount_cents" to amountCents,
                "payment_method" to paymentMethod,
                "custom_payment_method_id" to customPaymentMethodId,
            )
        body["amount_cents"] = amountCents
        body["payment_method"] = paymentMethod
        val config =
            RequestConfig(
                method = "POST",
                path = "/v2/wallets/${encodePathSegment(customer)}/top-ups",
                body = body,
                requestOptions = requestOptions,
                requestSchema =
                    app.sell.sellapp.models.SdkCreateWalletTopUpRequestApplicationJson
                        .runtimeSchema,
                responseSchema =
                    app.sell.sellapp.models.SdkCreateWalletTopUpResponseValue201ApplicationJson
                        .runtimeSchema,
                operationId = "createWalletTopUp",
                supportsIdempotency = true,
            )
        return sellapp.baseClient.request(
            config,
            SdkCreateWalletTopUpResponseValue201ApplicationJson::class.java,
        )
    }

    @Suppress("UNCHECKED_CAST")
    fun createWithResponse(
        customer: String,
        amountCents: Long,
        paymentMethod: PaymentMethod,
        customPaymentMethodId: String? = null,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkCreateWalletTopUpResponseValue201ApplicationJson> {
        var captured: RawResponse<Any?>? = null
        val capturingOptions =
            (requestOptions?.copy() ?: RequestOptions()).also { options ->
                options.responseCapture = { response -> captured = response }
            }
        create(customer, amountCents, paymentMethod, customPaymentMethodId, capturingOptions)
        return captured as? RawResponse<SdkCreateWalletTopUpResponseValue201ApplicationJson>
            ?: error("Response metadata was not captured")
    }

    /**
     * Coroutine-aware variant of [create]. Use this from a `suspend` function or coroutine scope.
     *
     * Delegates to the blocking [create] under `withContext(Dispatchers.IO)`, so this is safe to
     * call from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("createSuspend")
    suspend fun createSuspend(
        customer: String,
        amountCents: Long,
        paymentMethod: PaymentMethod,
        customPaymentMethodId: String? = null,
        requestOptions: RequestOptions? = null,
    ): SdkCreateWalletTopUpResponseValue201ApplicationJson =
        sellapp.baseClient.runCancellable {
            create(customer, amountCents, paymentMethod, customPaymentMethodId, requestOptions)
        }

    /**
     * Coroutine-aware variant of [createWithResponse]. Use this from a `suspend` function or
     * coroutine scope.
     *
     * Delegates to the blocking [createWithResponse] under `withContext(Dispatchers.IO)`, so this
     * is safe to call from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("createWithResponseSuspend")
    suspend fun createWithResponseSuspend(
        customer: String,
        amountCents: Long,
        paymentMethod: PaymentMethod,
        customPaymentMethodId: String? = null,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkCreateWalletTopUpResponseValue201ApplicationJson> =
        sellapp.baseClient.runCancellable {
            createWithResponse(
                customer,
                amountCents,
                paymentMethod,
                customPaymentMethodId,
                requestOptions,
            )
        }
}
