// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.entitlements

import app.sell.sellapp.SellApp
import app.sell.sellapp.common.http.RawResponse
import app.sell.sellapp.common.http.RequestConfig
import app.sell.sellapp.common.http.RequestOptions
import app.sell.sellapp.common.http.encodePathSegment
import app.sell.sellapp.common.json.runtimeSchema
import app.sell.sellapp.models.SdkListCustomerEntitlementsResponseValue200ApplicationJson

/**
 * API accessor for Entitlements.
 *
 * Every operation on this class is available in two flavors: a blocking variant (`<methodName>`)
 * and a coroutine-aware variant (`<methodName>Suspend`). The `Suspend` variants delegate to the
 * blocking ones under `withContext(Dispatchers.IO)`, so they are safe to call from any coroutine
 * dispatcher (including `Dispatchers.Main`).
 */
class Entitlements(internal val sellapp: SellApp) {
    /**
     * List customer entitlements
     *
     * Unified access without raw keys, serials, files, dynamic payloads, or seller-only metadata.
     * OAuth callers use the admin grant and select a store with X-STORE. Current membership and
     * role permissions apply to every request.
     *
     * @param customer The customer identifier.
     * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
     * @return the SdkListCustomerEntitlementsResponseValue200ApplicationJson
     */
    @JvmOverloads
    fun listCustomerEntitlements(
        customer: String,
        requestOptions: RequestOptions? = null,
    ): SdkListCustomerEntitlementsResponseValue200ApplicationJson {
        val config =
            RequestConfig(
                method = "GET",
                path = "/v2/customers/${encodePathSegment(customer)}/entitlements",
                requestOptions = requestOptions,
                responseSchema =
                    app.sell.sellapp.models
                        .SdkListCustomerEntitlementsResponseValue200ApplicationJson
                        .runtimeSchema,
                operationId = "listCustomerEntitlements",
                supportsIdempotency = false,
            )
        return sellapp.baseClient.request(
            config,
            SdkListCustomerEntitlementsResponseValue200ApplicationJson::class.java,
        )
    }

    @Suppress("UNCHECKED_CAST")
    fun listCustomerEntitlementsWithResponse(
        customer: String,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkListCustomerEntitlementsResponseValue200ApplicationJson> {
        var captured: RawResponse<Any?>? = null
        val capturingOptions =
            (requestOptions?.copy() ?: RequestOptions()).also { options ->
                options.responseCapture = { response -> captured = response }
            }
        listCustomerEntitlements(customer, capturingOptions)
        return captured as? RawResponse<SdkListCustomerEntitlementsResponseValue200ApplicationJson>
            ?: error("Response metadata was not captured")
    }

    /**
     * Coroutine-aware variant of [listCustomerEntitlements]. Use this from a `suspend` function or
     * coroutine scope.
     *
     * Delegates to the blocking [listCustomerEntitlements] under `withContext(Dispatchers.IO)`, so
     * this is safe to call from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("listCustomerEntitlementsSuspend")
    suspend fun listCustomerEntitlementsSuspend(
        customer: String,
        requestOptions: RequestOptions? = null,
    ): SdkListCustomerEntitlementsResponseValue200ApplicationJson =
        sellapp.baseClient.runCancellable {
            listCustomerEntitlements(customer, requestOptions)
        }

    /**
     * Coroutine-aware variant of [listCustomerEntitlementsWithResponse]. Use this from a `suspend`
     * function or coroutine scope.
     *
     * Delegates to the blocking [listCustomerEntitlementsWithResponse] under
     * `withContext(Dispatchers.IO)`, so this is safe to call from any coroutine dispatcher
     * (including `Dispatchers.Main`).
     */
    @JvmName("listCustomerEntitlementsWithResponseSuspend")
    suspend fun listCustomerEntitlementsWithResponseSuspend(
        customer: String,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkListCustomerEntitlementsResponseValue200ApplicationJson> =
        sellapp.baseClient.runCancellable {
            listCustomerEntitlementsWithResponse(customer, requestOptions)
        }

    /**
     * List customer entitlements
     *
     * Unified access without raw keys, serials, files, dynamic payloads, or seller-only metadata.
     * OAuth callers use the admin grant and select a store with X-STORE. Current membership and
     * role permissions apply to every request.
     *
     * @param externalId The externalId identifier.
     * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
     * @return the SdkListCustomerEntitlementsResponseValue200ApplicationJson
     */
    @JvmOverloads
    fun listCustomerEntitlementsByExternalId(
        externalId: String,
        requestOptions: RequestOptions? = null,
    ): SdkListCustomerEntitlementsResponseValue200ApplicationJson {
        val config =
            RequestConfig(
                method = "GET",
                path = "/v2/customers/external/${encodePathSegment(externalId)}/entitlements",
                requestOptions = requestOptions,
                responseSchema =
                    app.sell.sellapp.models
                        .SdkListCustomerEntitlementsResponseValue200ApplicationJson
                        .runtimeSchema,
                operationId = "listCustomerEntitlementsByExternalId",
                supportsIdempotency = false,
            )
        return sellapp.baseClient.request(
            config,
            SdkListCustomerEntitlementsResponseValue200ApplicationJson::class.java,
        )
    }

    @Suppress("UNCHECKED_CAST")
    fun listCustomerEntitlementsByExternalIdWithResponse(
        externalId: String,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkListCustomerEntitlementsResponseValue200ApplicationJson> {
        var captured: RawResponse<Any?>? = null
        val capturingOptions =
            (requestOptions?.copy() ?: RequestOptions()).also { options ->
                options.responseCapture = { response -> captured = response }
            }
        listCustomerEntitlementsByExternalId(externalId, capturingOptions)
        return captured as? RawResponse<SdkListCustomerEntitlementsResponseValue200ApplicationJson>
            ?: error("Response metadata was not captured")
    }

    /**
     * Coroutine-aware variant of [listCustomerEntitlementsByExternalId]. Use this from a `suspend`
     * function or coroutine scope.
     *
     * Delegates to the blocking [listCustomerEntitlementsByExternalId] under
     * `withContext(Dispatchers.IO)`, so this is safe to call from any coroutine dispatcher
     * (including `Dispatchers.Main`).
     */
    @JvmName("listCustomerEntitlementsByExternalIdSuspend")
    suspend fun listCustomerEntitlementsByExternalIdSuspend(
        externalId: String,
        requestOptions: RequestOptions? = null,
    ): SdkListCustomerEntitlementsResponseValue200ApplicationJson =
        sellapp.baseClient.runCancellable {
            listCustomerEntitlementsByExternalId(externalId, requestOptions)
        }

    /**
     * Coroutine-aware variant of [listCustomerEntitlementsByExternalIdWithResponse]. Use this from
     * a `suspend` function or coroutine scope.
     *
     * Delegates to the blocking [listCustomerEntitlementsByExternalIdWithResponse] under
     * `withContext(Dispatchers.IO)`, so this is safe to call from any coroutine dispatcher
     * (including `Dispatchers.Main`).
     */
    @JvmName("listCustomerEntitlementsByExternalIdWithResponseSuspend")
    suspend fun listCustomerEntitlementsByExternalIdWithResponseSuspend(
        externalId: String,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkListCustomerEntitlementsResponseValue200ApplicationJson> =
        sellapp.baseClient.runCancellable {
            listCustomerEntitlementsByExternalIdWithResponse(externalId, requestOptions)
        }
}
