// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.models

import app.sell.sellapp.common.json.ObjectMapperFactory
import app.sell.sellapp.types.BlacklistType
import app.sell.sellapp.types.CatalogVisibility
import app.sell.sellapp.types.CourseVisibility
import app.sell.sellapp.types.CreateCouponResponseValue201ApplicationJsonPropertyDataType
import app.sell.sellapp.types.DeleteCouponResponseValue200ApplicationJsonPropertyDataType
import app.sell.sellapp.types.GetCouponResponseValue200ApplicationJsonPropertyDataType
import app.sell.sellapp.types.ListCouponsResponseValue200ApplicationJsonPropertyDataItemType
import app.sell.sellapp.types.ReplaceCouponResponseValue200ApplicationJsonPropertyDataType
import app.sell.sellapp.types.SdkCreateChargeRequestApplicationJsonPaymentMethod
import app.sell.sellapp.types.SdkCreateChargeRequestApplicationJsonPaymentMethods
import app.sell.sellapp.types.SdkCreateCouponRequestApplicationJsonType
import app.sell.sellapp.types.SdkReplaceCouponRequestApplicationJsonType
import app.sell.sellapp.types.SdkUpdateCouponRequestApplicationJsonType
import app.sell.sellapp.types.StoreVisibility
import app.sell.sellapp.types.UpdateCouponResponseValue200ApplicationJsonPropertyDataType
import com.fasterxml.jackson.core.type.TypeReference
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Test

class GeneratedForwardCompatTest {
    private val mapper = ObjectMapperFactory.create()

    @Test
    fun `unknown BlacklistType wire values retain their exact value`() {
        // Simulates a future server release that introduces a new enum variant.
        val parsed = mapper.readValue("\"__oagen_new_variant__\"", BlacklistType::class.java)
        assertEquals("__oagen_new_variant__", parsed.value)
        assertFalse(parsed.isKnown)
    }

    @Test
    fun `unknown CatalogVisibility wire values retain their exact value`() {
        // Simulates a future server release that introduces a new enum variant.
        val parsed = mapper.readValue("\"__oagen_new_variant__\"", CatalogVisibility::class.java)
        assertEquals("__oagen_new_variant__", parsed.value)
        assertFalse(parsed.isKnown)
    }

    @Test
    fun `unknown CourseVisibility wire values retain their exact value`() {
        // Simulates a future server release that introduces a new enum variant.
        val parsed = mapper.readValue("\"__oagen_new_variant__\"", CourseVisibility::class.java)
        assertEquals("__oagen_new_variant__", parsed.value)
        assertFalse(parsed.isKnown)
    }

    @Test
    fun `unknown StoreVisibility wire values retain their exact value`() {
        // Simulates a future server release that introduces a new enum variant.
        val parsed = mapper.readValue("\"__oagen_new_variant__\"", StoreVisibility::class.java)
        assertEquals("__oagen_new_variant__", parsed.value)
        assertFalse(parsed.isKnown)
    }

    @Test
    fun `unknown SdkCreateChargeRequestApplicationJsonPaymentMethod wire values retain their exact value`() {
        // Simulates a future server release that introduces a new enum variant.
        val parsed =
            mapper.readValue(
                "\"__oagen_new_variant__\"",
                SdkCreateChargeRequestApplicationJsonPaymentMethod::class.java,
            )
        assertEquals("__oagen_new_variant__", parsed.value)
        assertFalse(parsed.isKnown)
    }

    @Test
    fun `unknown SdkCreateChargeRequestApplicationJsonPaymentMethods wire values retain their exact value`() {
        // Simulates a future server release that introduces a new enum variant.
        val parsed =
            mapper.readValue(
                "\"__oagen_new_variant__\"",
                SdkCreateChargeRequestApplicationJsonPaymentMethods::class.java,
            )
        assertEquals("__oagen_new_variant__", parsed.value)
        assertFalse(parsed.isKnown)
    }

    @Test
    fun `unknown ListCouponsResponseValue200ApplicationJsonPropertyDataItemType wire values retain their exact value`() {
        // Simulates a future server release that introduces a new enum variant.
        val parsed =
            mapper.readValue(
                "\"__oagen_new_variant__\"",
                ListCouponsResponseValue200ApplicationJsonPropertyDataItemType::class.java,
            )
        assertEquals("__oagen_new_variant__", parsed.value)
        assertFalse(parsed.isKnown)
    }

    @Test
    fun `unknown SdkCreateCouponRequestApplicationJsonType wire values retain their exact value`() {
        // Simulates a future server release that introduces a new enum variant.
        val parsed =
            mapper.readValue(
                "\"__oagen_new_variant__\"",
                SdkCreateCouponRequestApplicationJsonType::class.java,
            )
        assertEquals("__oagen_new_variant__", parsed.value)
        assertFalse(parsed.isKnown)
    }

    @Test
    fun `unknown CreateCouponResponseValue201ApplicationJsonPropertyDataType wire values retain their exact value`() {
        // Simulates a future server release that introduces a new enum variant.
        val parsed =
            mapper.readValue(
                "\"__oagen_new_variant__\"",
                CreateCouponResponseValue201ApplicationJsonPropertyDataType::class.java,
            )
        assertEquals("__oagen_new_variant__", parsed.value)
        assertFalse(parsed.isKnown)
    }

    @Test
    fun `unknown GetCouponResponseValue200ApplicationJsonPropertyDataType wire values retain their exact value`() {
        // Simulates a future server release that introduces a new enum variant.
        val parsed =
            mapper.readValue(
                "\"__oagen_new_variant__\"",
                GetCouponResponseValue200ApplicationJsonPropertyDataType::class.java,
            )
        assertEquals("__oagen_new_variant__", parsed.value)
        assertFalse(parsed.isKnown)
    }

    @Test
    fun `unknown SdkReplaceCouponRequestApplicationJsonType wire values retain their exact value`() {
        // Simulates a future server release that introduces a new enum variant.
        val parsed =
            mapper.readValue(
                "\"__oagen_new_variant__\"",
                SdkReplaceCouponRequestApplicationJsonType::class.java,
            )
        assertEquals("__oagen_new_variant__", parsed.value)
        assertFalse(parsed.isKnown)
    }

    @Test
    fun `unknown ReplaceCouponResponseValue200ApplicationJsonPropertyDataType wire values retain their exact value`() {
        // Simulates a future server release that introduces a new enum variant.
        val parsed =
            mapper.readValue(
                "\"__oagen_new_variant__\"",
                ReplaceCouponResponseValue200ApplicationJsonPropertyDataType::class.java,
            )
        assertEquals("__oagen_new_variant__", parsed.value)
        assertFalse(parsed.isKnown)
    }

    @Test
    fun `unknown SdkUpdateCouponRequestApplicationJsonType wire values retain their exact value`() {
        // Simulates a future server release that introduces a new enum variant.
        val parsed =
            mapper.readValue(
                "\"__oagen_new_variant__\"",
                SdkUpdateCouponRequestApplicationJsonType::class.java,
            )
        assertEquals("__oagen_new_variant__", parsed.value)
        assertFalse(parsed.isKnown)
    }

    @Test
    fun `unknown UpdateCouponResponseValue200ApplicationJsonPropertyDataType wire values retain their exact value`() {
        // Simulates a future server release that introduces a new enum variant.
        val parsed =
            mapper.readValue(
                "\"__oagen_new_variant__\"",
                UpdateCouponResponseValue200ApplicationJsonPropertyDataType::class.java,
            )
        assertEquals("__oagen_new_variant__", parsed.value)
        assertFalse(parsed.isKnown)
    }

    @Test
    fun `unknown DeleteCouponResponseValue200ApplicationJsonPropertyDataType wire values retain their exact value`() {
        // Simulates a future server release that introduces a new enum variant.
        val parsed =
            mapper.readValue(
                "\"__oagen_new_variant__\"",
                DeleteCouponResponseValue200ApplicationJsonPropertyDataType::class.java,
            )
        assertEquals("__oagen_new_variant__", parsed.value)
        assertFalse(parsed.isKnown)
    }

    @Test
    fun `CustomerPortalOrderLineItem retains unknown JSON fields`() {
        val json =
            "{\"__oagen_future_field__\": \"ignored\", \"id\": 0, \"product_id\": null, \"product_variant_id\": null, \"product_title\": " +
                "null, \"variant_title\": null, \"quantity\": 0, \"status\": \"sample\"}"
        val parsed = mapper.readValue(json, CustomerPortalOrderLineItem::class.java)
        assertNotNull(parsed)
        assertEquals("ignored", parsed.additionalProperties["__oagen_future_field__"]?.asText())
        val reserialized = mapper.readTree(mapper.writeValueAsString(parsed))
        assertEquals("ignored", reserialized["__oagen_future_field__"]?.asText())
    }

    @Test
    fun `OffsetDateTime round-trips through the configured mapper`() {
        val jsonIn = "\"2024-01-15T12:34:56.789Z\""
        val parsed = mapper.readValue(jsonIn, object : TypeReference<java.time.OffsetDateTime>() {})
        val reserialized = mapper.writeValueAsString(parsed)
        // Jackson serializes OffsetDateTime as an ISO-8601 string when
        // WRITE_DATES_AS_TIMESTAMPS is disabled. The wire form may choose a
        // different offset representation (e.g. "+00:00" vs "Z") so compare
        // logical equality of the parsed value rather than the raw string.
        val reparsed =
            mapper.readValue(reserialized, object : TypeReference<java.time.OffsetDateTime>() {})
        assertEquals(parsed.toInstant(), reparsed.toInstant())
    }
}
