// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.test

import app.sell.sellapp.SellApp
import com.github.tomakehurst.wiremock.WireMockServer
import com.github.tomakehurst.wiremock.client.WireMock.aResponse
import com.github.tomakehurst.wiremock.client.WireMock.request
import com.github.tomakehurst.wiremock.client.WireMock.urlPathEqualTo
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.BeforeEach

open class TestBase {
    protected lateinit var wireMockRule: WireMockServer

    @BeforeEach
    fun startServer() {
        wireMockRule = WireMockServer(0)
        wireMockRule.start()
    }

    @AfterEach
    fun stopServer() {
        wireMockRule.stop()
    }

    protected fun createSellAppClient(accessToken: String? = null) =
        SellApp(
            apiKey = "test_key",
            store = "test_store",
            baseUrl = wireMockRule.baseUrl(),
            maxRetries = 0,
            accessToken = accessToken,
            customerSession = "session_test",
            browserSession = "sell_session=browser_test",
        )

    protected fun stubResponse(method: String, path: String, status: Int, body: String = "{}") {
        wireMockRule.stubFor(
            request(method, urlPathEqualTo(path))
                .willReturn(
                    aResponse()
                        .withStatus(status)
                        .withHeader("Content-Type", "application/json")
                        .withBody(body)
                )
        )
    }
}
