// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.types

import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonValue

/** Open BookingsStatus value returned or accepted by the API. */
data class BookingsStatus
@JsonCreator(mode = JsonCreator.Mode.DELEGATING)
constructor(
    /** The wire value sent to and received from the API. */
    @get:JsonValue val value: String
) {
    companion object {
        /** Compatibility constant for callers that need an explicit unknown marker. */
        @JvmField val Unknown = BookingsStatus("unknown")
        @JvmField val Active = BookingsStatus("active")
        @JvmField val Inactive = BookingsStatus("inactive")

        private val knownValues = setOf(Active, Inactive)

        /** Enum-compatible enumeration of generated constants. */
        @JvmStatic fun values(): Array<BookingsStatus> = arrayOf(Unknown, Active, Inactive)
    }

    /** Whether this value was known when this SDK version was generated. */
    val isKnown: Boolean
        get() = this in knownValues
}
