// This file is auto-generated by oagen. Do not edit.

@file:Suppress("ktlint:standard:max-line-length")

package app.sell.sellapp.types

/** Alias for [GetAppointmentResponseValue200ApplicationJsonPropertyDataCalendarSyncStatus]. */
typealias CancelAppointmentResponseValue200ApplicationJsonPropertyDataCalendarSyncStatus =
    GetAppointmentResponseValue200ApplicationJsonPropertyDataCalendarSyncStatus
