// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.types

import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonValue

/**
 * Open CreateRewardRuleRequestApplicationJsonPropertyOutputsItemColor value returned or accepted by
 * the API.
 */
data class CreateRewardRuleRequestApplicationJsonPropertyOutputsItemColor
@JsonCreator(mode = JsonCreator.Mode.DELEGATING)
constructor(
    /** The wire value sent to and received from the API. */
    @get:JsonValue val value: String
) {
    companion object {
        /** Compatibility constant for callers that need an explicit unknown marker. */
        @JvmField
        val Unknown = CreateRewardRuleRequestApplicationJsonPropertyOutputsItemColor("unknown")
        @JvmField val Zinc = CreateRewardRuleRequestApplicationJsonPropertyOutputsItemColor("zinc")
        @JvmField val Red = CreateRewardRuleRequestApplicationJsonPropertyOutputsItemColor("red")
        @JvmField
        val Orange = CreateRewardRuleRequestApplicationJsonPropertyOutputsItemColor("orange")
        @JvmField
        val Amber = CreateRewardRuleRequestApplicationJsonPropertyOutputsItemColor("amber")
        @JvmField
        val Yellow = CreateRewardRuleRequestApplicationJsonPropertyOutputsItemColor("yellow")
        @JvmField val Lime = CreateRewardRuleRequestApplicationJsonPropertyOutputsItemColor("lime")
        @JvmField
        val Green = CreateRewardRuleRequestApplicationJsonPropertyOutputsItemColor("green")
        @JvmField
        val Emerald = CreateRewardRuleRequestApplicationJsonPropertyOutputsItemColor("emerald")
        @JvmField val Teal = CreateRewardRuleRequestApplicationJsonPropertyOutputsItemColor("teal")
        @JvmField val Cyan = CreateRewardRuleRequestApplicationJsonPropertyOutputsItemColor("cyan")
        @JvmField val Sky = CreateRewardRuleRequestApplicationJsonPropertyOutputsItemColor("sky")
        @JvmField val Blue = CreateRewardRuleRequestApplicationJsonPropertyOutputsItemColor("blue")
        @JvmField
        val Indigo = CreateRewardRuleRequestApplicationJsonPropertyOutputsItemColor("indigo")
        @JvmField
        val Violet = CreateRewardRuleRequestApplicationJsonPropertyOutputsItemColor("violet")
        @JvmField
        val Purple = CreateRewardRuleRequestApplicationJsonPropertyOutputsItemColor("purple")
        @JvmField
        val Fuchsia = CreateRewardRuleRequestApplicationJsonPropertyOutputsItemColor("fuchsia")
        @JvmField val Pink = CreateRewardRuleRequestApplicationJsonPropertyOutputsItemColor("pink")
        @JvmField val Rose = CreateRewardRuleRequestApplicationJsonPropertyOutputsItemColor("rose")

        private val knownValues =
            setOf(
                Zinc,
                Red,
                Orange,
                Amber,
                Yellow,
                Lime,
                Green,
                Emerald,
                Teal,
                Cyan,
                Sky,
                Blue,
                Indigo,
                Violet,
                Purple,
                Fuchsia,
                Pink,
                Rose,
            )

        /** Enum-compatible enumeration of generated constants. */
        @JvmStatic
        fun values(): Array<CreateRewardRuleRequestApplicationJsonPropertyOutputsItemColor> =
            arrayOf(
                Unknown,
                Zinc,
                Red,
                Orange,
                Amber,
                Yellow,
                Lime,
                Green,
                Emerald,
                Teal,
                Cyan,
                Sky,
                Blue,
                Indigo,
                Violet,
                Purple,
                Fuchsia,
                Pink,
                Rose,
            )
    }

    /** Whether this value was known when this SDK version was generated. */
    val isKnown: Boolean
        get() = this in knownValues
}
