// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.types

import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonValue

/**
 * Open GetAppointmentResponseValue200ApplicationJsonPropertyDataStatus value returned or accepted
 * by the API.
 */
data class GetAppointmentResponseValue200ApplicationJsonPropertyDataStatus
@JsonCreator(mode = JsonCreator.Mode.DELEGATING)
constructor(
    /** The wire value sent to and received from the API. */
    @get:JsonValue val value: String
) {
    companion object {
        /** Compatibility constant for callers that need an explicit unknown marker. */
        @JvmField
        val Unknown = GetAppointmentResponseValue200ApplicationJsonPropertyDataStatus("unknown")
        @JvmField
        val Pending = GetAppointmentResponseValue200ApplicationJsonPropertyDataStatus("pending")
        @JvmField
        val Confirmed = GetAppointmentResponseValue200ApplicationJsonPropertyDataStatus("confirmed")
        @JvmField
        val Cancelled = GetAppointmentResponseValue200ApplicationJsonPropertyDataStatus("cancelled")
        @JvmField
        val NeedsReschedule =
            GetAppointmentResponseValue200ApplicationJsonPropertyDataStatus("needs_reschedule")
        @JvmField
        val Failed = GetAppointmentResponseValue200ApplicationJsonPropertyDataStatus("failed")

        private val knownValues = setOf(Pending, Confirmed, Cancelled, NeedsReschedule, Failed)

        /** Enum-compatible enumeration of generated constants. */
        @JvmStatic
        fun values(): Array<GetAppointmentResponseValue200ApplicationJsonPropertyDataStatus> =
            arrayOf(Unknown, Pending, Confirmed, Cancelled, NeedsReschedule, Failed)
    }

    /** Whether this value was known when this SDK version was generated. */
    val isKnown: Boolean
        get() = this in knownValues
}
