// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.types

import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonValue

/**
 * Open GetAppointmentResponseValue200ApplicationJsonPropertyDataCalendarSyncStatus value returned
 * or accepted by the API.
 */
data class GetAppointmentResponseValue200ApplicationJsonPropertyDataCalendarSyncStatus
@JsonCreator(mode = JsonCreator.Mode.DELEGATING)
constructor(
    /** The wire value sent to and received from the API. */
    @get:JsonValue val value: String
) {
    companion object {
        /** Compatibility constant for callers that need an explicit unknown marker. */
        @JvmField
        val Unknown =
            GetAppointmentResponseValue200ApplicationJsonPropertyDataCalendarSyncStatus("unknown")
        @JvmField
        val Pending =
            GetAppointmentResponseValue200ApplicationJsonPropertyDataCalendarSyncStatus("pending")
        @JvmField
        val Synced =
            GetAppointmentResponseValue200ApplicationJsonPropertyDataCalendarSyncStatus("synced")
        @JvmField
        val Skipped =
            GetAppointmentResponseValue200ApplicationJsonPropertyDataCalendarSyncStatus("skipped")
        @JvmField
        val Cancelled =
            GetAppointmentResponseValue200ApplicationJsonPropertyDataCalendarSyncStatus("cancelled")
        @JvmField
        val Failed =
            GetAppointmentResponseValue200ApplicationJsonPropertyDataCalendarSyncStatus("failed")

        private val knownValues = setOf(Pending, Synced, Skipped, Cancelled, Failed)

        /** Enum-compatible enumeration of generated constants. */
        @JvmStatic
        fun values():
            Array<GetAppointmentResponseValue200ApplicationJsonPropertyDataCalendarSyncStatus> =
            arrayOf(Unknown, Pending, Synced, Skipped, Cancelled, Failed)
    }

    /** Whether this value was known when this SDK version was generated. */
    val isKnown: Boolean
        get() = this in knownValues
}
