// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.types

import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonValue

/** Open InvoicesSearchBy value returned or accepted by the API. */
data class InvoicesSearchBy
@JsonCreator(mode = JsonCreator.Mode.DELEGATING)
constructor(
    /** The wire value sent to and received from the API. */
    @get:JsonValue val value: String
) {
    companion object {
        /** Compatibility constant for callers that need an explicit unknown marker. */
        @JvmField val Unknown = InvoicesSearchBy("unknown")
        @JvmField val Default = InvoicesSearchBy("default")
        @JvmField val TransactionId = InvoicesSearchBy("transaction_id")
        @JvmField val SerialCode = InvoicesSearchBy("serial_code")
        @JvmField val AdditionalInfo = InvoicesSearchBy("additional_info")
        @JvmField val ProductName = InvoicesSearchBy("product_name")
        @JvmField val DiscordData = InvoicesSearchBy("discord_data")
        @JvmField val CryptoTxid = InvoicesSearchBy("crypto_txid")
        @JvmField val CryptoAddress = InvoicesSearchBy("crypto_address")
        @JvmField val CouponCode = InvoicesSearchBy("coupon_code")

        private val knownValues =
            setOf(
                Default,
                TransactionId,
                SerialCode,
                AdditionalInfo,
                ProductName,
                DiscordData,
                CryptoTxid,
                CryptoAddress,
                CouponCode,
            )

        /** Enum-compatible enumeration of generated constants. */
        @JvmStatic
        fun values(): Array<InvoicesSearchBy> =
            arrayOf(
                Unknown,
                Default,
                TransactionId,
                SerialCode,
                AdditionalInfo,
                ProductName,
                DiscordData,
                CryptoTxid,
                CryptoAddress,
                CouponCode,
            )
    }

    /** Whether this value was known when this SDK version was generated. */
    val isKnown: Boolean
        get() = this in knownValues
}
