// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.types

import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonValue

/** Open LicenseLengthUnit value returned or accepted by the API. */
data class LicenseLengthUnit
@JsonCreator(mode = JsonCreator.Mode.DELEGATING)
constructor(
    /** The wire value sent to and received from the API. */
    @get:JsonValue val value: String
) {
    companion object {
        /** Compatibility constant for callers that need an explicit unknown marker. */
        @JvmField val Unknown = LicenseLengthUnit("unknown")
        @JvmField val Day = LicenseLengthUnit("DAY")
        @JvmField val Month = LicenseLengthUnit("MONTH")
        @JvmField val Year = LicenseLengthUnit("YEAR")
        @JvmField val Null = LicenseLengthUnit("null")

        private val knownValues = setOf(Day, Month, Year, Null)

        /** Enum-compatible enumeration of generated constants. */
        @JvmStatic fun values(): Array<LicenseLengthUnit> = arrayOf(Unknown, Day, Month, Year, Null)
    }

    /** Whether this value was known when this SDK version was generated. */
    val isKnown: Boolean
        get() = this in knownValues
}
