// This file is auto-generated by oagen. Do not edit.

@file:Suppress("ktlint:standard:max-line-length")

package app.sell.sellapp.types

/** Alias for [GetPaymentMethodStatusResponseValue200ApplicationJsonPropertyDataStatus]. */
typealias ListPaymentMethodsResponseValue200ApplicationJsonPropertyDataItemStatus =
    GetPaymentMethodStatusResponseValue200ApplicationJsonPropertyDataStatus
