// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.types

/** Alias for [GetDisputeResponseValue200ApplicationJsonPropertyDataStatus]. */
typealias ListDisputesResponseValue200ApplicationJsonPropertyDataItemStatus =
    GetDisputeResponseValue200ApplicationJsonPropertyDataStatus
