// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.types

/** Alias for [SdkUpdateCourseRequestApplicationJsonAccessType]. */
typealias ReorderCourseLessonsResponseValue200ApplicationJsonPropertyDataAccessType =
    SdkUpdateCourseRequestApplicationJsonAccessType
