// This file is auto-generated by oagen. Do not edit.

@file:Suppress("ktlint:standard:max-line-length")

package app.sell.sellapp.types

/** Alias for [SdkCreateCourseLessonRequestApplicationJsonType]. */
typealias ReplaceCourseSectionResponseValue200ApplicationJsonPropertyDataPropertyLessonsItemType =
    SdkCreateCourseLessonRequestApplicationJsonType
