// This file is auto-generated by oagen. Do not edit.

@file:Suppress("ktlint:standard:max-line-length")

package app.sell.sellapp.types

/** Alias for [PauseSubscriptionResponseValue200ApplicationJsonPropertyDataStatus]. */
typealias ResumeSubscriptionResponseValue200ApplicationJsonPropertyDataStatus =
    PauseSubscriptionResponseValue200ApplicationJsonPropertyDataStatus
