// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.types

import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonValue

/**
 * Open SdkRevokeOAuthTokenRequestApplicationXWwwFormUrlencodedTokenTypeHint value returned or
 * accepted by the API.
 */
data class SdkRevokeOAuthTokenRequestApplicationXWwwFormUrlencodedTokenTypeHint
@JsonCreator(mode = JsonCreator.Mode.DELEGATING)
constructor(
    /** The wire value sent to and received from the API. */
    @get:JsonValue val value: String
) {
    companion object {
        /** Compatibility constant for callers that need an explicit unknown marker. */
        @JvmField
        val Unknown =
            SdkRevokeOAuthTokenRequestApplicationXWwwFormUrlencodedTokenTypeHint("unknown")
        @JvmField
        val AccessToken =
            SdkRevokeOAuthTokenRequestApplicationXWwwFormUrlencodedTokenTypeHint("access_token")
        @JvmField
        val RefreshToken =
            SdkRevokeOAuthTokenRequestApplicationXWwwFormUrlencodedTokenTypeHint("refresh_token")

        private val knownValues = setOf(AccessToken, RefreshToken)

        /** Enum-compatible enumeration of generated constants. */
        @JvmStatic
        fun values(): Array<SdkRevokeOAuthTokenRequestApplicationXWwwFormUrlencodedTokenTypeHint> =
            arrayOf(Unknown, AccessToken, RefreshToken)
    }

    /** Whether this value was known when this SDK version was generated. */
    val isKnown: Boolean
        get() = this in knownValues
}
