// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.types

import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonValue

/**
 * Open SearchCustomersRequestApplicationJsonPropertySortItemField value returned or accepted by the
 * API.
 */
data class SearchCustomersRequestApplicationJsonPropertySortItemField
@JsonCreator(mode = JsonCreator.Mode.DELEGATING)
constructor(
    /** The wire value sent to and received from the API. */
    @get:JsonValue val value: String
) {
    companion object {
        /** Compatibility constant for callers that need an explicit unknown marker. */
        @JvmField
        val Unknown = SearchCustomersRequestApplicationJsonPropertySortItemField("unknown")
        @JvmField val Id = SearchCustomersRequestApplicationJsonPropertySortItemField("id")
        @JvmField val Email = SearchCustomersRequestApplicationJsonPropertySortItemField("email")
        @JvmField
        val CreatedAt = SearchCustomersRequestApplicationJsonPropertySortItemField("created_at")
        @JvmField
        val UpdatedAt = SearchCustomersRequestApplicationJsonPropertySortItemField("updated_at")

        private val knownValues = setOf(Id, Email, CreatedAt, UpdatedAt)

        /** Enum-compatible enumeration of generated constants. */
        @JvmStatic
        fun values(): Array<SearchCustomersRequestApplicationJsonPropertySortItemField> =
            arrayOf(Unknown, Id, Email, CreatedAt, UpdatedAt)
    }

    /** Whether this value was known when this SDK version was generated. */
    val isKnown: Boolean
        get() = this in knownValues
}
