// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.types

import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonValue

/**
 * Open SearchOrderLineItemsRequestApplicationJsonPropertyFiltersItemOperator value returned or
 * accepted by the API.
 */
data class SearchOrderLineItemsRequestApplicationJsonPropertyFiltersItemOperator
@JsonCreator(mode = JsonCreator.Mode.DELEGATING)
constructor(
    /** The wire value sent to and received from the API. */
    @get:JsonValue val value: String
) {
    companion object {
        /** Compatibility constant for callers that need an explicit unknown marker. */
        @JvmField
        val Unknown =
            SearchOrderLineItemsRequestApplicationJsonPropertyFiltersItemOperator("unknown")
        @JvmField
        val Eq = SearchOrderLineItemsRequestApplicationJsonPropertyFiltersItemOperator("eq")
        @JvmField
        val In = SearchOrderLineItemsRequestApplicationJsonPropertyFiltersItemOperator("in")
        @JvmField
        val Contains =
            SearchOrderLineItemsRequestApplicationJsonPropertyFiltersItemOperator("contains")
        @JvmField
        val Gt = SearchOrderLineItemsRequestApplicationJsonPropertyFiltersItemOperator("gt")
        @JvmField
        val Gte = SearchOrderLineItemsRequestApplicationJsonPropertyFiltersItemOperator("gte")
        @JvmField
        val Lt = SearchOrderLineItemsRequestApplicationJsonPropertyFiltersItemOperator("lt")
        @JvmField
        val Lte = SearchOrderLineItemsRequestApplicationJsonPropertyFiltersItemOperator("lte")

        private val knownValues = setOf(Eq, In, Contains, Gt, Gte, Lt, Lte)

        /** Enum-compatible enumeration of generated constants. */
        @JvmStatic
        fun values(): Array<SearchOrderLineItemsRequestApplicationJsonPropertyFiltersItemOperator> =
            arrayOf(Unknown, Eq, In, Contains, Gt, Gte, Lt, Lte)
    }

    /** Whether this value was known when this SDK version was generated. */
    val isKnown: Boolean
        get() = this in knownValues
}
