// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.types

/** Alias for [CommunityConnectionsPlatform]. */
typealias StartCommunityConnectionResponseValue200ApplicationJsonPropertyDataPlatform =
    CommunityConnectionsPlatform
