// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.types

import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonValue

/** Open Type value returned or accepted by the API. */
data class Type
@JsonCreator(mode = JsonCreator.Mode.DELEGATING)
constructor(
    /** The wire value sent to and received from the API. */
    @get:JsonValue val value: String
) {
    companion object {
        /** Compatibility constant for callers that need an explicit unknown marker. */
        @JvmField val Unknown = Type("unknown")
        @JvmField val Product = Type("product")
        @JvmField val Order = Type("order")
        @JvmField val Null = Type("null")

        private val knownValues = setOf(Product, Order, Null)

        /** Enum-compatible enumeration of generated constants. */
        @JvmStatic fun values(): Array<Type> = arrayOf(Unknown, Product, Order, Null)
    }

    /** Whether this value was known when this SDK version was generated. */
    val isKnown: Boolean
        get() = this in knownValues
}
