// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.types

/** Alias for [SearchAddOnsRequestApplicationJsonPropertyFiltersItemType]. */
typealias V2SearchSectionsRequestApplicationJsonPropertyFiltersItemType =
    SearchAddOnsRequestApplicationJsonPropertyFiltersItemType
