// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.entitlements

import app.sell.sellapp.common.exceptions.GenericServerException
import app.sell.sellapp.common.exceptions.NotFoundException
import app.sell.sellapp.common.exceptions.RateLimitException
import app.sell.sellapp.common.exceptions.UnauthorizedException
import app.sell.sellapp.test.TestBase
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.Test

class EntitlementsTest : TestBase() {
    private fun api() = Entitlements(createSellAppClient())

    @Test
    fun `listCustomerEntitlements returns a typed response`() {
        stubResponse("GET", "/v2/customers/sample-arg/entitlements", 200, "{\"data\": []}")
        val result = api().listCustomerEntitlements("sample-arg")
        assertNotNull(result)
    }

    @Test
    fun `listCustomerEntitlementsByExternalId returns a typed response`() {
        stubResponse("GET", "/v2/customers/external/sample-arg/entitlements", 200, "{\"data\": []}")
        val result = api().listCustomerEntitlementsByExternalId("sample-arg")
        assertNotNull(result)
    }

    @Test
    fun `listCustomerEntitlements translates 401 to UnauthorizedException`() {
        stubResponse("GET", "/v2/customers/sample-arg/entitlements", 401)
        assertThrows(UnauthorizedException::class.java) {
            api().listCustomerEntitlements("sample-arg")
        }
    }

    @Test
    fun `listCustomerEntitlements translates 404 to NotFoundException`() {
        stubResponse("GET", "/v2/customers/sample-arg/entitlements", 404)
        assertThrows(NotFoundException::class.java) {
            api().listCustomerEntitlements("sample-arg")
        }
    }

    @Test
    fun `listCustomerEntitlements translates 429 to RateLimitException`() {
        stubResponse("GET", "/v2/customers/sample-arg/entitlements", 429)
        assertThrows(RateLimitException::class.java) {
            api().listCustomerEntitlements("sample-arg")
        }
    }

    @Test
    fun `listCustomerEntitlements translates 500 to GenericServerException`() {
        stubResponse("GET", "/v2/customers/sample-arg/entitlements", 500)
        assertThrows(GenericServerException::class.java) {
            api().listCustomerEntitlements("sample-arg")
        }
    }
}
