// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.events

import app.sell.sellapp.common.exceptions.GenericServerException
import app.sell.sellapp.common.exceptions.NotFoundException
import app.sell.sellapp.common.exceptions.RateLimitException
import app.sell.sellapp.common.exceptions.UnauthorizedException
import app.sell.sellapp.test.TestBase
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.Test

class EventsTest : TestBase() {
    private fun api() = Events(createSellAppClient())

    @Test
    fun `listIntegrationEvents returns a typed response`() {
        stubResponse(
            "GET",
            "/v2/events",
            200,
            "{\"data\": [], \"list_metadata\": {\"before\": null, \"after\": null}}",
        )
        val result = api().listIntegrationEvents()
        assertNotNull(result)
    }

    @Test
    fun `listOrderEvents returns a typed response`() {
        stubResponse(
            "GET",
            "/v2/orders/sample-arg/events",
            200,
            "{\"data\": [], \"list_metadata\": {\"before\": null, \"after\": null}}",
        )
        val result = api().listOrderEvents("sample-arg")
        assertNotNull(result)
    }

    @Test
    fun `listIntegrationEvents translates 401 to UnauthorizedException`() {
        stubResponse("GET", "/v2/events", 401)
        assertThrows(UnauthorizedException::class.java) {
            api().listIntegrationEvents()
        }
    }

    @Test
    fun `listIntegrationEvents translates 404 to NotFoundException`() {
        stubResponse("GET", "/v2/events", 404)
        assertThrows(NotFoundException::class.java) {
            api().listIntegrationEvents()
        }
    }

    @Test
    fun `listIntegrationEvents translates 429 to RateLimitException`() {
        stubResponse("GET", "/v2/events", 429)
        assertThrows(RateLimitException::class.java) {
            api().listIntegrationEvents()
        }
    }

    @Test
    fun `listIntegrationEvents translates 500 to GenericServerException`() {
        stubResponse("GET", "/v2/events", 500)
        assertThrows(GenericServerException::class.java) {
            api().listIntegrationEvents()
        }
    }
}
