// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.oauth

import app.sell.sellapp.common.exceptions.GenericServerException
import app.sell.sellapp.common.exceptions.NotFoundException
import app.sell.sellapp.common.exceptions.RateLimitException
import app.sell.sellapp.common.exceptions.UnauthorizedException
import app.sell.sellapp.test.TestBase
import com.github.tomakehurst.wiremock.client.WireMock.containing
import com.github.tomakehurst.wiremock.client.WireMock.deleteRequestedFor
import com.github.tomakehurst.wiremock.client.WireMock.getRequestedFor
import com.github.tomakehurst.wiremock.client.WireMock.matching
import com.github.tomakehurst.wiremock.client.WireMock.postRequestedFor
import com.github.tomakehurst.wiremock.client.WireMock.urlPathMatching
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.Test

class OAuthTest : TestBase() {
    private fun api() = OAuth(createSellAppClient())

    @Test
    fun `getAuthorizationServerMetadata returns a typed response`() {
        stubResponse(
            "GET",
            "/.well-known/oauth-authorization-server",
            200,
            "{\"issuer\": \"sample\", \"authorization_endpoint\": \"sample\", \"token_endpoint\": \"sample\", \"revocation_endpoint\": " +
                "\"sample\", \"response_types_supported\": [], \"grant_types_supported\": [], \"code_challenge_methods_supported\": [], " +
                "\"token_endpoint_auth_methods_supported\": [], \"revocation_endpoint_auth_methods_supported\": [], \"scopes_supported\": []}",
        )
        val result = api().getAuthorizationServerMetadata()
        assertNotNull(result)
        assertEquals("sample", result.issuer)
        assertEquals("sample", result.authorizationEndpoint)
        assertEquals("sample", result.tokenEndpoint)
        assertEquals("sample", result.revocationEndpoint)
    }

    @Test
    fun `getAuthorizationRequest completes without throwing`() {
        stubResponse("GET", "/oauth/authorize", 200, "\"sample\"")
        api()
            .getAuthorizationRequest(
                "code",
                "sample-arg",
                "sample-arg",
                "sample-arg",
                "sample-argxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "S256",
            )
        wireMockRule.verify(
            getRequestedFor(urlPathMatching("/oauth/authorize"))
                .withQueryParam("client_id", matching("sample-arg"))
                .withQueryParam("redirect_uri", matching("sample-arg"))
                .withQueryParam("state", matching("sample-arg"))
                .withQueryParam(
                    "code_challenge",
                    matching("sample-argxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"),
                )
        )
    }

    @Test
    fun `approveAuthorization completes without throwing`() {
        stubResponse("POST", "/oauth/authorize", 200)
        api()
            .approveAuthorization(
                authToken = "sample-arg",
                clientId = "sample-arg",
                state = "sample-arg",
                token = "sample-arg",
            )
        wireMockRule.verify(
            postRequestedFor(urlPathMatching("/oauth/authorize"))
                .withRequestBody(containing("auth_token"))
                .withRequestBody(containing("client_id"))
                .withRequestBody(containing("state"))
                .withRequestBody(containing("_token"))
        )
    }

    @Test
    fun `denyAuthorization completes without throwing`() {
        stubResponse("DELETE", "/oauth/authorize", 204)
        api().denyAuthorization(authToken = "sample-arg", token = "sample-arg")
        wireMockRule.verify(
            deleteRequestedFor(urlPathMatching("/oauth/authorize"))
                .withRequestBody(containing("auth_token"))
                .withRequestBody(containing("_token"))
        )
    }

    @Test
    fun `exchangeToken returns a typed response`() {
        stubResponse(
            "POST",
            "/oauth/token",
            200,
            "{\"token_type\": \"Bearer\", \"expires_in\": 3600, \"access_token\": \"sample\", \"refresh_token\": \"sample\"}",
        )
        val result =
            api()
                .exchangeToken(
                    requestBody =
                        com.fasterxml.jackson.module.kotlin
                            .jacksonObjectMapper()
                            .readTree(
                                "{\"grant_type\": \"authorization_code\", \"code\": \"sample\", \"redirect_uri\": \"sample\", \"code_verifier\": \"samplexxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\"}"
                            )
                )
        assertNotNull(result)
        assertEquals("Bearer", result.tokenType)
        assertEquals(3600, result.expiresIn)
        assertEquals("sample", result.accessToken)
        assertEquals("sample", result.refreshToken)
    }

    @Test
    fun `revokeToken completes without throwing`() {
        stubResponse("POST", "/oauth/revoke", 200, "[]")
        api().revokeToken(token = "sample-arg")
        wireMockRule.verify(
            postRequestedFor(urlPathMatching("/oauth/revoke")).withRequestBody(containing("token"))
        )
    }

    @Test
    fun `getAuthorizationServerMetadata translates 401 to UnauthorizedException`() {
        stubResponse("GET", "/.well-known/oauth-authorization-server", 401)
        assertThrows(UnauthorizedException::class.java) {
            api().getAuthorizationServerMetadata()
        }
    }

    @Test
    fun `getAuthorizationServerMetadata translates 404 to NotFoundException`() {
        stubResponse("GET", "/.well-known/oauth-authorization-server", 404)
        assertThrows(NotFoundException::class.java) {
            api().getAuthorizationServerMetadata()
        }
    }

    @Test
    fun `getAuthorizationServerMetadata translates 429 to RateLimitException`() {
        stubResponse("GET", "/.well-known/oauth-authorization-server", 429)
        assertThrows(RateLimitException::class.java) {
            api().getAuthorizationServerMetadata()
        }
    }

    @Test
    fun `getAuthorizationServerMetadata translates 500 to GenericServerException`() {
        stubResponse("GET", "/.well-known/oauth-authorization-server", 500)
        assertThrows(GenericServerException::class.java) {
            api().getAuthorizationServerMetadata()
        }
    }
}
