// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.affiliatepayouts

import app.sell.sellapp.SellApp
import app.sell.sellapp.common.http.Page
import app.sell.sellapp.common.http.RawResponse
import app.sell.sellapp.common.http.RequestConfig
import app.sell.sellapp.common.http.RequestOptions
import app.sell.sellapp.common.http.encodePathSegment
import app.sell.sellapp.common.http.patchBodyOf
import app.sell.sellapp.common.json.runtimeSchema
import app.sell.sellapp.models.ListAffiliatePayoutsResponseValue200ApplicationJsonPropertyDataItem
import app.sell.sellapp.models.SdkCreateAffiliatePayoutResponseValue200ApplicationJson
import app.sell.sellapp.models.SdkGetAffiliatePayoutResponseValue200ApplicationJson
import app.sell.sellapp.models.SdkUpdateAffiliatePayoutStatusResponseValue200ApplicationJson
import app.sell.sellapp.types.AffiliatePayoutsStatus
import com.fasterxml.jackson.core.type.TypeReference

/**
 * API accessor for AffiliatePayouts.
 *
 * Every operation on this class is available in two flavors: a blocking variant (`<methodName>`)
 * and a coroutine-aware variant (`<methodName>Suspend`). The `Suspend` variants delegate to the
 * blocking ones under `withContext(Dispatchers.IO)`, so they are safe to call from any coroutine
 * dispatcher (including `Dispatchers.Main`).
 */
class AffiliatePayouts(internal val sellapp: SellApp) {
    /**
     * List affiliate payouts
     *
     * List merchant-managed affiliate payout records. These record commission payments arranged by
     * the merchant; SellApp does not transfer or hold the funds. Requires the `affiliate`
     * credential ability. OAuth callers use the admin grant and select a store with X-STORE.
     * Current membership and role permissions apply to every request.
     *
     * @param affiliateId Filter by affiliate ID.
     * @param status Filter by payout status.
     * @param limit Number of items to return per page.
     * @param page Page number to return.
     * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
     * @return a [app.sell.sellapp.common.http.Page] of results
     */
    @JvmOverloads
    fun list(
        affiliateId: Long? = null,
        status: AffiliatePayoutsStatus? = null,
        limit: Int? = null,
        page: Long? = null,
        requestOptions: RequestOptions? = null,
    ): Page<ListAffiliatePayoutsResponseValue200ApplicationJsonPropertyDataItem> {
        val itemType =
            object :
                TypeReference<
                    ListAffiliatePayoutsResponseValue200ApplicationJsonPropertyDataItem
                >() {}
        return sellapp.baseClient.requestPage(
            method = "GET",
            path = "/v2/affiliate-payouts",
            itemType = itemType,
            requestOptions = requestOptions,
            operationId = "listAffiliatePayouts",
            supportsIdempotency = false,
            itemSchema =
                app.sell.sellapp.models
                    .ListAffiliatePayoutsResponseValue200ApplicationJsonPropertyDataItem
                    .runtimeSchema,
            before = null,
            after = null,
        ) {
            affiliateId?.let { add("affiliate_id" to it.toString()) }
            status?.let { add("status" to it.value) }
            limit?.let { add("limit" to it.toString()) }
            page?.let { add("page" to it.toString()) }
        }
    }

    @Suppress("UNCHECKED_CAST")
    fun listWithResponse(
        affiliateId: Long? = null,
        status: AffiliatePayoutsStatus? = null,
        limit: Int? = null,
        page: Long? = null,
        requestOptions: RequestOptions? = null,
    ): RawResponse<Page<ListAffiliatePayoutsResponseValue200ApplicationJsonPropertyDataItem>> {
        var captured: RawResponse<Any?>? = null
        val capturingOptions =
            (requestOptions?.copy() ?: RequestOptions()).also { options ->
                options.responseCapture = { response -> captured = response }
            }
        list(affiliateId, status, limit, page, capturingOptions)
        return captured
            as?
            RawResponse<Page<ListAffiliatePayoutsResponseValue200ApplicationJsonPropertyDataItem>>
            ?: error("Response metadata was not captured")
    }

    /**
     * Coroutine-aware variant of [list]. Use this from a `suspend` function or coroutine scope.
     *
     * Delegates to the blocking [list] under `withContext(Dispatchers.IO)`, so this is safe to call
     * from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("listSuspend")
    suspend fun listSuspend(
        affiliateId: Long? = null,
        status: AffiliatePayoutsStatus? = null,
        limit: Int? = null,
        page: Long? = null,
        requestOptions: RequestOptions? = null,
    ): Page<ListAffiliatePayoutsResponseValue200ApplicationJsonPropertyDataItem> =
        sellapp.baseClient.runCancellable {
            list(affiliateId, status, limit, page, requestOptions)
        }

    /**
     * Coroutine-aware variant of [listWithResponse]. Use this from a `suspend` function or
     * coroutine scope.
     *
     * Delegates to the blocking [listWithResponse] under `withContext(Dispatchers.IO)`, so this is
     * safe to call from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("listWithResponseSuspend")
    suspend fun listWithResponseSuspend(
        affiliateId: Long? = null,
        status: AffiliatePayoutsStatus? = null,
        limit: Int? = null,
        page: Long? = null,
        requestOptions: RequestOptions? = null,
    ): RawResponse<Page<ListAffiliatePayoutsResponseValue200ApplicationJsonPropertyDataItem>> =
        sellapp.baseClient.runCancellable {
            listWithResponse(affiliateId, status, limit, page, requestOptions)
        }

    /**
     * Retrieve an affiliate payout
     *
     * Retrieve one merchant-managed affiliate payout record with a masked destination and referral
     * count. Requires the `affiliate` credential ability. OAuth callers use the admin grant and
     * select a store with X-STORE. Current membership and role permissions apply to every request.
     *
     * @param payout The payout path parameter.
     * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
     * @return the SdkGetAffiliatePayoutResponseValue200ApplicationJson
     */
    @JvmOverloads
    fun get(
        payout: String,
        requestOptions: RequestOptions? = null,
    ): SdkGetAffiliatePayoutResponseValue200ApplicationJson {
        val config =
            RequestConfig(
                method = "GET",
                path = "/v2/affiliate-payouts/${encodePathSegment(payout)}",
                requestOptions = requestOptions,
                responseSchema =
                    app.sell.sellapp.models.SdkGetAffiliatePayoutResponseValue200ApplicationJson
                        .runtimeSchema,
                operationId = "getAffiliatePayout",
                supportsIdempotency = false,
            )
        return sellapp.baseClient.request(
            config,
            SdkGetAffiliatePayoutResponseValue200ApplicationJson::class.java,
        )
    }

    @Suppress("UNCHECKED_CAST")
    fun getWithResponse(
        payout: String,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkGetAffiliatePayoutResponseValue200ApplicationJson> {
        var captured: RawResponse<Any?>? = null
        val capturingOptions =
            (requestOptions?.copy() ?: RequestOptions()).also { options ->
                options.responseCapture = { response -> captured = response }
            }
        get(payout, capturingOptions)
        return captured as? RawResponse<SdkGetAffiliatePayoutResponseValue200ApplicationJson>
            ?: error("Response metadata was not captured")
    }

    /**
     * Coroutine-aware variant of [get]. Use this from a `suspend` function or coroutine scope.
     *
     * Delegates to the blocking [get] under `withContext(Dispatchers.IO)`, so this is safe to call
     * from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("getSuspend")
    suspend fun getSuspend(
        payout: String,
        requestOptions: RequestOptions? = null,
    ): SdkGetAffiliatePayoutResponseValue200ApplicationJson =
        sellapp.baseClient.runCancellable {
            get(payout, requestOptions)
        }

    /**
     * Coroutine-aware variant of [getWithResponse]. Use this from a `suspend` function or coroutine
     * scope.
     *
     * Delegates to the blocking [getWithResponse] under `withContext(Dispatchers.IO)`, so this is
     * safe to call from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("getWithResponseSuspend")
    suspend fun getWithResponseSuspend(
        payout: String,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkGetAffiliatePayoutResponseValue200ApplicationJson> =
        sellapp.baseClient.runCancellable {
            getWithResponse(payout, requestOptions)
        }

    /**
     * Create an affiliate payout
     *
     * Create a payout record for all eligible accepted referrals of one active affiliate. The
     * merchant arranges payment separately. Replaying the same Idempotency-Key returns the same
     * record. Requires `affiliate`, `affiliate:payout`, and enough eligible commissions to meet the
     * store's minimum payout amount. OAuth callers use the admin grant and select a store with
     * X-STORE. Current membership and role permissions apply to every request.
     *
     * @param affiliate The affiliate path parameter.
     * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
     * @return the SdkCreateAffiliatePayoutResponseValue200ApplicationJson
     */
    @JvmOverloads
    fun create(
        affiliate: String,
        requestOptions: RequestOptions? = null,
    ): SdkCreateAffiliatePayoutResponseValue200ApplicationJson {
        val body = linkedMapOf<String, Any?>()
        val config =
            RequestConfig(
                method = "POST",
                path = "/v2/affiliates/${encodePathSegment(affiliate)}/payouts",
                body = body,
                requestOptions = requestOptions,
                responseSchema =
                    app.sell.sellapp.models.SdkCreateAffiliatePayoutResponseValue200ApplicationJson
                        .runtimeSchema,
                operationId = "createAffiliatePayout",
                supportsIdempotency = true,
            )
        return sellapp.baseClient.request(
            config,
            SdkCreateAffiliatePayoutResponseValue200ApplicationJson::class.java,
        )
    }

    @Suppress("UNCHECKED_CAST")
    fun createWithResponse(
        affiliate: String,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkCreateAffiliatePayoutResponseValue200ApplicationJson> {
        var captured: RawResponse<Any?>? = null
        val capturingOptions =
            (requestOptions?.copy() ?: RequestOptions()).also { options ->
                options.responseCapture = { response -> captured = response }
            }
        create(affiliate, capturingOptions)
        return captured as? RawResponse<SdkCreateAffiliatePayoutResponseValue200ApplicationJson>
            ?: error("Response metadata was not captured")
    }

    /**
     * Coroutine-aware variant of [create]. Use this from a `suspend` function or coroutine scope.
     *
     * Delegates to the blocking [create] under `withContext(Dispatchers.IO)`, so this is safe to
     * call from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("createSuspend")
    suspend fun createSuspend(
        affiliate: String,
        requestOptions: RequestOptions? = null,
    ): SdkCreateAffiliatePayoutResponseValue200ApplicationJson =
        sellapp.baseClient.runCancellable {
            create(affiliate, requestOptions)
        }

    /**
     * Coroutine-aware variant of [createWithResponse]. Use this from a `suspend` function or
     * coroutine scope.
     *
     * Delegates to the blocking [createWithResponse] under `withContext(Dispatchers.IO)`, so this
     * is safe to call from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("createWithResponseSuspend")
    suspend fun createWithResponseSuspend(
        affiliate: String,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkCreateAffiliatePayoutResponseValue200ApplicationJson> =
        sellapp.baseClient.runCancellable {
            createWithResponse(affiliate, requestOptions)
        }

    /**
     * Update affiliate payout status
     *
     * Mark an affiliate payout record due or paid and update its assigned referrals. Marking paid
     * records a payment arranged by the merchant; it does not transfer money. Identical retries
     * make no further change. Requires `affiliate` and `affiliate:payout`. OAuth callers use the
     * admin grant and select a store with X-STORE. Current membership and role permissions apply to
     * every request.
     *
     * @param payout The payout path parameter.
     * @param status the status of the request.
     * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
     * @return the SdkUpdateAffiliatePayoutStatusResponseValue200ApplicationJson
     */
    @JvmOverloads
    fun update(
        payout: String,
        status: AffiliatePayoutsStatus,
        requestOptions: RequestOptions? = null,
    ): SdkUpdateAffiliatePayoutStatusResponseValue200ApplicationJson {
        val body = patchBodyOf("status" to status)
        body["status"] = status
        val config =
            RequestConfig(
                method = "PATCH",
                path = "/v2/affiliate-payouts/${encodePathSegment(payout)}/status",
                body = body,
                requestOptions = requestOptions,
                requestSchema =
                    app.sell.sellapp.models.SdkUpdateAffiliatePayoutStatusRequestApplicationJson
                        .runtimeSchema,
                responseSchema =
                    app.sell.sellapp.models
                        .SdkUpdateAffiliatePayoutStatusResponseValue200ApplicationJson
                        .runtimeSchema,
                operationId = "updateAffiliatePayoutStatus",
                supportsIdempotency = false,
            )
        return sellapp.baseClient.request(
            config,
            SdkUpdateAffiliatePayoutStatusResponseValue200ApplicationJson::class.java,
        )
    }

    @Suppress("UNCHECKED_CAST")
    fun updateWithResponse(
        payout: String,
        status: AffiliatePayoutsStatus,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkUpdateAffiliatePayoutStatusResponseValue200ApplicationJson> {
        var captured: RawResponse<Any?>? = null
        val capturingOptions =
            (requestOptions?.copy() ?: RequestOptions()).also { options ->
                options.responseCapture = { response -> captured = response }
            }
        update(payout, status, capturingOptions)
        return captured
            as? RawResponse<SdkUpdateAffiliatePayoutStatusResponseValue200ApplicationJson>
            ?: error("Response metadata was not captured")
    }

    /**
     * Coroutine-aware variant of [update]. Use this from a `suspend` function or coroutine scope.
     *
     * Delegates to the blocking [update] under `withContext(Dispatchers.IO)`, so this is safe to
     * call from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("updateSuspend")
    suspend fun updateSuspend(
        payout: String,
        status: AffiliatePayoutsStatus,
        requestOptions: RequestOptions? = null,
    ): SdkUpdateAffiliatePayoutStatusResponseValue200ApplicationJson =
        sellapp.baseClient.runCancellable {
            update(payout, status, requestOptions)
        }

    /**
     * Coroutine-aware variant of [updateWithResponse]. Use this from a `suspend` function or
     * coroutine scope.
     *
     * Delegates to the blocking [updateWithResponse] under `withContext(Dispatchers.IO)`, so this
     * is safe to call from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("updateWithResponseSuspend")
    suspend fun updateWithResponseSuspend(
        payout: String,
        status: AffiliatePayoutsStatus,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkUpdateAffiliatePayoutStatusResponseValue200ApplicationJson> =
        sellapp.baseClient.runCancellable {
            updateWithResponse(payout, status, requestOptions)
        }
}
