// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.rewardrules

import app.sell.sellapp.common.exceptions.GenericServerException
import app.sell.sellapp.common.exceptions.NotFoundException
import app.sell.sellapp.common.exceptions.RateLimitException
import app.sell.sellapp.common.exceptions.UnauthorizedException
import app.sell.sellapp.test.TestBase
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.Test

class RewardRulesTest : TestBase() {
    private fun api() = RewardRules(createSellAppClient())

    @Test
    fun `list returns a typed response`() {
        stubResponse(
            "GET",
            "/v2/reward-rules",
            200,
            "{\"data\": [], \"list_metadata\": {\"before\": null, \"after\": null}}",
        )
        val result = api().list()
        assertNotNull(result)
    }

    @Test
    fun `search returns a typed response`() {
        stubResponse(
            "POST",
            "/v2/reward-rules/search",
            200,
            "{\"data\": [], \"list_metadata\": {\"before\": null, \"after\": null}}",
        )
        val result = api().search()
        assertNotNull(result)
    }

    @Test
    fun `get returns a typed response`() {
        stubResponse(
            "GET",
            "/v2/reward-rules/sample-arg",
            200,
            "{\"data\": {\"id\": 0, \"name\": \"sample\", \"is_active\": false, \"trigger_type\": \"PURCHASE_COUNT\", \"trigger_threshold\": " +
                "1, \"fire_once_per_customer\": false, \"outputs\": [{\"id\": 0, \"type\": \"WALLET_CREDIT\", \"sort_order\": 0, \"payload\": " +
                "{}}]}}",
        )
        val result = api().get("sample-arg")
        assertNotNull(result)
    }

    @Test
    fun `replace returns a typed response`() {
        stubResponse(
            "PUT",
            "/v2/reward-rules/sample-arg",
            200,
            "{\"data\": {\"id\": 0, \"name\": \"sample\", \"is_active\": false, \"trigger_type\": \"PURCHASE_COUNT\", \"trigger_threshold\": " +
                "1, \"fire_once_per_customer\": false, \"outputs\": [{\"id\": 0, \"type\": \"WALLET_CREDIT\", \"sort_order\": 0, \"payload\": " +
                "{}}]}}",
        )
        val result = api().replace("sample-arg")
        assertNotNull(result)
    }

    @Test
    fun `update returns a typed response`() {
        stubResponse(
            "PATCH",
            "/v2/reward-rules/sample-arg",
            200,
            "{\"data\": {\"id\": 0, \"name\": \"sample\", \"is_active\": false, \"trigger_type\": \"PURCHASE_COUNT\", \"trigger_threshold\": " +
                "1, \"fire_once_per_customer\": false, \"outputs\": [{\"id\": 0, \"type\": \"WALLET_CREDIT\", \"sort_order\": 0, \"payload\": " +
                "{}}]}}",
        )
        val result = api().update("sample-arg")
        assertNotNull(result)
    }

    @Test
    fun `list translates 401 to UnauthorizedException`() {
        stubResponse("GET", "/v2/reward-rules", 401)
        assertThrows(UnauthorizedException::class.java) {
            api().list()
        }
    }

    @Test
    fun `list translates 404 to NotFoundException`() {
        stubResponse("GET", "/v2/reward-rules", 404)
        assertThrows(NotFoundException::class.java) {
            api().list()
        }
    }

    @Test
    fun `list translates 429 to RateLimitException`() {
        stubResponse("GET", "/v2/reward-rules", 429)
        assertThrows(RateLimitException::class.java) {
            api().list()
        }
    }

    @Test
    fun `list translates 500 to GenericServerException`() {
        stubResponse("GET", "/v2/reward-rules", 500)
        assertThrows(GenericServerException::class.java) {
            api().list()
        }
    }
}
