// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.wallet

import app.sell.sellapp.SellApp
import app.sell.sellapp.common.http.Page
import app.sell.sellapp.common.http.RawResponse
import app.sell.sellapp.common.http.RequestConfig
import app.sell.sellapp.common.http.RequestOptions
import app.sell.sellapp.common.http.bodyOf
import app.sell.sellapp.common.http.encodePathSegment
import app.sell.sellapp.common.http.patchBodyOf
import app.sell.sellapp.common.json.runtimeSchema
import app.sell.sellapp.models.ListCustomerWalletsResponseValue200ApplicationJsonPropertyDataItem
import app.sell.sellapp.models.SdkAdjustCustomerWalletResponseValue200ApplicationJson
import app.sell.sellapp.models.SdkGetCustomerWalletResponseValue200ApplicationJson
import app.sell.sellapp.models.SdkUpdateCustomerWalletStatusResponseValue200ApplicationJson
import app.sell.sellapp.types.SdkUpdateCustomerWalletStatusRequestApplicationJsonStatus
import com.fasterxml.jackson.core.type.TypeReference

/**
 * API accessor for Wallet.
 *
 * Every operation on this class is available in two flavors: a blocking variant (`<methodName>`)
 * and a coroutine-aware variant (`<methodName>Suspend`). The `Suspend` variants delegate to the
 * blocking ones under `withContext(Dispatchers.IO)`, so they are safe to call from any coroutine
 * dispatcher (including `Dispatchers.Main`).
 */
class Wallet(internal val sellapp: SellApp) {
    /**
     * List customer wallets
     *
     * List customer wallet balances for the authenticated store. Requires the `wallet` or
     * `wallet:write` API ability. OAuth callers use the admin grant and select a store with
     * X-STORE. Current membership and role permissions apply to every request.
     *
     * @param limit Number of items to return per page.
     * @param page Page number to return.
     * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
     * @return a [app.sell.sellapp.common.http.Page] of results
     */
    @JvmOverloads
    fun list(
        limit: Int? = null,
        page: Long? = null,
        requestOptions: RequestOptions? = null,
    ): Page<ListCustomerWalletsResponseValue200ApplicationJsonPropertyDataItem> {
        val itemType =
            object :
                TypeReference<
                    ListCustomerWalletsResponseValue200ApplicationJsonPropertyDataItem
                >() {}
        return sellapp.baseClient.requestPage(
            method = "GET",
            path = "/v2/wallets",
            itemType = itemType,
            requestOptions = requestOptions,
            operationId = "listCustomerWallets",
            supportsIdempotency = false,
            itemSchema =
                app.sell.sellapp.models
                    .ListCustomerWalletsResponseValue200ApplicationJsonPropertyDataItem
                    .runtimeSchema,
            before = null,
            after = null,
        ) {
            limit?.let { add("limit" to it.toString()) }
            page?.let { add("page" to it.toString()) }
        }
    }

    @Suppress("UNCHECKED_CAST")
    fun listWithResponse(
        limit: Int? = null,
        page: Long? = null,
        requestOptions: RequestOptions? = null,
    ): RawResponse<Page<ListCustomerWalletsResponseValue200ApplicationJsonPropertyDataItem>> {
        var captured: RawResponse<Any?>? = null
        val capturingOptions =
            (requestOptions?.copy() ?: RequestOptions()).also { options ->
                options.responseCapture = { response -> captured = response }
            }
        list(limit, page, capturingOptions)
        return captured
            as?
            RawResponse<Page<ListCustomerWalletsResponseValue200ApplicationJsonPropertyDataItem>>
            ?: error("Response metadata was not captured")
    }

    /**
     * Coroutine-aware variant of [list]. Use this from a `suspend` function or coroutine scope.
     *
     * Delegates to the blocking [list] under `withContext(Dispatchers.IO)`, so this is safe to call
     * from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("listSuspend")
    suspend fun listSuspend(
        limit: Int? = null,
        page: Long? = null,
        requestOptions: RequestOptions? = null,
    ): Page<ListCustomerWalletsResponseValue200ApplicationJsonPropertyDataItem> =
        sellapp.baseClient.runCancellable {
            list(limit, page, requestOptions)
        }

    /**
     * Coroutine-aware variant of [listWithResponse]. Use this from a `suspend` function or
     * coroutine scope.
     *
     * Delegates to the blocking [listWithResponse] under `withContext(Dispatchers.IO)`, so this is
     * safe to call from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("listWithResponseSuspend")
    suspend fun listWithResponseSuspend(
        limit: Int? = null,
        page: Long? = null,
        requestOptions: RequestOptions? = null,
    ): RawResponse<Page<ListCustomerWalletsResponseValue200ApplicationJsonPropertyDataItem>> =
        sellapp.baseClient.runCancellable {
            listWithResponse(limit, page, requestOptions)
        }

    /**
     * Retrieve a customer wallet
     *
     * Retrieve one current-store customer wallet by customer ID. OAuth callers use the admin grant
     * and select a store with X-STORE. Current membership and role permissions apply to every
     * request.
     *
     * @param customer The customer path parameter.
     * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
     * @return the SdkGetCustomerWalletResponseValue200ApplicationJson
     */
    @JvmOverloads
    fun get(
        customer: String,
        requestOptions: RequestOptions? = null,
    ): SdkGetCustomerWalletResponseValue200ApplicationJson {
        val config =
            RequestConfig(
                method = "GET",
                path = "/v2/wallets/${encodePathSegment(customer)}",
                requestOptions = requestOptions,
                responseSchema =
                    app.sell.sellapp.models.SdkGetCustomerWalletResponseValue200ApplicationJson
                        .runtimeSchema,
                operationId = "getCustomerWallet",
                supportsIdempotency = false,
            )
        return sellapp.baseClient.request(
            config,
            SdkGetCustomerWalletResponseValue200ApplicationJson::class.java,
        )
    }

    @Suppress("UNCHECKED_CAST")
    fun getWithResponse(
        customer: String,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkGetCustomerWalletResponseValue200ApplicationJson> {
        var captured: RawResponse<Any?>? = null
        val capturingOptions =
            (requestOptions?.copy() ?: RequestOptions()).also { options ->
                options.responseCapture = { response -> captured = response }
            }
        get(customer, capturingOptions)
        return captured as? RawResponse<SdkGetCustomerWalletResponseValue200ApplicationJson>
            ?: error("Response metadata was not captured")
    }

    /**
     * Coroutine-aware variant of [get]. Use this from a `suspend` function or coroutine scope.
     *
     * Delegates to the blocking [get] under `withContext(Dispatchers.IO)`, so this is safe to call
     * from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("getSuspend")
    suspend fun getSuspend(
        customer: String,
        requestOptions: RequestOptions? = null,
    ): SdkGetCustomerWalletResponseValue200ApplicationJson =
        sellapp.baseClient.runCancellable {
            get(customer, requestOptions)
        }

    /**
     * Coroutine-aware variant of [getWithResponse]. Use this from a `suspend` function or coroutine
     * scope.
     *
     * Delegates to the blocking [getWithResponse] under `withContext(Dispatchers.IO)`, so this is
     * safe to call from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("getWithResponseSuspend")
    suspend fun getWithResponseSuspend(
        customer: String,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkGetCustomerWalletResponseValue200ApplicationJson> =
        sellapp.baseClient.runCancellable {
            getWithResponse(customer, requestOptions)
        }

    /**
     * Adjust a customer wallet
     *
     * Add or subtract a nonzero amount from a customer wallet. Requires the wallet:write API
     * ability and store wallet permission. Use signed integer cents and a nonblank note. Positive
     * adjustments can create a wallet and follow the store's credit-expiration policy; negative
     * adjustments need an existing eligible wallet and sufficient balance. Wallets must be enabled.
     * Send idempotency_key in the body. Replaying the same key returns the original entry only for
     * the same store, customer, staff actor, amount and trimmed note; changed input returns 422.
     * Keep that identity unchanged across retries. OAuth callers use the admin grant and select a
     * store with X-STORE. Current membership and role permissions apply to every request.
     *
     * @param customer The customer path parameter.
     * @param amountCents The signed adjustment amount in cents. Must not be zero.
     * @param idempotencyKey Required body key, at most 128 characters. Keep the customer, amount,
     *   staff actor and trimmed note unchanged when retrying this intended adjustment.
     * @param note the note of the request.
     * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
     * @return the SdkAdjustCustomerWalletResponseValue200ApplicationJson
     */
    @JvmOverloads
    fun adjust(
        customer: String,
        amountCents: Long,
        idempotencyKey: String,
        note: String,
        requestOptions: RequestOptions? = null,
    ): SdkAdjustCustomerWalletResponseValue200ApplicationJson {
        val body =
            bodyOf(
                "amount_cents" to amountCents,
                "idempotency_key" to idempotencyKey,
                "note" to note,
            )
        body["amount_cents"] = amountCents
        body["idempotency_key"] = idempotencyKey
        body["note"] = note
        val config =
            RequestConfig(
                method = "POST",
                path = "/v2/wallets/${encodePathSegment(customer)}/adjustments",
                body = body,
                requestOptions = requestOptions,
                requestSchema =
                    app.sell.sellapp.models.SdkAdjustCustomerWalletRequestApplicationJson
                        .runtimeSchema,
                responseSchema =
                    app.sell.sellapp.models.SdkAdjustCustomerWalletResponseValue200ApplicationJson
                        .runtimeSchema,
                operationId = "adjustCustomerWallet",
                supportsIdempotency = false,
            )
        return sellapp.baseClient.request(
            config,
            SdkAdjustCustomerWalletResponseValue200ApplicationJson::class.java,
        )
    }

    @Suppress("UNCHECKED_CAST")
    fun adjustWithResponse(
        customer: String,
        amountCents: Long,
        idempotencyKey: String,
        note: String,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkAdjustCustomerWalletResponseValue200ApplicationJson> {
        var captured: RawResponse<Any?>? = null
        val capturingOptions =
            (requestOptions?.copy() ?: RequestOptions()).also { options ->
                options.responseCapture = { response -> captured = response }
            }
        adjust(customer, amountCents, idempotencyKey, note, capturingOptions)
        return captured as? RawResponse<SdkAdjustCustomerWalletResponseValue200ApplicationJson>
            ?: error("Response metadata was not captured")
    }

    /**
     * Coroutine-aware variant of [adjust]. Use this from a `suspend` function or coroutine scope.
     *
     * Delegates to the blocking [adjust] under `withContext(Dispatchers.IO)`, so this is safe to
     * call from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("adjustSuspend")
    suspend fun adjustSuspend(
        customer: String,
        amountCents: Long,
        idempotencyKey: String,
        note: String,
        requestOptions: RequestOptions? = null,
    ): SdkAdjustCustomerWalletResponseValue200ApplicationJson =
        sellapp.baseClient.runCancellable {
            adjust(customer, amountCents, idempotencyKey, note, requestOptions)
        }

    /**
     * Coroutine-aware variant of [adjustWithResponse]. Use this from a `suspend` function or
     * coroutine scope.
     *
     * Delegates to the blocking [adjustWithResponse] under `withContext(Dispatchers.IO)`, so this
     * is safe to call from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("adjustWithResponseSuspend")
    suspend fun adjustWithResponseSuspend(
        customer: String,
        amountCents: Long,
        idempotencyKey: String,
        note: String,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkAdjustCustomerWalletResponseValue200ApplicationJson> =
        sellapp.baseClient.runCancellable {
            adjustWithResponse(customer, amountCents, idempotencyKey, note, requestOptions)
        }

    /**
     * Update a customer wallet status
     *
     * Freeze or activate an existing customer wallet. Requires wallet:write and the store wallet
     * permission, with wallets enabled. Activating a frozen wallet expires eligible credits before
     * returning, so its balance may decrease. Read balance_cents from the returned wallet.
     * Repeating the current status leaves the wallet unchanged. OAuth callers use the admin grant
     * and select a store with X-STORE. Current membership and role permissions apply to every
     * request.
     *
     * @param customer The customer path parameter.
     * @param status the status of the request.
     * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
     * @return the SdkUpdateCustomerWalletStatusResponseValue200ApplicationJson
     */
    @JvmOverloads
    fun updateStatus(
        customer: String,
        status: SdkUpdateCustomerWalletStatusRequestApplicationJsonStatus,
        requestOptions: RequestOptions? = null,
    ): SdkUpdateCustomerWalletStatusResponseValue200ApplicationJson {
        val body = patchBodyOf("status" to status)
        body["status"] = status
        val config =
            RequestConfig(
                method = "PATCH",
                path = "/v2/wallets/${encodePathSegment(customer)}/status",
                body = body,
                requestOptions = requestOptions,
                requestSchema =
                    app.sell.sellapp.models.SdkUpdateCustomerWalletStatusRequestApplicationJson
                        .runtimeSchema,
                responseSchema =
                    app.sell.sellapp.models
                        .SdkUpdateCustomerWalletStatusResponseValue200ApplicationJson
                        .runtimeSchema,
                operationId = "updateCustomerWalletStatus",
                supportsIdempotency = false,
            )
        return sellapp.baseClient.request(
            config,
            SdkUpdateCustomerWalletStatusResponseValue200ApplicationJson::class.java,
        )
    }

    @Suppress("UNCHECKED_CAST")
    fun updateStatusWithResponse(
        customer: String,
        status: SdkUpdateCustomerWalletStatusRequestApplicationJsonStatus,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkUpdateCustomerWalletStatusResponseValue200ApplicationJson> {
        var captured: RawResponse<Any?>? = null
        val capturingOptions =
            (requestOptions?.copy() ?: RequestOptions()).also { options ->
                options.responseCapture = { response -> captured = response }
            }
        updateStatus(customer, status, capturingOptions)
        return captured
            as? RawResponse<SdkUpdateCustomerWalletStatusResponseValue200ApplicationJson>
            ?: error("Response metadata was not captured")
    }

    /**
     * Coroutine-aware variant of [updateStatus]. Use this from a `suspend` function or coroutine
     * scope.
     *
     * Delegates to the blocking [updateStatus] under `withContext(Dispatchers.IO)`, so this is safe
     * to call from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("updateStatusSuspend")
    suspend fun updateStatusSuspend(
        customer: String,
        status: SdkUpdateCustomerWalletStatusRequestApplicationJsonStatus,
        requestOptions: RequestOptions? = null,
    ): SdkUpdateCustomerWalletStatusResponseValue200ApplicationJson =
        sellapp.baseClient.runCancellable {
            updateStatus(customer, status, requestOptions)
        }

    /**
     * Coroutine-aware variant of [updateStatusWithResponse]. Use this from a `suspend` function or
     * coroutine scope.
     *
     * Delegates to the blocking [updateStatusWithResponse] under `withContext(Dispatchers.IO)`, so
     * this is safe to call from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("updateStatusWithResponseSuspend")
    suspend fun updateStatusWithResponseSuspend(
        customer: String,
        status: SdkUpdateCustomerWalletStatusRequestApplicationJsonStatus,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkUpdateCustomerWalletStatusResponseValue200ApplicationJson> =
        sellapp.baseClient.runCancellable {
            updateStatusWithResponse(customer, status, requestOptions)
        }
}
