// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.wallettransactions

import app.sell.sellapp.common.exceptions.GenericServerException
import app.sell.sellapp.common.exceptions.NotFoundException
import app.sell.sellapp.common.exceptions.RateLimitException
import app.sell.sellapp.common.exceptions.UnauthorizedException
import app.sell.sellapp.test.TestBase
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.Test

class WalletTransactionsTest : TestBase() {
    private fun api() = WalletTransactions(createSellAppClient())

    @Test
    fun `list returns a typed response`() {
        stubResponse(
            "GET",
            "/v2/wallets/sample-arg/transactions",
            200,
            "{\"data\": [], \"list_metadata\": {\"before\": null, \"after\": null}}",
        )
        val result = api().list("sample-arg")
        assertNotNull(result)
    }

    @Test
    fun `list translates 401 to UnauthorizedException`() {
        stubResponse("GET", "/v2/wallets/sample-arg/transactions", 401)
        assertThrows(UnauthorizedException::class.java) {
            api().list("sample-arg")
        }
    }

    @Test
    fun `list translates 404 to NotFoundException`() {
        stubResponse("GET", "/v2/wallets/sample-arg/transactions", 404)
        assertThrows(NotFoundException::class.java) {
            api().list("sample-arg")
        }
    }

    @Test
    fun `list translates 429 to RateLimitException`() {
        stubResponse("GET", "/v2/wallets/sample-arg/transactions", 429)
        assertThrows(RateLimitException::class.java) {
            api().list("sample-arg")
        }
    }

    @Test
    fun `list translates 500 to GenericServerException`() {
        stubResponse("GET", "/v2/wallets/sample-arg/transactions", 500)
        assertThrows(GenericServerException::class.java) {
            api().list("sample-arg")
        }
    }
}
