// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.affiliates

import app.sell.sellapp.SellApp
import app.sell.sellapp.common.http.Page
import app.sell.sellapp.common.http.RawResponse
import app.sell.sellapp.common.http.RequestConfig
import app.sell.sellapp.common.http.RequestOptions
import app.sell.sellapp.common.http.addIfNotNull
import app.sell.sellapp.common.http.encodePathSegment
import app.sell.sellapp.common.http.patchBodyOf
import app.sell.sellapp.common.json.runtimeSchema
import app.sell.sellapp.models.ListAffiliatesResponseValue200ApplicationJsonPropertyDataItem
import app.sell.sellapp.models.SdkGetAffiliateResponseValue200ApplicationJson
import app.sell.sellapp.models.SdkUpdateAffiliateStatusResponseValue200ApplicationJson
import app.sell.sellapp.types.AffiliatesStatus
import app.sell.sellapp.types.SdkUpdateAffiliateStatusRequestApplicationJsonStatus
import com.fasterxml.jackson.core.type.TypeReference

/**
 * API accessor for Affiliates.
 *
 * Every operation on this class is available in two flavors: a blocking variant (`<methodName>`)
 * and a coroutine-aware variant (`<methodName>Suspend`). The `Suspend` variants delegate to the
 * blocking ones under `withContext(Dispatchers.IO)`, so they are safe to call from any coroutine
 * dispatcher (including `Dispatchers.Main`).
 */
class Affiliates(internal val sellapp: SellApp) {
    /**
     * List affiliates
     *
     * List store affiliate memberships, approved profile details, referral counts, and integer
     * USD-cent balances. Requires the `affiliate` ability. OAuth callers use the admin grant and
     * select a store with X-STORE. Current membership and role permissions apply to every request.
     *
     * @param status Filter by affiliate program status.
     * @param search Search affiliate email addresses and profile identifiers.
     * @param limit Number of items to return per page.
     * @param page Page number to return.
     * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
     * @return a [app.sell.sellapp.common.http.Page] of results
     */
    @JvmOverloads
    fun list(
        status: AffiliatesStatus? = null,
        search: String? = null,
        limit: Int? = null,
        page: Long? = null,
        requestOptions: RequestOptions? = null,
    ): Page<ListAffiliatesResponseValue200ApplicationJsonPropertyDataItem> {
        val itemType =
            object :
                TypeReference<ListAffiliatesResponseValue200ApplicationJsonPropertyDataItem>() {}
        return sellapp.baseClient.requestPage(
            method = "GET",
            path = "/v2/affiliates",
            itemType = itemType,
            requestOptions = requestOptions,
            operationId = "listAffiliates",
            supportsIdempotency = false,
            itemSchema =
                app.sell.sellapp.models
                    .ListAffiliatesResponseValue200ApplicationJsonPropertyDataItem
                    .runtimeSchema,
            before = null,
            after = null,
        ) {
            status?.let { add("status" to it.value) }
            addIfNotNull("search", search)
            limit?.let { add("limit" to it.toString()) }
            page?.let { add("page" to it.toString()) }
        }
    }

    @Suppress("UNCHECKED_CAST")
    fun listWithResponse(
        status: AffiliatesStatus? = null,
        search: String? = null,
        limit: Int? = null,
        page: Long? = null,
        requestOptions: RequestOptions? = null,
    ): RawResponse<Page<ListAffiliatesResponseValue200ApplicationJsonPropertyDataItem>> {
        var captured: RawResponse<Any?>? = null
        val capturingOptions =
            (requestOptions?.copy() ?: RequestOptions()).also { options ->
                options.responseCapture = { response -> captured = response }
            }
        list(status, search, limit, page, capturingOptions)
        return captured
            as? RawResponse<Page<ListAffiliatesResponseValue200ApplicationJsonPropertyDataItem>>
            ?: error("Response metadata was not captured")
    }

    /**
     * Coroutine-aware variant of [list]. Use this from a `suspend` function or coroutine scope.
     *
     * Delegates to the blocking [list] under `withContext(Dispatchers.IO)`, so this is safe to call
     * from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("listSuspend")
    suspend fun listSuspend(
        status: AffiliatesStatus? = null,
        search: String? = null,
        limit: Int? = null,
        page: Long? = null,
        requestOptions: RequestOptions? = null,
    ): Page<ListAffiliatesResponseValue200ApplicationJsonPropertyDataItem> =
        sellapp.baseClient.runCancellable {
            list(status, search, limit, page, requestOptions)
        }

    /**
     * Coroutine-aware variant of [listWithResponse]. Use this from a `suspend` function or
     * coroutine scope.
     *
     * Delegates to the blocking [listWithResponse] under `withContext(Dispatchers.IO)`, so this is
     * safe to call from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("listWithResponseSuspend")
    suspend fun listWithResponseSuspend(
        status: AffiliatesStatus? = null,
        search: String? = null,
        limit: Int? = null,
        page: Long? = null,
        requestOptions: RequestOptions? = null,
    ): RawResponse<Page<ListAffiliatesResponseValue200ApplicationJsonPropertyDataItem>> =
        sellapp.baseClient.runCancellable {
            listWithResponse(status, search, limit, page, requestOptions)
        }

    /**
     * Retrieve an affiliate
     *
     * Retrieve one store-scoped affiliate, profile, balances, and counts. Requires the `affiliate`
     * ability. OAuth callers use the admin grant and select a store with X-STORE. Current
     * membership and role permissions apply to every request.
     *
     * @param affiliate The affiliate path parameter.
     * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
     * @return the SdkGetAffiliateResponseValue200ApplicationJson
     */
    @JvmOverloads
    fun get(
        affiliate: String,
        requestOptions: RequestOptions? = null,
    ): SdkGetAffiliateResponseValue200ApplicationJson {
        val config =
            RequestConfig(
                method = "GET",
                path = "/v2/affiliates/${encodePathSegment(affiliate)}",
                requestOptions = requestOptions,
                responseSchema =
                    app.sell.sellapp.models.SdkGetAffiliateResponseValue200ApplicationJson
                        .runtimeSchema,
                operationId = "getAffiliate",
                supportsIdempotency = false,
            )
        return sellapp.baseClient.request(
            config,
            SdkGetAffiliateResponseValue200ApplicationJson::class.java,
        )
    }

    @Suppress("UNCHECKED_CAST")
    fun getWithResponse(
        affiliate: String,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkGetAffiliateResponseValue200ApplicationJson> {
        var captured: RawResponse<Any?>? = null
        val capturingOptions =
            (requestOptions?.copy() ?: RequestOptions()).also { options ->
                options.responseCapture = { response -> captured = response }
            }
        get(affiliate, capturingOptions)
        return captured as? RawResponse<SdkGetAffiliateResponseValue200ApplicationJson>
            ?: error("Response metadata was not captured")
    }

    /**
     * Coroutine-aware variant of [get]. Use this from a `suspend` function or coroutine scope.
     *
     * Delegates to the blocking [get] under `withContext(Dispatchers.IO)`, so this is safe to call
     * from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("getSuspend")
    suspend fun getSuspend(
        affiliate: String,
        requestOptions: RequestOptions? = null,
    ): SdkGetAffiliateResponseValue200ApplicationJson =
        sellapp.baseClient.runCancellable {
            get(affiliate, requestOptions)
        }

    /**
     * Coroutine-aware variant of [getWithResponse]. Use this from a `suspend` function or coroutine
     * scope.
     *
     * Delegates to the blocking [getWithResponse] under `withContext(Dispatchers.IO)`, so this is
     * safe to call from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("getWithResponseSuspend")
    suspend fun getWithResponseSuspend(
        affiliate: String,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkGetAffiliateResponseValue200ApplicationJson> =
        sellapp.baseClient.runCancellable {
            getWithResponse(affiliate, requestOptions)
        }

    /**
     * Update affiliate status
     *
     * Approve, disable, re-enable, or reject an affiliate through its valid state transition.
     * Requires `affiliate` and `affiliate:write`; pending invitations cannot be approved until an
     * application is submitted. OAuth callers use the admin grant and select a store with X-STORE.
     * Current membership and role permissions apply to every request.
     *
     * @param affiliate The affiliate path parameter.
     * @param status the status of the request.
     * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
     * @return the SdkUpdateAffiliateStatusResponseValue200ApplicationJson
     */
    @JvmOverloads
    fun update(
        affiliate: String,
        status: SdkUpdateAffiliateStatusRequestApplicationJsonStatus,
        requestOptions: RequestOptions? = null,
    ): SdkUpdateAffiliateStatusResponseValue200ApplicationJson {
        val body = patchBodyOf("status" to status)
        body["status"] = status
        val config =
            RequestConfig(
                method = "PATCH",
                path = "/v2/affiliates/${encodePathSegment(affiliate)}/status",
                body = body,
                requestOptions = requestOptions,
                requestSchema =
                    app.sell.sellapp.models.SdkUpdateAffiliateStatusRequestApplicationJson
                        .runtimeSchema,
                responseSchema =
                    app.sell.sellapp.models.SdkUpdateAffiliateStatusResponseValue200ApplicationJson
                        .runtimeSchema,
                operationId = "updateAffiliateStatus",
                supportsIdempotency = false,
            )
        return sellapp.baseClient.request(
            config,
            SdkUpdateAffiliateStatusResponseValue200ApplicationJson::class.java,
        )
    }

    @Suppress("UNCHECKED_CAST")
    fun updateWithResponse(
        affiliate: String,
        status: SdkUpdateAffiliateStatusRequestApplicationJsonStatus,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkUpdateAffiliateStatusResponseValue200ApplicationJson> {
        var captured: RawResponse<Any?>? = null
        val capturingOptions =
            (requestOptions?.copy() ?: RequestOptions()).also { options ->
                options.responseCapture = { response -> captured = response }
            }
        update(affiliate, status, capturingOptions)
        return captured as? RawResponse<SdkUpdateAffiliateStatusResponseValue200ApplicationJson>
            ?: error("Response metadata was not captured")
    }

    /**
     * Coroutine-aware variant of [update]. Use this from a `suspend` function or coroutine scope.
     *
     * Delegates to the blocking [update] under `withContext(Dispatchers.IO)`, so this is safe to
     * call from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("updateSuspend")
    suspend fun updateSuspend(
        affiliate: String,
        status: SdkUpdateAffiliateStatusRequestApplicationJsonStatus,
        requestOptions: RequestOptions? = null,
    ): SdkUpdateAffiliateStatusResponseValue200ApplicationJson =
        sellapp.baseClient.runCancellable {
            update(affiliate, status, requestOptions)
        }

    /**
     * Coroutine-aware variant of [updateWithResponse]. Use this from a `suspend` function or
     * coroutine scope.
     *
     * Delegates to the blocking [updateWithResponse] under `withContext(Dispatchers.IO)`, so this
     * is safe to call from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("updateWithResponseSuspend")
    suspend fun updateWithResponseSuspend(
        affiliate: String,
        status: SdkUpdateAffiliateStatusRequestApplicationJsonStatus,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkUpdateAffiliateStatusResponseValue200ApplicationJson> =
        sellapp.baseClient.runCancellable {
            updateWithResponse(affiliate, status, requestOptions)
        }
}
