// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.highlightsmedia

import app.sell.sellapp.SellApp
import app.sell.sellapp.common.http.PatchField
import app.sell.sellapp.common.http.RawResponse
import app.sell.sellapp.common.http.RequestConfig
import app.sell.sellapp.common.http.RequestOptions
import app.sell.sellapp.common.http.bodyOf
import app.sell.sellapp.common.http.encodePathSegment
import app.sell.sellapp.common.http.patchBodyOf
import app.sell.sellapp.common.json.runtimeSchema
import app.sell.sellapp.models.SdkAddHighlightMediaResponseValue201ApplicationJson
import app.sell.sellapp.models.SdkListHighlightMediaResponseValue200ApplicationJson
import app.sell.sellapp.models.SdkReorderHighlightMediaResponseValue200ApplicationJson
import app.sell.sellapp.models.SdkReplaceHighlightMediaMetadataResponseValue200ApplicationJson
import app.sell.sellapp.models.SdkReplaceHighlightMediaResponseValue200ApplicationJson
import app.sell.sellapp.models.SdkUpdateHighlightMediaResponseValue200ApplicationJson

/**
 * API accessor for HighlightsMedia.
 *
 * Every operation on this class is available in two flavors: a blocking variant (`<methodName>`)
 * and a coroutine-aware variant (`<methodName>Suspend`). The `Suspend` variants delegate to the
 * blocking ones under `withContext(Dispatchers.IO)`, so they are safe to call from any coroutine
 * dispatcher (including `Dispatchers.Main`).
 */
class HighlightsMedia(internal val sellapp: SellApp) {
    /**
     * List highlight media
     *
     * List media attached to a highlight in display order. OAuth callers use the admin grant and
     * select a store with X-STORE. Current membership and role permissions apply to every request.
     *
     * @param highlight The highlight path parameter.
     * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
     * @return the SdkListHighlightMediaResponseValue200ApplicationJson
     */
    @JvmOverloads
    fun list(
        highlight: String,
        requestOptions: RequestOptions? = null,
    ): SdkListHighlightMediaResponseValue200ApplicationJson {
        val config =
            RequestConfig(
                method = "GET",
                path = "/v2/highlights/${encodePathSegment(highlight)}/media",
                requestOptions = requestOptions,
                responseSchema =
                    app.sell.sellapp.models.SdkListHighlightMediaResponseValue200ApplicationJson
                        .runtimeSchema,
                operationId = "listHighlightMedia",
                supportsIdempotency = false,
            )
        return sellapp.baseClient.request(
            config,
            SdkListHighlightMediaResponseValue200ApplicationJson::class.java,
        )
    }

    @Suppress("UNCHECKED_CAST")
    fun listWithResponse(
        highlight: String,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkListHighlightMediaResponseValue200ApplicationJson> {
        var captured: RawResponse<Any?>? = null
        val capturingOptions =
            (requestOptions?.copy() ?: RequestOptions()).also { options ->
                options.responseCapture = { response -> captured = response }
            }
        list(highlight, capturingOptions)
        return captured as? RawResponse<SdkListHighlightMediaResponseValue200ApplicationJson>
            ?: error("Response metadata was not captured")
    }

    /**
     * Coroutine-aware variant of [list]. Use this from a `suspend` function or coroutine scope.
     *
     * Delegates to the blocking [list] under `withContext(Dispatchers.IO)`, so this is safe to call
     * from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("listSuspend")
    suspend fun listSuspend(
        highlight: String,
        requestOptions: RequestOptions? = null,
    ): SdkListHighlightMediaResponseValue200ApplicationJson =
        sellapp.baseClient.runCancellable {
            list(highlight, requestOptions)
        }

    /**
     * Coroutine-aware variant of [listWithResponse]. Use this from a `suspend` function or
     * coroutine scope.
     *
     * Delegates to the blocking [listWithResponse] under `withContext(Dispatchers.IO)`, so this is
     * safe to call from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("listWithResponseSuspend")
    suspend fun listWithResponseSuspend(
        highlight: String,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkListHighlightMediaResponseValue200ApplicationJson> =
        sellapp.baseClient.runCancellable {
            listWithResponse(highlight, requestOptions)
        }

    /**
     * Add highlight media
     *
     * Upload an image or video and append it to a highlight, up to 30 media items in total. OAuth
     * callers use the admin grant and select a store with X-STORE. Current membership and role
     * permissions apply to every request.
     *
     * @param highlight The highlight path parameter.
     * @param file the file of the request.
     * @param ctaTitle the cta title of the request.
     * @param productId the product id of the request.
     * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
     * @return the SdkAddHighlightMediaResponseValue201ApplicationJson
     */
    @JvmOverloads
    fun add(
        highlight: String,
        file: ByteArray,
        ctaTitle: String? = null,
        productId: Long? = null,
        requestOptions: RequestOptions? = null,
    ): SdkAddHighlightMediaResponseValue201ApplicationJson {
        val body =
            bodyOf(
                "file" to file,
                "cta_title" to ctaTitle,
                "product_id" to productId,
            )
        body["file"] = file
        val config =
            RequestConfig(
                method = "POST",
                path = "/v2/highlights/${encodePathSegment(highlight)}/media",
                body = body,
                bodyEncoding = "form-data",
                requestOptions = requestOptions,
                requestSchema =
                    app.sell.sellapp.models.SdkAddHighlightMediaRequestMultipartFormData
                        .runtimeSchema,
                responseSchema =
                    app.sell.sellapp.models.SdkAddHighlightMediaResponseValue201ApplicationJson
                        .runtimeSchema,
                operationId = "addHighlightMedia",
                supportsIdempotency = false,
            )
        return sellapp.baseClient.request(
            config,
            SdkAddHighlightMediaResponseValue201ApplicationJson::class.java,
        )
    }

    @Suppress("UNCHECKED_CAST")
    fun addWithResponse(
        highlight: String,
        file: ByteArray,
        ctaTitle: String? = null,
        productId: Long? = null,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkAddHighlightMediaResponseValue201ApplicationJson> {
        var captured: RawResponse<Any?>? = null
        val capturingOptions =
            (requestOptions?.copy() ?: RequestOptions()).also { options ->
                options.responseCapture = { response -> captured = response }
            }
        add(highlight, file, ctaTitle, productId, capturingOptions)
        return captured as? RawResponse<SdkAddHighlightMediaResponseValue201ApplicationJson>
            ?: error("Response metadata was not captured")
    }

    /**
     * Coroutine-aware variant of [add]. Use this from a `suspend` function or coroutine scope.
     *
     * Delegates to the blocking [add] under `withContext(Dispatchers.IO)`, so this is safe to call
     * from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("addSuspend")
    suspend fun addSuspend(
        highlight: String,
        file: ByteArray,
        ctaTitle: String? = null,
        productId: Long? = null,
        requestOptions: RequestOptions? = null,
    ): SdkAddHighlightMediaResponseValue201ApplicationJson =
        sellapp.baseClient.runCancellable {
            add(highlight, file, ctaTitle, productId, requestOptions)
        }

    /**
     * Coroutine-aware variant of [addWithResponse]. Use this from a `suspend` function or coroutine
     * scope.
     *
     * Delegates to the blocking [addWithResponse] under `withContext(Dispatchers.IO)`, so this is
     * safe to call from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("addWithResponseSuspend")
    suspend fun addWithResponseSuspend(
        highlight: String,
        file: ByteArray,
        ctaTitle: String? = null,
        productId: Long? = null,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkAddHighlightMediaResponseValue201ApplicationJson> =
        sellapp.baseClient.runCancellable {
            addWithResponse(highlight, file, ctaTitle, productId, requestOptions)
        }

    /**
     * Reorder highlight media
     *
     * Replace the complete media order for a highlight with the supplied media IDs. OAuth callers
     * use the admin grant and select a store with X-STORE. Current membership and role permissions
     * apply to every request.
     *
     * @param highlight The highlight path parameter.
     * @param resources the resources of the request.
     * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
     * @return the SdkReorderHighlightMediaResponseValue200ApplicationJson
     */
    @JvmOverloads
    fun reorder(
        highlight: String,
        resources: List<Long>,
        requestOptions: RequestOptions? = null,
    ): SdkReorderHighlightMediaResponseValue200ApplicationJson {
        val body = patchBodyOf("resources" to resources)
        body["resources"] = resources
        val config =
            RequestConfig(
                method = "PATCH",
                path = "/v2/highlights/${encodePathSegment(highlight)}/media/reorder",
                body = body,
                requestOptions = requestOptions,
                requestSchema =
                    app.sell.sellapp.models.SdkReorderHighlightsRequestApplicationJson
                        .runtimeSchema,
                responseSchema =
                    app.sell.sellapp.models.SdkReorderHighlightMediaResponseValue200ApplicationJson
                        .runtimeSchema,
                operationId = "reorderHighlightMedia",
                supportsIdempotency = false,
            )
        return sellapp.baseClient.request(
            config,
            SdkReorderHighlightMediaResponseValue200ApplicationJson::class.java,
        )
    }

    @Suppress("UNCHECKED_CAST")
    fun reorderWithResponse(
        highlight: String,
        resources: List<Long>,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkReorderHighlightMediaResponseValue200ApplicationJson> {
        var captured: RawResponse<Any?>? = null
        val capturingOptions =
            (requestOptions?.copy() ?: RequestOptions()).also { options ->
                options.responseCapture = { response -> captured = response }
            }
        reorder(highlight, resources, capturingOptions)
        return captured as? RawResponse<SdkReorderHighlightMediaResponseValue200ApplicationJson>
            ?: error("Response metadata was not captured")
    }

    /**
     * Coroutine-aware variant of [reorder]. Use this from a `suspend` function or coroutine scope.
     *
     * Delegates to the blocking [reorder] under `withContext(Dispatchers.IO)`, so this is safe to
     * call from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("reorderSuspend")
    suspend fun reorderSuspend(
        highlight: String,
        resources: List<Long>,
        requestOptions: RequestOptions? = null,
    ): SdkReorderHighlightMediaResponseValue200ApplicationJson =
        sellapp.baseClient.runCancellable {
            reorder(highlight, resources, requestOptions)
        }

    /**
     * Coroutine-aware variant of [reorderWithResponse]. Use this from a `suspend` function or
     * coroutine scope.
     *
     * Delegates to the blocking [reorderWithResponse] under `withContext(Dispatchers.IO)`, so this
     * is safe to call from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("reorderWithResponseSuspend")
    suspend fun reorderWithResponseSuspend(
        highlight: String,
        resources: List<Long>,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkReorderHighlightMediaResponseValue200ApplicationJson> =
        sellapp.baseClient.runCancellable {
            reorderWithResponse(highlight, resources, requestOptions)
        }

    /**
     * Replace highlight media
     *
     * Replace highlight media for a highlight. Deleting the last media item unpublishes the
     * highlight. OAuth callers use the admin grant and select a store with X-STORE. Current
     * membership and role permissions apply to every request.
     *
     * @param highlight The highlight path parameter.
     * @param media The media path parameter.
     * @param file the file of the request.
     * @param ctaTitle the cta title of the request.
     * @param productId the product id of the request.
     * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
     * @return the SdkReplaceHighlightMediaResponseValue200ApplicationJson
     */
    @JvmOverloads
    fun replace(
        highlight: String,
        media: String,
        file: ByteArray,
        ctaTitle: String? = null,
        productId: Long? = null,
        requestOptions: RequestOptions? = null,
    ): SdkReplaceHighlightMediaResponseValue200ApplicationJson {
        val body =
            bodyOf(
                "file" to file,
                "cta_title" to ctaTitle,
                "product_id" to productId,
            )
        body["file"] = file
        val config =
            RequestConfig(
                method = "POST",
                path =
                    "/v2/highlights/${encodePathSegment(highlight)}/media/${encodePathSegment(media)}",
                body = body,
                bodyEncoding = "form-data",
                requestOptions = requestOptions,
                requestSchema =
                    app.sell.sellapp.models.SdkReplaceHighlightMediaRequestMultipartFormData
                        .runtimeSchema,
                responseSchema =
                    app.sell.sellapp.models.SdkReplaceHighlightMediaResponseValue200ApplicationJson
                        .runtimeSchema,
                operationId = "replaceHighlightMedia",
                supportsIdempotency = false,
            )
        return sellapp.baseClient.request(
            config,
            SdkReplaceHighlightMediaResponseValue200ApplicationJson::class.java,
        )
    }

    @Suppress("UNCHECKED_CAST")
    fun replaceWithResponse(
        highlight: String,
        media: String,
        file: ByteArray,
        ctaTitle: String? = null,
        productId: Long? = null,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkReplaceHighlightMediaResponseValue200ApplicationJson> {
        var captured: RawResponse<Any?>? = null
        val capturingOptions =
            (requestOptions?.copy() ?: RequestOptions()).also { options ->
                options.responseCapture = { response -> captured = response }
            }
        replace(highlight, media, file, ctaTitle, productId, capturingOptions)
        return captured as? RawResponse<SdkReplaceHighlightMediaResponseValue200ApplicationJson>
            ?: error("Response metadata was not captured")
    }

    /**
     * Coroutine-aware variant of [replace]. Use this from a `suspend` function or coroutine scope.
     *
     * Delegates to the blocking [replace] under `withContext(Dispatchers.IO)`, so this is safe to
     * call from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("replaceSuspend")
    suspend fun replaceSuspend(
        highlight: String,
        media: String,
        file: ByteArray,
        ctaTitle: String? = null,
        productId: Long? = null,
        requestOptions: RequestOptions? = null,
    ): SdkReplaceHighlightMediaResponseValue200ApplicationJson =
        sellapp.baseClient.runCancellable {
            replace(highlight, media, file, ctaTitle, productId, requestOptions)
        }

    /**
     * Coroutine-aware variant of [replaceWithResponse]. Use this from a `suspend` function or
     * coroutine scope.
     *
     * Delegates to the blocking [replaceWithResponse] under `withContext(Dispatchers.IO)`, so this
     * is safe to call from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("replaceWithResponseSuspend")
    suspend fun replaceWithResponseSuspend(
        highlight: String,
        media: String,
        file: ByteArray,
        ctaTitle: String? = null,
        productId: Long? = null,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkReplaceHighlightMediaResponseValue200ApplicationJson> =
        sellapp.baseClient.runCancellable {
            replaceWithResponse(highlight, media, file, ctaTitle, productId, requestOptions)
        }

    /**
     * Update highlight media
     *
     * Update highlight media for a highlight. Deleting the last media item unpublishes the
     * highlight. OAuth callers use the admin grant and select a store with X-STORE. Current
     * membership and role permissions apply to every request.
     *
     * @param highlight The highlight path parameter.
     * @param media The media path parameter.
     * @param ctaTitle the cta title of the request.
     * @param productId the product id of the request.
     * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
     * @return the SdkReplaceHighlightMediaMetadataResponseValue200ApplicationJson
     */
    @JvmOverloads
    fun replaceMetadata(
        highlight: String,
        media: String,
        ctaTitle: String? = null,
        productId: Long? = null,
        requestOptions: RequestOptions? = null,
    ): SdkReplaceHighlightMediaMetadataResponseValue200ApplicationJson {
        val body =
            bodyOf(
                "cta_title" to ctaTitle,
                "product_id" to productId,
            )
        val config =
            RequestConfig(
                method = "PUT",
                path =
                    "/v2/highlights/${encodePathSegment(highlight)}/media/${encodePathSegment(media)}",
                body = body,
                requestOptions = requestOptions,
                requestSchema =
                    app.sell.sellapp.models.SdkReplaceHighlightMediaMetadataRequestApplicationJson
                        .runtimeSchema,
                responseSchema =
                    app.sell.sellapp.models
                        .SdkReplaceHighlightMediaMetadataResponseValue200ApplicationJson
                        .runtimeSchema,
                operationId = "replaceHighlightMediaMetadata",
                supportsIdempotency = false,
            )
        return sellapp.baseClient.request(
            config,
            SdkReplaceHighlightMediaMetadataResponseValue200ApplicationJson::class.java,
        )
    }

    @Suppress("UNCHECKED_CAST")
    fun replaceMetadataWithResponse(
        highlight: String,
        media: String,
        ctaTitle: String? = null,
        productId: Long? = null,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkReplaceHighlightMediaMetadataResponseValue200ApplicationJson> {
        var captured: RawResponse<Any?>? = null
        val capturingOptions =
            (requestOptions?.copy() ?: RequestOptions()).also { options ->
                options.responseCapture = { response -> captured = response }
            }
        replaceMetadata(highlight, media, ctaTitle, productId, capturingOptions)
        return captured
            as? RawResponse<SdkReplaceHighlightMediaMetadataResponseValue200ApplicationJson>
            ?: error("Response metadata was not captured")
    }

    /**
     * Coroutine-aware variant of [replaceMetadata]. Use this from a `suspend` function or coroutine
     * scope.
     *
     * Delegates to the blocking [replaceMetadata] under `withContext(Dispatchers.IO)`, so this is
     * safe to call from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("replaceMetadataSuspend")
    suspend fun replaceMetadataSuspend(
        highlight: String,
        media: String,
        ctaTitle: String? = null,
        productId: Long? = null,
        requestOptions: RequestOptions? = null,
    ): SdkReplaceHighlightMediaMetadataResponseValue200ApplicationJson =
        sellapp.baseClient.runCancellable {
            replaceMetadata(highlight, media, ctaTitle, productId, requestOptions)
        }

    /**
     * Coroutine-aware variant of [replaceMetadataWithResponse]. Use this from a `suspend` function
     * or coroutine scope.
     *
     * Delegates to the blocking [replaceMetadataWithResponse] under `withContext(Dispatchers.IO)`,
     * so this is safe to call from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("replaceMetadataWithResponseSuspend")
    suspend fun replaceMetadataWithResponseSuspend(
        highlight: String,
        media: String,
        ctaTitle: String? = null,
        productId: Long? = null,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkReplaceHighlightMediaMetadataResponseValue200ApplicationJson> =
        sellapp.baseClient.runCancellable {
            replaceMetadataWithResponse(highlight, media, ctaTitle, productId, requestOptions)
        }

    /**
     * Update highlight media
     *
     * Update highlight media for a highlight. Deleting the last media item unpublishes the
     * highlight. OAuth callers use the admin grant and select a store with X-STORE. Current
     * membership and role permissions apply to every request.
     *
     * @param highlight The highlight path parameter.
     * @param media The media path parameter.
     * @param ctaTitle the cta title of the request.
     * @param productId the product id of the request.
     * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
     * @return the SdkUpdateHighlightMediaResponseValue200ApplicationJson
     */
    @JvmOverloads
    fun update(
        highlight: String,
        media: String,
        ctaTitle: PatchField<String> = PatchField.Absent,
        productId: PatchField<Long?> = PatchField.Absent,
        requestOptions: RequestOptions? = null,
    ): SdkUpdateHighlightMediaResponseValue200ApplicationJson {
        val body =
            patchBodyOf(
                "cta_title" to ctaTitle,
                "product_id" to productId,
            )
        val config =
            RequestConfig(
                method = "PATCH",
                path =
                    "/v2/highlights/${encodePathSegment(highlight)}/media/${encodePathSegment(media)}",
                body = body,
                requestOptions = requestOptions,
                requestSchema =
                    app.sell.sellapp.models.SdkUpdateHighlightMediaRequestApplicationJson
                        .runtimeSchema,
                responseSchema =
                    app.sell.sellapp.models.SdkUpdateHighlightMediaResponseValue200ApplicationJson
                        .runtimeSchema,
                operationId = "updateHighlightMedia",
                supportsIdempotency = false,
            )
        return sellapp.baseClient.request(
            config,
            SdkUpdateHighlightMediaResponseValue200ApplicationJson::class.java,
        )
    }

    @Suppress("UNCHECKED_CAST")
    fun updateWithResponse(
        highlight: String,
        media: String,
        ctaTitle: PatchField<String> = PatchField.Absent,
        productId: PatchField<Long?> = PatchField.Absent,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkUpdateHighlightMediaResponseValue200ApplicationJson> {
        var captured: RawResponse<Any?>? = null
        val capturingOptions =
            (requestOptions?.copy() ?: RequestOptions()).also { options ->
                options.responseCapture = { response -> captured = response }
            }
        update(highlight, media, ctaTitle, productId, capturingOptions)
        return captured as? RawResponse<SdkUpdateHighlightMediaResponseValue200ApplicationJson>
            ?: error("Response metadata was not captured")
    }

    /**
     * Coroutine-aware variant of [update]. Use this from a `suspend` function or coroutine scope.
     *
     * Delegates to the blocking [update] under `withContext(Dispatchers.IO)`, so this is safe to
     * call from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("updateSuspend")
    suspend fun updateSuspend(
        highlight: String,
        media: String,
        ctaTitle: PatchField<String> = PatchField.Absent,
        productId: PatchField<Long?> = PatchField.Absent,
        requestOptions: RequestOptions? = null,
    ): SdkUpdateHighlightMediaResponseValue200ApplicationJson =
        sellapp.baseClient.runCancellable {
            update(highlight, media, ctaTitle, productId, requestOptions)
        }

    /**
     * Coroutine-aware variant of [updateWithResponse]. Use this from a `suspend` function or
     * coroutine scope.
     *
     * Delegates to the blocking [updateWithResponse] under `withContext(Dispatchers.IO)`, so this
     * is safe to call from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("updateWithResponseSuspend")
    suspend fun updateWithResponseSuspend(
        highlight: String,
        media: String,
        ctaTitle: PatchField<String> = PatchField.Absent,
        productId: PatchField<Long?> = PatchField.Absent,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkUpdateHighlightMediaResponseValue200ApplicationJson> =
        sellapp.baseClient.runCancellable {
            updateWithResponse(highlight, media, ctaTitle, productId, requestOptions)
        }

    /**
     * Delete highlight media
     *
     * Delete highlight media for a highlight. Deleting the last media item unpublishes the
     * highlight. OAuth callers use the admin grant and select a store with X-STORE. Current
     * membership and role permissions apply to every request.
     *
     * @param highlight The highlight path parameter.
     * @param media The media path parameter.
     * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
     */
    @JvmOverloads
    fun delete(
        highlight: String,
        media: String,
        requestOptions: RequestOptions? = null,
    ) {
        val config =
            RequestConfig(
                method = "DELETE",
                path =
                    "/v2/highlights/${encodePathSegment(highlight)}/media/${encodePathSegment(media)}",
                requestOptions = requestOptions,
                responseSchema =
                    app.sell.sellapp.models.SdkDeleteHighlightMediaResponseValue200ApplicationJson
                        .runtimeSchema,
                operationId = "deleteHighlightMedia",
                supportsIdempotency = false,
            )
        sellapp.baseClient.requestVoid(config)
    }

    @Suppress("UNCHECKED_CAST")
    fun deleteWithResponse(
        highlight: String,
        media: String,
        requestOptions: RequestOptions? = null,
    ): RawResponse<Unit> {
        var captured: RawResponse<Any?>? = null
        val capturingOptions =
            (requestOptions?.copy() ?: RequestOptions()).also { options ->
                options.responseCapture = { response -> captured = response }
            }
        delete(highlight, media, capturingOptions)
        return captured as? RawResponse<Unit> ?: error("Response metadata was not captured")
    }

    /**
     * Coroutine-aware variant of [delete]. Use this from a `suspend` function or coroutine scope.
     *
     * Delegates to the blocking [delete] under `withContext(Dispatchers.IO)`, so this is safe to
     * call from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("deleteSuspend")
    suspend fun deleteSuspend(
        highlight: String,
        media: String,
        requestOptions: RequestOptions? = null,
    ) =
        sellapp.baseClient.runCancellable {
            delete(highlight, media, requestOptions)
        }

    /**
     * Coroutine-aware variant of [deleteWithResponse]. Use this from a `suspend` function or
     * coroutine scope.
     *
     * Delegates to the blocking [deleteWithResponse] under `withContext(Dispatchers.IO)`, so this
     * is safe to call from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("deleteWithResponseSuspend")
    suspend fun deleteWithResponseSuspend(
        highlight: String,
        media: String,
        requestOptions: RequestOptions? = null,
    ): RawResponse<Unit> =
        sellapp.baseClient.runCancellable {
            deleteWithResponse(highlight, media, requestOptions)
        }
}
