// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.communityconnections

import app.sell.sellapp.common.exceptions.GenericServerException
import app.sell.sellapp.common.exceptions.NotFoundException
import app.sell.sellapp.common.exceptions.RateLimitException
import app.sell.sellapp.common.exceptions.UnauthorizedException
import app.sell.sellapp.test.TestBase
import com.github.tomakehurst.wiremock.client.WireMock.getRequestedFor
import com.github.tomakehurst.wiremock.client.WireMock.matching
import com.github.tomakehurst.wiremock.client.WireMock.matchingJsonPath
import com.github.tomakehurst.wiremock.client.WireMock.postRequestedFor
import com.github.tomakehurst.wiremock.client.WireMock.urlPathMatching
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.Test

class CommunityConnectionsTest : TestBase() {
    private fun api() = CommunityConnections(createSellAppClient())

    @Test
    fun `list returns a typed response`() {
        stubResponse("GET", "/v2/community-connections", 200, "{\"data\": []}")
        val result = api().list()
        assertNotNull(result)
    }

    @Test
    fun `start returns a typed response`() {
        stubResponse(
            "POST",
            "/v2/community-connections/sample-arg/connect",
            200,
            "{\"data\": {\"platform\": \"discord\", \"type\": \"oauth\"}}",
        )
        val result = api().start("sample-arg")
        assertNotNull(result)
    }

    @Test
    fun `poll returns a typed response`() {
        stubResponse(
            "GET",
            "/v2/community-connections/sample-arg/status",
            200,
            "{\"data\": {\"platform\": \"telegram\", \"status\": \"pending\"}}",
        )
        val result = api().poll("sample-arg", "sample-arg")
        assertNotNull(result)
        wireMockRule.verify(
            getRequestedFor(urlPathMatching("/v2/community-connections/sample-arg/status"))
                .withQueryParam("status_token", matching("sample-arg"))
        )
    }

    @Test
    fun `complete returns a typed response`() {
        stubResponse(
            "POST",
            "/v2/community-connections/sample-arg/complete",
            200,
            "{\"data\": {\"platform\": \"whatsapp\", \"connected\": true, \"server\": {\"id\": \"sample\", \"name\": \"sample\", \"type\": " +
                "null, \"health_status\": null, \"health_checked_at\": null, \"roles\": []}}}",
        )
        val result =
            api().complete("sample-arg", statusToken = "sample-arg", serverId = "sample-arg")
        assertNotNull(result)
        wireMockRule.verify(
            postRequestedFor(urlPathMatching("/v2/community-connections/sample-arg/complete"))
                .withRequestBody(matchingJsonPath("\$.status_token"))
                .withRequestBody(matchingJsonPath("\$.server_id"))
        )
    }

    @Test
    fun `verify returns a typed response`() {
        stubResponse(
            "POST",
            "/v2/community-connections/sample-arg/verify",
            200,
            "{\"data\": {\"platform\": \"discord\", \"healthy_count\": 0, \"issue_count\": 0, \"retried_count\": 0, \"skipped_count\": 0, " +
                "\"skipped_products\": [], \"unchanged_products\": []}}",
        )
        val result = api().verify("sample-arg")
        assertNotNull(result)
    }

    @Test
    fun `disconnect completes without throwing`() {
        stubResponse(
            "DELETE",
            "/v2/community-connections/sample-arg",
            204,
            "{\"data\": {\"platform\": \"discord\", \"disconnected\": true}}",
        )
        api().disconnect("sample-arg")
    }

    @Test
    fun `list translates 401 to UnauthorizedException`() {
        stubResponse("GET", "/v2/community-connections", 401)
        assertThrows(UnauthorizedException::class.java) {
            api().list()
        }
    }

    @Test
    fun `list translates 404 to NotFoundException`() {
        stubResponse("GET", "/v2/community-connections", 404)
        assertThrows(NotFoundException::class.java) {
            api().list()
        }
    }

    @Test
    fun `list translates 429 to RateLimitException`() {
        stubResponse("GET", "/v2/community-connections", 429)
        assertThrows(RateLimitException::class.java) {
            api().list()
        }
    }

    @Test
    fun `list translates 500 to GenericServerException`() {
        stubResponse("GET", "/v2/community-connections", 500)
        assertThrows(GenericServerException::class.java) {
            api().list()
        }
    }
}
