// This file is auto-generated by oagen. Do not edit.

package app.sell.sellapp.promotionsphases

import app.sell.sellapp.SellApp
import app.sell.sellapp.common.http.RawResponse
import app.sell.sellapp.common.http.RequestConfig
import app.sell.sellapp.common.http.RequestOptions
import app.sell.sellapp.common.http.bodyOf
import app.sell.sellapp.common.http.encodePathSegment
import app.sell.sellapp.common.json.runtimeSchema
import app.sell.sellapp.models.ReplacePromotionPhasesRequestApplicationJsonPropertyPhasesItem
import app.sell.sellapp.models.SdkListPromotionPhasesResponseValue200ApplicationJson
import app.sell.sellapp.models.SdkReplacePromotionPhasesResponseValue200ApplicationJson

/**
 * API accessor for PromotionsPhases.
 *
 * Every operation on this class is available in two flavors: a blocking variant (`<methodName>`)
 * and a coroutine-aware variant (`<methodName>Suspend`). The `Suspend` variants delegate to the
 * blocking ones under `withContext(Dispatchers.IO)`, so they are safe to call from any coroutine
 * dispatcher (including `Dispatchers.Main`).
 */
class PromotionsPhases(internal val sellapp: SellApp) {
    /**
     * List promotion phases
     *
     * List a promotion's active phases in evaluation order. OAuth callers use the admin grant and
     * select a store with X-STORE. Current membership and role permissions apply to every request.
     *
     * @param promotion The promotion path parameter.
     * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
     * @return the SdkListPromotionPhasesResponseValue200ApplicationJson
     */
    @JvmOverloads
    fun list(
        promotion: String,
        requestOptions: RequestOptions? = null,
    ): SdkListPromotionPhasesResponseValue200ApplicationJson {
        val config =
            RequestConfig(
                method = "GET",
                path = "/v2/promotions/${encodePathSegment(promotion)}/phases",
                requestOptions = requestOptions,
                responseSchema =
                    app.sell.sellapp.models.SdkListPromotionPhasesResponseValue200ApplicationJson
                        .runtimeSchema,
                operationId = "listPromotionPhases",
                supportsIdempotency = false,
            )
        return sellapp.baseClient.request(
            config,
            SdkListPromotionPhasesResponseValue200ApplicationJson::class.java,
        )
    }

    @Suppress("UNCHECKED_CAST")
    fun listWithResponse(
        promotion: String,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkListPromotionPhasesResponseValue200ApplicationJson> {
        var captured: RawResponse<Any?>? = null
        val capturingOptions =
            (requestOptions?.copy() ?: RequestOptions()).also { options ->
                options.responseCapture = { response -> captured = response }
            }
        list(promotion, capturingOptions)
        return captured as? RawResponse<SdkListPromotionPhasesResponseValue200ApplicationJson>
            ?: error("Response metadata was not captured")
    }

    /**
     * Coroutine-aware variant of [list]. Use this from a `suspend` function or coroutine scope.
     *
     * Delegates to the blocking [list] under `withContext(Dispatchers.IO)`, so this is safe to call
     * from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("listSuspend")
    suspend fun listSuspend(
        promotion: String,
        requestOptions: RequestOptions? = null,
    ): SdkListPromotionPhasesResponseValue200ApplicationJson =
        sellapp.baseClient.runCancellable {
            list(promotion, requestOptions)
        }

    /**
     * Coroutine-aware variant of [listWithResponse]. Use this from a `suspend` function or
     * coroutine scope.
     *
     * Delegates to the blocking [listWithResponse] under `withContext(Dispatchers.IO)`, so this is
     * safe to call from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("listWithResponseSuspend")
    suspend fun listWithResponseSuspend(
        promotion: String,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkListPromotionPhasesResponseValue200ApplicationJson> =
        sellapp.baseClient.runCancellable {
            listWithResponse(promotion, requestOptions)
        }

    /**
     * Replace promotion phases
     *
     * Replace the complete phase set. Array order becomes phase position; at least one phase is
     * required. Historical referenced phases remain soft-deleted. OAuth callers use the admin grant
     * and select a store with X-STORE. Current membership and role permissions apply to every
     * request.
     *
     * @param promotion The promotion path parameter.
     * @param phases the phases of the request.
     * @param requestOptions per-request overrides (idempotency key, API key, headers, timeout)
     * @return the SdkReplacePromotionPhasesResponseValue200ApplicationJson
     */
    @JvmOverloads
    fun replace(
        promotion: String,
        phases: List<ReplacePromotionPhasesRequestApplicationJsonPropertyPhasesItem>,
        requestOptions: RequestOptions? = null,
    ): SdkReplacePromotionPhasesResponseValue200ApplicationJson {
        val body = bodyOf("phases" to phases)
        body["phases"] = phases
        val config =
            RequestConfig(
                method = "PUT",
                path = "/v2/promotions/${encodePathSegment(promotion)}/phases",
                body = body,
                requestOptions = requestOptions,
                requestSchema =
                    app.sell.sellapp.models.SdkReplacePromotionPhasesRequestApplicationJson
                        .runtimeSchema,
                responseSchema =
                    app.sell.sellapp.models.SdkReplacePromotionPhasesResponseValue200ApplicationJson
                        .runtimeSchema,
                operationId = "replacePromotionPhases",
                supportsIdempotency = false,
            )
        return sellapp.baseClient.request(
            config,
            SdkReplacePromotionPhasesResponseValue200ApplicationJson::class.java,
        )
    }

    @Suppress("UNCHECKED_CAST")
    fun replaceWithResponse(
        promotion: String,
        phases: List<ReplacePromotionPhasesRequestApplicationJsonPropertyPhasesItem>,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkReplacePromotionPhasesResponseValue200ApplicationJson> {
        var captured: RawResponse<Any?>? = null
        val capturingOptions =
            (requestOptions?.copy() ?: RequestOptions()).also { options ->
                options.responseCapture = { response -> captured = response }
            }
        replace(promotion, phases, capturingOptions)
        return captured as? RawResponse<SdkReplacePromotionPhasesResponseValue200ApplicationJson>
            ?: error("Response metadata was not captured")
    }

    /**
     * Coroutine-aware variant of [replace]. Use this from a `suspend` function or coroutine scope.
     *
     * Delegates to the blocking [replace] under `withContext(Dispatchers.IO)`, so this is safe to
     * call from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("replaceSuspend")
    suspend fun replaceSuspend(
        promotion: String,
        phases: List<ReplacePromotionPhasesRequestApplicationJsonPropertyPhasesItem>,
        requestOptions: RequestOptions? = null,
    ): SdkReplacePromotionPhasesResponseValue200ApplicationJson =
        sellapp.baseClient.runCancellable {
            replace(promotion, phases, requestOptions)
        }

    /**
     * Coroutine-aware variant of [replaceWithResponse]. Use this from a `suspend` function or
     * coroutine scope.
     *
     * Delegates to the blocking [replaceWithResponse] under `withContext(Dispatchers.IO)`, so this
     * is safe to call from any coroutine dispatcher (including `Dispatchers.Main`).
     */
    @JvmName("replaceWithResponseSuspend")
    suspend fun replaceWithResponseSuspend(
        promotion: String,
        phases: List<ReplacePromotionPhasesRequestApplicationJsonPropertyPhasesItem>,
        requestOptions: RequestOptions? = null,
    ): RawResponse<SdkReplacePromotionPhasesResponseValue200ApplicationJson> =
        sellapp.baseClient.runCancellable {
            replaceWithResponse(promotion, phases, requestOptions)
        }
}
